### ISSUE TITLE
[Bug][Ascend] Qwen3-Next-80B-A3B-Instruct not support uinit64 yet?

### ISSUE THREAD

**Issue by tomant1024** [sgl-project/sglang#10402]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

when I run Qwen3-Next-80B-A3B-Instruct , got error below
[2025-09-13 05:28:15 TP4] Scheduler hit an exception: Traceback (most recent call last):
File "/workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2615, in run_scheduler_process
scheduler = Scheduler(
^^^^^^^^^^
File "/workspace/sglang/python/sglang/srt/managers/scheduler.py", line 333, in init
self.tp_worker = TpWorkerClass(
^^^^^^^^^^^^^^
File "/workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 73, in init
self.worker = TpModelWorker(
^^^^^^^^^^^^^^
File "/workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 96, in init
self.model_runner = ModelRunner(
^^^^^^^^^^^^
File "/workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 259, in init
self.initialize(min_per_gpu_memory)
File "/workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 388, in initialize
self.init_memory_pool(
File "/workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1587, in init_memory_pool
self.token_to_kv_pool = MHATokenToKVPool(
^^^^^^^^^^^^^^^^^
File "/workspace/sglang/python/sglang/srt/mem_cache/memory_pool.py", line 435, in init
self._create_buffers()
File "/workspace/sglang/python/sglang/srt/mem_cache/memory_pool.py", line 477, in _create_buffers
self.data_ptrs = torch.cat([self.k_data_ptrs, self.v_data_ptrs], dim=0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cat:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:265 NPU function error: call aclnnCat failed, error code is 161002
[ERROR] 2025-09-13-05:28:15 (PID:55172, Device:4, RankID:-1) ERR00100 PTA call acl api failed.
EZ1001: [PID: 55172] 2025-09-13-05:28:15.526.256 tensor 0 not implemented for DT_UINT64, should be in dtype support list [DT_FLOAT,DT_INT32,DT_INT64,DT_FLOAT16,DT_INT16,DT_INT8,DT_UINT8,DT_DOUBLE,DT_COMPLEX64,DT_BFLOAT16,DT_BOOL,].

ascendd not support uinit64 yet?

### Reproduction

run qwen3 next

### Environment

cann + pytorch_npu 2.6 + torch2.6

**Comment by ping1jing2** [comment]
1. pull docker image. `docker pull lmsysorg/sglang:main-cann8.2.rc1-910b`
2. download [bisheng](https://sglang-ascend.obs.cn-east-3.myhuaweicloud.com/sglang/Ascend-BiSheng-toolkit_aarch64.run?AccessKeyId=HPUAXT4YM0U8JNTERLST&Expires=1788772129&Signature=NDiPdW4C7P6Af4sog/irX8pLch0%3D) and [triton_ascend](https://sglang-ascend.obs.cn-east-3.myhuaweicloud.com/sglang/triton_ascend-3.2.0%2Bgitb0ea0850-cp311-cp311-linux_aarch64.whl?AccessKeyId=HPUAXT4YM0U8JNTERLST&Expires=1788772152&Signature=LGDphSSSRjhGtlx/F4oLADafVTI%3D).
3. install bisheng and triton-ascend
    ```shell
    pip install triton_ascend-3.2.0+gitb0ea0850-cp311-cp311-linux_aarch64.whl
    ./Ascend-BiSheng-toolkit_aarch64.run --install
    source /usr/local/Ascend/ascend-toolkit/latest/bisheng_toolkit/set_env.sh
   ```
4. install sgl-kernel refer to [README.md](https://github.com/sgl-project/sgl-kernel-npu/blob/main/python/sgl_kernel_npu/README.md)
5. test
    ```shell
      python -m sglang.launch_server --model-path {weight_path} --host 127.0.0.1 --port 6688 --trust-remote-code --nnodes 1 --node-rank 0  --attention-backend hybrid_linear_attn --device npu   --max-running-requests 32 --context-length 8192  --disable-radix-cache --chunked-prefill-size 32768 --max-prefill-tokens 28000  --tp-size 16  --mem-fraction-static 0.5 --disable-cuda-graph

   ```

**Comment by ping1jing2** [comment]
had confirmed it been solved, closed it.

**Comment by zhangguinan** [comment]
root@A800T-10:~# docker search lmsysorg/sglang:main-cann8.2.rc1-910b
Error response from daemon: Get "https://index.docker.io/v1/search?q=lmsysorg%2Fsglang%3Amain-cann8.2.rc1-910b&n=25": Gateway Time-out
root@A800T-10:~#
@ping1jing2
