### ISSUE TITLE
[Bug] After service, `torch.distributed.DistBackendError`

### ISSUE THREAD

**Issue by YinSonglin1997** [sgl-project/sglang#1116]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

I have 4 A100(40G), I followed the instructions below:
`python -m sglang.launch_server --model-path /ldata/llms/Meta-Llama-3.1-70B-Instruct --host 0.0.0.0 --port 30000 --tp 4 --mem-fraction-static 0.95 --disable-cuda-graph`
Then it reported an error:
```
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.cpp:76, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.20.5
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Failed to CUDA calloc 67108864 bytes
```
How can I fix it？
![捕获](https://github.com/user-attachments/assets/2372cb23-6034-4402-8167-24773feac4e5)

### Reproduction

command: `python -m sglang.launch_server --model-path /ldata/llms/Meta-Llama-3.1-70B-Instruct --host 0.0.0.0 --port 30000 --tp 4 --mem-fraction-static 0.95 --disable-cuda-graph`
model: `Meta-Llama-3.1-70B-Instruct`

### Environment

Python: 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) [GCC 12.3.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A100-PCIE-40GB
GPU 0,1,2,3 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda-11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
CUDA Driver Version: 535.86.10
PyTorch: 2.4.0+cu121
sglang: 0.2.12
flashinfer: 0.1.4+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.3
fastapi: 0.112.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 26.1.0
vllm: 0.5.4
multipart: 0.0.9
openai: 1.40.8
anthropic: 0.34.0

**Comment by zhyncs** [comment]
It works for me and you can refer to my environment and run commands.
```
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A100 80GB PCIe
GPU 0,1,2,3 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 545.23.08
PyTorch: 2.4.0+cu121
sglang: 0.2.13
flashinfer: 0.1.5+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.3
aiohttp: 3.10.3
fastapi: 0.112.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 23.2
PIL: 10.2.0
psutil: 5.9.8
pydantic: 2.8.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 24.0.1
vllm: 0.5.4
multipart: 0.0.9
openai: 1.41.0
anthropic: 0.34.0
NVIDIA Topology:
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PHB     PHB     PHB     0-251   0               N/A
GPU1    PHB      X      PHB     PHB     0-251   0               N/A
GPU2    PHB     PHB      X      PHB     0-251   0               N/A
GPU3    PHB     PHB     PHB      X      0-251   0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1048576
```

```
# server
python -m sglang.launch_server --model-path meta-llama/Meta-Llama-3.1-70B-Instruct --tp 4 --disable-radix-cache --enable-p2p-check

# client
python -m sglang.bench_serving --backend sglang --num-prompts 10
```

```
============ Serving Benchmark Result ============
Backend:                                 sglang
Traffic request rate:                    inf
Successful requests:                     10
Benchmark duration (s):                  42.87
Total input tokens:                      1369
Total generated tokens:                  2278
Total generated tokens (retokenized):    2268
Request throughput (req/s):              0.23
Input token throughput (tok/s):          31.93
Output token throughput (tok/s):         53.14
----------------End-to-End Latency----------------
Mean E2E Latency (ms):                   16760.78
Median E2E Latency (ms):                 11625.66
---------------Time to First Token----------------
Mean TTFT (ms):                          4175.83
Median TTFT (ms):                        4582.61
P99 TTFT (ms):                           4774.11
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          66.01
Median TPOT (ms):                        64.35
P99 TPOT (ms):                           100.07
---------------Inter-token Latency----------------
Mean ITL (ms):                           55.78
Median ITL (ms):                         50.80
P99 ITL (ms):                            106.39
==================================================
```

**Comment by merrymercy** [comment]
reduce `--mem-fraction-static`, 0.95 is too high.
