### ISSUE TITLE
[Bug] Qwen3-235B-A22B-Instruct-W8A8 is very easy npu OOM

### ISSUE THREAD

**Issue by hyena126** [sgl-project/sglang#12016]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

no any other complex configugres, mem-fraction-statio < 0.9 almost can not start service.  even context_len very small
for example： 
for 800I A2 single node，if context_len=10K，mem-fraction-statio must > 0.92, is not correct；
for 800I A2，1P(8 npus)1D(8 npus) disaggregation , context_len=4K，mem-fraction-statio must > 0.95, even 0.98

### Environment

800I A2 64G, 2 nodes,  stand-alone computer(using 8 fiber to connect the npus)

**Comment by ssshinigami** [comment]
Could you please provide full command to run server?

**Comment by lfy-code123** [comment]
> The issue has been resolved. Please wait for [#12078](https://github.com/sgl-project/sglang/pull/12078) to be merged. Then pull the latest code and try again.

@hyena126
