### ISSUE TITLE
[Bug] #11708 breaks FP8 SM120 inference

### ISSUE THREAD

**Issue by voipmonitor** [sgl-project/sglang#12280]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

commit 88596739a4637ad10a98d09473e71cee8064b9ec which is part of #11708  breaks FP8 GLM-4.6 inference 

### Reproduction

NCCL_P2P_LEVEL=4 NCCL_DEBUG=INFO PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True USE_TRITON_W8A8_FP8_KERNEL=1 SGL_ENABLE_JIT_DEEPGEMM=0 python -m sglang.launch_server --model /mnt/GLM-4.6-FP8/ --tp 4 --host 0.0.0.0 --port  4999 --mem-fraction-static 0.96 --context-length 200000  --enable-metrics  --attention-backend flashinfer   --tool-call-parser glm45    --reasoning-parser glm45   --served-model-name glm-4.5-air   --chunked-prefill-size 8092 --enable-mixed-chunk   --cuda-graph-max-bs 16   --kv-cache-dtype fp8_e5m2  --model-loader-extra-config '{"enable_multithread_load": true, "num_threads": 8}'

the inference output is completely garbled and the output containts: 

Failed to initialize the CUTLASS kernel. Last CUDA error is: Failed to initialize the CUTLASS kernel. Last CUDA error is: Failed to initialize the CUTLASS kernel. Last CUDA error is: Failed to initialize the CUTLASS kernel. Last CUDA error is: no errorno errorno errorno error
Failed to launch the CUTLASS kernel. Last CUDA error is: Failed to launch the CUTLASS kernel. Last CUDA error is: Failed to launch the CUTLASS kernel. Last CUDA error is: Failed to launch the CUTLASS kernel. Last CUDA error is: no errorno errorno errorno error
Failed to initialize the CUTLASS kernel. Last CUDA error is: no error
Failed to initialize the CUTLASS kernel. Last CUDA error is: no error
Failed to launch the CUTLASS kernel. Last CUDA error is: no error

### Environment

I have tried sglang docker and also compiled in my environment - same issue.

**Comment by chisleu** [comment]
Same problem here. I tried to upgrade from 0.5.2 this morning to the latest prerelease and encountered this regression.

**Comment by voipmonitor** [comment]
the problem is in python/sglang/srt/layers/attention/flashinfer_backend.py  and 

 is_blackwell_supported():
                      self.fmha_backend = "cutlass"

it was "auto" and not "cutlass" - is the cutlass supposed to work on sm120? If I force it to "auto" the problem is gone.

**Comment by Fridge003** [comment]
Thanks for reporting this bug @voipmonitor
To be fixed in #12325

**Comment by voipmonitor** [comment]
> Thanks for reporting this bug [@voipmonitor](https://github.com/voipmonitor) To be fixed in [#12325](https://github.com/sgl-project/sglang/pull/12325)

thanks - I have just asked why forcing it to the fa2 and not let it "auto"

**Comment by voipmonitor** [comment]
fixed in the latest git
