### ISSUE TITLE
[Bug] FlashAttention kernel crash on Ascend backend with long sequence length (seq_len up to 128k), LEval dataset

### ISSUE THREAD

**Issue by Comtive-Wdson** [sgl-project/sglang#12342]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

When running sglang with the Ascend attention backend, I encountered kernel crashes during benchmarking with LEval.

It seems to be caused by  out-of-range memory access (DDR address out of range)  in FlashAttentionScore kernel.

The issue might related to long sequence lengths(128k), as it dose not occur in dataset like ShareGPT. I wonder whether the fault is caused by the kernel's inability to handle long sequences or by a memory-management bug.

Bug

```shell
[rank3]:[E1029 21:38:50.006206870 compiler_depend.ts:429] operator():build/CMakeFiles/torch_npu.dir/compiler_depend.ts:54 NPU function error: call aclnnAddmm failed, error code is 507015
[ERROR] 2025-10-29-21:38:50 (PID:2797081, Device:3, RankID:-1) ERR00100 PTA call acl api failed
[Error]: The aicore execution is abnormal. 
        Rectify the fault based on the error information in the ascend log.
EZ9903: [PID: 2797081] 2025-10-29-21:38:50.593.236 rtKernelLaunchWithHandleV2 failed: 507015
        Solution: In this scenario, collect the plog when the fault occurs and locate the fault based on the plog.
        TraceBack (most recent call last):
        The error from device(chipId:5, dieId:0), serial number is 8, there is an exception of fftsplus aivector error, core id is 0, error code = 0x800000, dump info: pc start: 0x12ce9f1488d8, current: 0x12ce9f14c718, vec error info: 0xeb00d760b4, mte error info: 0x580600000d, ifu error info: 0x2e3e7b26828c0, ccu error info: 0x681c3e8f14a0001d, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c11c714080.[FUNC:ProcessStarsCoreErrorInfo][FILE:device_error_core_proc.cc][LINE:303]
        The extend info: errcode:(0x800000, 0, 0) errorStr: The DDR address of the MTE instruction is out of range. fixp_error0 info: 0x600000d, fixp_error1 info: 0x58, fsmId:0, tslot:1, thread:0, ctxid:0, blk:15, sublk:1, subErrType:4.[FUNC:ProcessStarsCoreErrorInfo][FILE:device_error_core_proc.cc][LINE:322]
        Kernel task happen error, retCode=0x26, [aicore exception].[FUNC:PreCheckTaskErr][FILE:davinci_kernel_task.cc][LINE:1539]
        AICORE Kernel task happen error, retCode=0x26.[FUNC:GetError][FILE:stream.cc][LINE:1183]
        [AIC_INFO] after execute:args print end[FUNC:GetError][FILE:stream.cc][LINE:1183]
        [AIC_INFO] after execute:mixCtx print end[FUNC:GetError][FILE:stream.cc][LINE:1183]
        Aicore kernel execute failed, device_id=5, stream_id=6, report_stream_id=6, task_id=35859, flip_num=4, fault kernel_name=FlashAttentionScore_8c70d0f9d000516023d9390793106fdc_10000000000022420943, fault kernel info ext=none, program id=427, hash=2291774960824917303.[FUNC:GetError][FILE:stream.cc][LINE:1183]
        Failed to submit kernel task, retCode=0x7150026.[FUNC:LaunchKernelSubmit][FILE:context.cc][LINE:1206]
        kernel launch submit failed.[FUNC:LaunchKernelWithHandle][FILE:context.cc][LINE:1460]
        rtKernelLaunchWithHandleV2 execute failed, reason=[aicore exception][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
        rtKernelLaunchWithHandleV2 failed: 507015
        #### KernelLaunch failed: /usr/local/Ascend/ascend-toolkit/8.2.RC1/opp/built-in/op_impl/ai_core/tbe//kernel/ascend910b/cast/Cast_b2717900ea7de2d41ea9c63d23aa269b_high_performance.o
        Kernel Run failed. opType: 11, Cast
        launch failed for Cast, errno:361001.
```

```shell
Exception raised from operator() at build/CMakeFiles/torch_npu.dir/compiler_depend.ts:54 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xd4 (0xffff9aada9e4 in /root/miniconda3/envs/sglang/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xe4 (0xffff9aa8d384 in /root/miniconda3/envs/sglang/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0xbe4074 (0xfffe8a8f4074 in /root/miniconda3/envs/sglang/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #3: <unknown function> + 0x20da2b4 (0xfffe8bdea2b4 in /root/miniconda3/envs/sglang/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #4: <unknown function> + 0x89fd50 (0xfffe8a5afd50 in /root/miniconda3/envs/sglang/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #5: <unknown function> + 0x8a20e4 (0xfffe8a5b20e4 in /root/miniconda3/envs/sglang/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #6: <unknown function> + 0x89ea0c (0xfffe8a5aea0c in /root/miniconda3/envs/sglang/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #7: <unknown function> + 0x101d98 (0xffffa6351d98 in /root/miniconda3/envs/sglang/bin/../lib/libstdc++.so.6)
frame #8: <unknown function> + 0x7d5c8 (0xffffac84d5c8 in /lib/aarch64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0xe5edc (0xffffac8b5edc in /lib/aarch64-linux-gnu/libc.so.6)

[2025-10-29 21:38:50 TP3] Scheduler hit an exception: Traceback (most recent call last):
  File "/mnt/nvm/sglang/python/sglang/srt/managers/scheduler.py", line 2672, in run_scheduler_process
    scheduler.event_loop_overlap()
  File "/root/miniconda3/envs/sglang/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvm/sglang/python/sglang/srt/managers/scheduler.py", line 839, in event_loop_overlap
    self.process_batch_result(
  File "/mnt/nvm/sglang/python/sglang/srt/managers/scheduler.py", line 1868, in process_batch_result
    self.process_batch_result_prefill(batch, result, launch_done)
  File "/mnt/nvm/sglang/python/sglang/srt/managers/scheduler_output_processor_mixin.py", line 55, in process_batch_result_prefill
    self.tp_worker.resolve_last_batch_result(launch_done)
  File "/mnt/nvm/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 218, in resolve_last_batch_result
    copy_done.synchronize()
  File "/root/miniconda3/envs/sglang/lib/python3.11/site-packages/torch_npu/npu/streams.py", line 187, in synchronize
    super(Event, self).synchronize()
RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnAddmm.
Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
[ERROR] 2025-10-29-21:38:50 (PID:2797081, Device:3, RankID:-1) ERR00100 PTA call acl api failed.
```

By the way, if set `--max-concurrency 32`in client, the server will not encounter such error, but facing `watchdog timeout` after serving several requests.

### Reproduction

Add benchmarking for LEval dataset, which is a long-context(128k) dataset.
```shell
git clone https://github.com/OpenLMLab/LEval.git
```

```python
#bench_serving.py
#add leval dataset sampling in bench_serving.py
elif args.dataset_name == "leval":
        input_requests = sample_leval_requests(
            dataset_path="/<local way to LEval>/LEval-data",   #update the dataset_path
            num_requests=2000,
            tokenizer=tokenizer,
        )
#...
def sample_leval_requests(
    dataset_path: str,
    num_requests: int,
    tokenizer: PreTrainedTokenizerBase,
) -> List[Tuple[str, int, int]]:
    files = []
    for root, dirs, filenames in os.walk(dataset_path):
        for filename in filenames:
            if filename.endswith(".jsonl"):
                files.append(os.path.join(root, filename))

    num_lines = sum(
        [
            sum(
                [
                    len(json.loads(line)["instructions"])
                    for line in open(filename, "r").readlines()
                ]
            )
            for filename in files
        ]
    )

    filtered_dataset: List[Tuple[str, int, int]] = []
    for file in files:
        print(f"Processing {file}")
        with open(file, "r") as f:
            for line in f.readlines():
                if line.strip() == "":
                    continue
                data = json.loads(line)

                input = data["input"]
                input_len = len(tokenizer.tokenize(input))
                for instruction, output in zip(data["instructions"], data["outputs"]):
                    prompt = input + instruction
                    prompt_len = input_len + len(tokenizer.tokenize(instruction))
                    output_len = len(tokenizer.tokenize(output))
                    if prompt_len >= 128000:
                        prompt = prompt[:12800]
                        prompt_len = 12800
                    filtered_dataset.append(
                        DatasetRow(
                            prompt=prompt,
                            prompt_len=prompt_len,
                            output_len=output_len,
                        )
                    )

    print(f"#LEval num prompts: {len(filtered_dataset)}")
    print(f"#Input tokens: {np.sum([data.prompt_len for data in filtered_dataset])}")
    print(f"#Output tokens: {np.sum([data.output_len for data in filtered_dataset])}")
    return filtered_dataset

#add "leval" in parser.add_argument "--dataset-name"

```

Command
```shell
python -m sglang.launch_server --model-path /mnt/model/Qwen/Qwen2.5-7B --attention-backend ascend --tp-size 4 --port 30000 --host 0.0.0.0
```

```shell
python3 bench_serving.py --backend sglang --dataset-name leval --request-rate 3.5
```

### Environment

Hardware: 4x Ascend 910B3

CANN: 8.2.RC1

Pytorch: 2.6

Python: 3.11

**Comment by Comtive-Wdson** [comment]
For supplementary,
If using default max concurrency value in client, the error will be shown as above.

If set `--max-concurrency 1` in client,  the server will raise memory checking error `ValueError: token_to_kv_pool_allocator memory leak detected! self.max_total_num_tokens=3392128, available_size=2281472, evictable_size=1110784, protected_size=0`

If set `--max-concurrecy 32` in client, the server will raise `watchdog timeout` after serving several requests.

Such errors will not occur when serving short-context datasets like ShareGPT.

It seems to be caused by kernel's inability to handle long sequences or by a memory-management bug.

**Comment by Comtive-Wdson** [comment]
I got confused with different operators when trying to support varlen operator. Solved after reverting to original operator `torch_npu._npu_flash_attention_qlens`
