### ISSUE TITLE
[Bug Deepseek v3.2  not work with docker images

### ISSUE THREAD

**Issue by openzeka-birol-kuyumcu** [sgl-project/sglang#14700]
### Checklist

- [x] I searched related issues but found no solution.
- [x] The bug persists in the latest version.
- [x] Issues without environment info and a minimal reproducible demo are hard to resolve and may receive no feedback.
- [x] If this is not a bug report but a general question, please start a discussion at https://github.com/sgl-project/sglang/discussions. Otherwise, it will be closed.
- [x] Please use English. Otherwise, it will be closed.

### Describe the bug

i use B300 GPUs
When I try to use Deepseek v3.2 with  sglang:dsv32 docker image
I get the following error:

> [2025-12-09 04:55:34 DP1 TP1] Using FP8 KV cache but no scaling factors provided. Defaulting to scaling factors of 1.0. This may lead to less accurate results!
[2025-12-09 04:55:34 DP0 TP0] Using FP8 KV cache but no scaling factors provided. Defaulting to scaling factors of 1.0. This may lead to less accurate results!
[2025-12-09 04:55:34 DP0 TP0] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=172.51 GB, mem usage=93.06 GB.
[2025-12-09 04:55:34 DP6 TP6] Using FP8 KV cache but no scaling factors provided. Defaulting to scaling factors of 1.0. This may lead to less accurate results!
[2025-12-09 04:55:34 DP5 TP5] Using FP8 KV cache but no scaling factors provided. Defaulting to scaling factors of 1.0. This may lead to less accurate results!
[2025-12-09 04:55:34 DP7 TP7] Using FP8 KV cache but no scaling factors provided. Defaulting to scaling factors of 1.0. This may lead to less accurate results!
[2025-12-09 04:55:34 DP4 TP4] Using FP8 KV cache but no scaling factors provided. Defaulting to scaling factors of 1.0. This may lead to less accurate results!
[2025-12-09 04:55:35 DP2 TP2] Using FP8 KV cache but no scaling factors provided. Defaulting to scaling factors of 1.0. This may lead to less accurate results!
[2025-12-09 04:55:35 DP3 TP3] Using FP8 KV cache but no scaling factors provided. Defaulting to scaling factors of 1.0. This may lead to less accurate results!
[2025-12-09 04:55:35 DP0 TP0] Using KV cache dtype: torch.float8_e4m3fn
[2025-12-09 04:55:35 DP0 TP0] KV Cache is allocated. #tokens: 3646912, KV size: 135.91 GB
[2025-12-09 04:55:35 DP5 TP5] KV Cache is allocated. #tokens: 3646912, KV size: 135.91 GB
[2025-12-09 04:55:35 DP3 TP3] KV Cache is allocated. #tokens: 3646912, KV size: 135.91 GB
[2025-12-09 04:55:35 DP4 TP4] KV Cache is allocated. #tokens: 3646912, KV size: 135.91 GB
[2025-12-09 04:55:35 DP7 TP7] KV Cache is allocated. #tokens: 3646912, KV size: 135.91 GB
[2025-12-09 04:55:35 DP6 TP6] KV Cache is allocated. #tokens: 3646912, KV size: 135.91 GB
[2025-12-09 04:55:35 DP2 TP2] KV Cache is allocated. #tokens: 3646912, KV size: 135.91 GB
[2025-12-09 04:55:35 DP1 TP1] KV Cache is allocated. #tokens: 3646912, KV size: 135.91 GB
[2025-12-09 04:55:35 DP0 TP0] Memory pool end. avail mem=6.66 GB
CUDA error (/sgl-workspace/flash-mla/csrc/smxx/get_mla_metadata.cu:93): no kernel image is available for execution on the device
[2025-12-09 04:55:44 DP0 TP0] Capture cuda graph begin. This can take up to several minutes. avail mem=6.60 GB
[2025-12-09 04:55:44 DP0 TP0] Capture cuda graph bs [1, 2, 4, 8, 12, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512]
CUDA error (/sgl-workspace/flash-mla/csrc/smxx/get_mla_metadata.cu:93): no kernel image is available for execution on the device
CUDA error (/sgl-workspace/flash-mla/csrc/smxx/get_mla_metadata.cu:93): no kernel image is available for execution on the device
[2025-12-09 04:55:44] DataParallelController hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang-private/python/sglang/srt/managers/data_parallel_controller.py", line 392, in run_data_parallel_controller_process
    controller = DataParallelController(server_args, port_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sgl-workspace/sglang-private/python/sglang/srt/managers/data_parallel_controller.py", line 143, in __init__
    dp_port_args = self.launch_dp_attention_schedulers(server_args, port_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sgl-workspace/sglang-private/python/sglang/srt/managers/data_parallel_controller.py", line 245, in launch_dp_attention_schedulers
    self.launch_tensor_parallel_group(server_args, port_args, 0, None)
  File "/sgl-workspace/sglang-private/python/sglang/srt/managers/data_parallel_controller.py", line 327, in launch_tensor_parallel_group
    scheduler_info.append(scheduler_pipe_readers[i].recv())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError
[2025-12-09 04:55:44] Received sigquit from a child process. It usually means the child failed.

When I try to use Deepseek v3.2 with  sglang:dev-cu13 docker image
I get the following error:

> 
> [2025-12-09 05:12:15 DP5 TP5] KV Cache is allocated. #tokens: 3627136, KV size: 162.38 GB
> [2025-12-09 05:12:15 DP5 TP5] Memory pool end. avail mem=7.43 GB
> [2025-12-09 05:12:23 DP6 TP6] Capture cuda graph begin. This can take up to several minutes. avail mem=6.99 GB
> CUDA error (_deps/repo-flashmla-src/csrc/smxx/get_mla_metadata.cu:93): no kernel image is available for execution on the device
> [2025-12-09 05:12:24 DP2 TP2] Capture cuda graph begin. This can take up to several minutes. avail mem=6.99 GB
> CUDA error (_deps/repo-flashmla-src/csrc/smxx/get_mla_metadata.cu:93): no kernel image is available for execution on the device
> [2025-12-09 05:12:24 DP7 TP7] Capture cuda graph begin. This can take up to several minutes. avail mem=7.31 GB
> CUDA error (_deps/repo-flashmla-src/csrc/smxx/get_mla_metadata.cu:93): no kernel image is available for execution on the device
> [2025-12-09 05:12:24 DP3 TP3] Capture cuda graph begin. This can take up to several minutes. avail mem=6.99 GB
> CUDA error (_deps/repo-flashmla-src/csrc/smxx/get_mla_metadata.cu:93): no kernel image is available for execution on the device
> [2025-12-09 05:12:24 DP0 TP0] Capture cuda graph begin. This can take up to several minutes. avail mem=7.06 GB
> [2025-12-09 05:12:24 DP0 TP0] Capture cuda graph bs [1, 2, 4, 8, 12, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512]
> CUDA error (_deps/repo-flashmla-src/csrc/smxx/get_mla_metadata.cu:93): no kernel image is available for execution on the device
> [2025-12-09 05:12:24 DP4 TP4] Capture cuda graph begin. This can take up to several minutes. avail mem=6.99 GB
> CUDA error (_deps/repo-flashmla-src/csrc/smxx/get_mla_metadata.cu:93): no kernel image is available for execution on the device
> [2025-12-09 05:12:24 DP1 TP1] Capture cuda graph begin. This can take up to several minutes. avail mem=6.99 GB
> CUDA error (_deps/repo-flashmla-src/csrc/smxx/get_mla_metadata.cu:93): no kernel image is available for execution on the device
> [2025-12-09 05:12:24] DataParallelController hit an exception: Traceback (most recent call last):
>   File "/sgl-workspace/sglang/python/sglang/srt/managers/data_parallel_controller.py", line 529, in run_data_parallel_controller_process
>     controller = data_parallel_controller_class(server_args, port_args)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/sgl-workspace/sglang/python/sglang/srt/managers/data_parallel_controller.py", line 160, in __init__
>     self.launch_dp_attention_schedulers(server_args, port_args)
>   File "/sgl-workspace/sglang/python/sglang/srt/managers/data_parallel_controller.py", line 366, in launch_dp_attention_schedulers
>     self.launch_tensor_parallel_group(
>   File "/sgl-workspace/sglang/python/sglang/srt/managers/data_parallel_controller.py", line 451, in launch_tensor_parallel_group
>     scheduler_info.append(scheduler_pipe_readers[i].recv())
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
>     buf = self._recv_bytes()
>           ^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
>     buf = self._recv(4)
>           ^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
>     raise EOFError
> EOFError
> 
> 

### Reproduction

docker run --gpus all --rm \
     -p 30000:8000 \
     --ipc=host \
     lmsysorg/sglang:dsv32 \
     python3 -m sglang.launch_server \
     --model-path deepseek-ai/DeepSeek-V3.2 \
     --tp-size 8 \
     --mem-fraction-static 0.9 \
     --served-model-name DeepSeek-V3.2 \
     --host 0.0.0.0 \
     --port 8000 

### Environment

official docker images
sglang:dsv32  and  sglang:dev-cu13

**Comment by ForcewithMe66** [comment]
> Hi [@Fridge003](https://github.com/Fridge003) , I used 8*H20-3e(141G)，which is sm_90, also met this problem. So this EOFError isn't only for sm_103.

@Fridge003 
I have fixed this issues. It automatically installed torch2.9.1+cu13 when installing sglang, while my Nvidia drivers only support cu12.x. When I re-installed torch2.9.1+cu129, everything works fine.

**Comment by openzeka-birol-kuyumcu** [comment]
latest dev-cu13  works thanks 

https://hub.docker.com/layers/lmsysorg/sglang/dev-cu13/images/sha256-105e46e1564a238ef688e2bc0527d50e6faab3988c12ace661dc751da7075a55
