### ISSUE TITLE
[Bug] Abnormal memory growth on GPU 0 (Rank 0) accumulating ~20GB extra overhead leading to OOM with Qwen3-VL-235B

### ISSUE THREAD

**Issue by biandh** [sgl-project/sglang#15871]
### Checklist

- [x] I searched related issues but found no solution.
- [x] The bug persists in the latest version.
- [ ] Issues without environment info and a minimal reproducible demo are hard to resolve and may receive no feedback.
- [ ] If this is not a bug report but a general question, please start a discussion at https://github.com/sgl-project/sglang/discussions. Otherwise, it will be closed.
- [ ] Please use English. Otherwise, it will be closed.

### Describe the bug

Model: Qwen3-VL-235B-Instruct-FP8
Hardware: 8x NVIDIA H20 (96GB VRAM)
SGLang Version: Main branch (installed via uv)
Launch Config: TP=8, EP=8, Disable CUDA Graph, Chunked Prefill enabled.
1. Issue Summary
When serving Qwen3-VL-235B on an 8x H20 node, I observed a severe memory imbalance and potential memory leak on GPU 0 (Rank 0).
While other GPUs (Rank 1-7) maintain stable memory usage, GPU 0 consumes significantly more memory. Over time or during startup/compilation, an "extra" process (or unreleased memory handle) appears on GPU 0, occupying ~20GB of VRAM, eventually causing an OOM error even when mem-fraction-static is lowered.
2. Observed Behavior
Initial State: All GPUs load weights (~28GB) and allocate KV Cache normally.
The Issue: A specific PID (sometimes invisible in ps but visible in nvidia-smi as a large allocation, or sometimes appears as a secondary python process) occupies increasing memory on GPU 0.
Growth: The gap between GPU 0 and other GPUs widens to approximately 20GB.
Result: GPU 0 hits 100% memory usage and crashes the server with OOM, while other GPUs still have ~15GB free space.
Zombie Process: In some cases, after the server crashes, a "ghost" PID remains on GPU 0 occupying ~14-20GB VRAM, which cannot be found via ps or /proc but requires a gpu-reset to clear.

I am attaching 5 nvitop screenshots and logs to demonstrate the timeline of the memory leak:

1. Before starting the server:
<img width="1422" height="607" alt="Image" src="https://github.com/user-attachments/assets/de31015b-0654-4517-a14e-2010094f351c" />

2. Idle state immediately after startup:
<img width="1432" height="652" alt="Image" src="https://github.com/user-attachments/assets/5bc6b3d8-dc94-47bb-99bc-7798d15340f0" />

3. During runtime (Accumulation):
<img width="1437" height="663" alt="Image" src="https://github.com/user-attachments/assets/25f4e75e-d7bf-44aa-af16-89052967732e" />
<img width="1438" height="633" alt="Image" src="https://github.com/user-attachments/assets/6680a66b-57d2-4d4a-b24d-ae1f80c69f94" />

4. Critical state (Near OOM):
<img width="1445" height="665" alt="Image" src="https://github.com/user-attachments/assets/7bac8d43-e38f-4d01-960f-2b9128ce9cb8" />

<img width="1433" height="660" alt="Image" src="https://github.com/user-attachments/assets/044e5373-77f6-4f71-8b2d-d3818064ef71" />

another node
<img width="1408" height="647" alt="Image" src="https://github.com/user-attachments/assets/856407de-1b09-4854-9e8e-0433faac7bd1" />

5. OOM Error Log:
<img width="1435" height="622" alt="Image" src="https://github.com/user-attachments/assets/886b9ad6-7d89-4a88-8fbc-01e291bc6374" />

To summarize, my workload is actually quite conservative: I am running with only 2 concurrent requests, and the maximum context length is around 100k tokens.

Given this setup, the behavior on GPU 0 is very concerning. I have a few specific questions regarding this ~20GB overhead:

What specific component in SGLang is consuming this extra 20GB on Rank 0? Is it the Scheduler, the Image Processor, or the TorchInductor compilation cache accumulating without release?

Is this memory growth unbounded? If I were using GPUs with larger VRAM (e.g., A100 80G or H100), would this occupation continue to grow indefinitely?

How can we limit this overhead? Without a mechanism to cap this specific memory usage on Rank 0, an OOM seems inevitable over time, regardless of how much we lower the mem-fraction-static for the KV cache.

### Reproduction

export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256 
export SGLANG_VLM_CACHE_SIZE_MB=1024
export SGLANG_VLM_MAX_IMAGES_PER_VIT=1 
export SGLANG_VLM_MAX_PATCHES_PER_VIT=4096  

uv run python -m sglang.launch_server \
  --model-path Qwen/Qwen3-VL-235B-A22B-Instruct-FP8 \
  --tp 8 \
  --ep 8 \
  --port 8000 \
  --mem-fraction-static 0.4 \
  --host 0.0.0.0 \
  --disable-custom-all-reduce \
  --log-level info \
  --max-running-requests 4 \
  --max-total-tokens 240000 \
  --context-length 120000 \
  --max-prefill-tokens 2048 \
  --chunked-prefill-size 1024 \
  --allow-auto-truncate \
  --attention-backend flashinfer \
  --sampling-backend flashinfer \
  --enable-metrics \
  --enable-memory-saver \
  --served-model-name Qwen3-VL-Instruct \
  --model-loader-extra-config '{"enable_multithread_load": true, "num_threads": 8}' \
  --grammar-backend xgrammar

### Environment

    uv pip install --upgrade "sglang[all] @ git+https://github.com/sgl-project/sglang.git#subdirectory=python"
    uv pip install "qwen_vl_utils>=0.0.14"
    uv pip install flash-attn --no-build-isolation
    uv pip install nvidia-cudnn-cu12==9.16.0.29

[run_sglang_qwen_235b.log](https://github.com/user-attachments/files/24345906/run_sglang_qwen_235b.log)

**Comment by ryan762** [comment]
You can try adding these two parameters: --disable-fast-image-processor --grammar-backend none

**Comment by biandh** [comment]
Thanks @ryan762 for the suggestion. I have tested the workaround, and here are the results:

**1. Configuration Changes:**
*   **Grammar:** I switched to `--grammar-backend outlines` (instead of `none` or `xgrammar`) as I require JSON schema output.
*   **Image Processor:** I added `--disable-fast-image-processor` as suggested.

**2. Results:**
*   **Memory:** The memory usage on GPU 0 has indeed dropped, and the OOM issue is resolved.
*   **Performance:** However, the side effect is severe. The inference speed has slowed down by **more than 2x** compared to having the fast processor enabled.

<img width="1421" height="626" alt="Image" src="https://github.com/user-attachments/assets/1c5f3aa7-d449-4cbd-aa1d-f360741400c2" />

<img width="1434" height="653" alt="Image" src="https://github.com/user-attachments/assets/eb36be80-b71e-45cf-96da-aec314eeebd2" />



**3. Questions & Feature Request:**
I have a few follow-up questions regarding the root cause:

*   **Why are the limits ineffective?**
    I am running on the latest code from the main branch. Even with the environment variables set (e.g., `export SGLANG_VLM_MAX_IMAGES_PER_VIT=1` and `export SGLANG_VLM_MAX_PATCHES_PER_VIT=4096` or even lower) https://github.com/sgl-project/sglang/pull/14907, the `fast-image-processor` still occupies a massive amount of VRAM (~20GB overhead on Rank 0). Why do these constraints fail to limit the memory usage effectively?
*   **Can we cap memory usage without disabling the feature?**
    Is it possible to implement a hard limit on the maximum VRAM the `fast-image-processor` is allowed to use?

Disabling it completely makes the model too slow for my use case. We need a solution that prevents the unbounded memory growth on Rank 0 while retaining the performance benefits of the fast processor.
