### ISSUE TITLE
[Bug] NCCL AllGather deadlock in Qwen3 Next MTP

### ISSUE THREAD

**Issue by ispobock** [sgl-project/sglang#22276]
### Checklist

- [ ] I searched related issues but found no solution.
- [ ] The bug persists in the latest version.
- [ ] Issues without environment info and a minimal reproducible demo are hard to resolve and may receive no feedback.
- [ ] If this is not a bug report but a general question, please start a discussion at https://github.com/sgl-project/sglang/discussions. Otherwise, it will be closed.
- [ ] Please use English. Otherwise, it will be closed.

### Describe the bug

Qwen3 Next MTP (both spec v1 & v2) CI test (`test_qwen3_next_models_mtp.py`) failed. Server hangs during `test_input_output_logprobs_match_decode_cache_hit`. Specifically during second turn chunked prefill with decode cache hit.
- https://github.com/sgl-project/sglang/actions/runs/24044511585/job/70146071554 (MTPTopk)
- https://github.com/sgl-project/sglang/actions/runs/24021871164/job/70069355776 (MTPTopk)
- https://github.com/sgl-project/sglang/actions/runs/24013952407/job/70109595150 (MTPV2)

 Watchdog py-spy stack trace of TP0:                                                                                        
 ```                                                           
  cuStreamSynchronize
    _local_scalar_dense_cuda (tensor.item())                                                                                 
      update_single_wrapper (flashinfer_backend.py:1252)                                                                     
        init_forward_metadata (flashinfer_backend.py:499)                                                                    
          init_forward_metadata (hybrid_linear_attn_backend.py:737)                                                          
            forward_extend (model_runner.py:2673)                                                                            
              forward_draft_extend (eagle_worker.py:922)                                                                     
                forward_batch_generation (eagle_worker.py:301)                                                               
```                                                                                                                   
The `.item()` at `flashinfer_backend.py:1252` (`paged_kernel_lens.sum().item()`) triggers cudaStreamSynchronize, which blocks waiting for pending NCCL ops from the preceding target model forward to complete.

**Current findings:**

1. Trigger CUDA core dump manually and identify the hanging kernel is `ncclDevKernel_AllGather_RING_LL`.
2. Added `NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=COLL` to check NCCL log:
    - At hang time, ranks 0/1 stopped issuing AllGather while ranks 2/3 still issuing — target model forward enqueues different numbers of NCCL ops across ranks. 
    - The target model and draft model each have their own NCCL communicator, but they share the same CUDA stream within each TP rank process. If any NCCL op from the target model forward is still pending on the stream, this `.item()` sync will block until that op completes, which requires all TP ranks to have enqueued their matching collective. If any rank's target forward enqueued a different set of NCCL ops, all ranks deadlock at this sync point.                                                        
3. Ruled out: 
    - TP rank divergence in verify/sampling (all ranks show identical accept_length and verified_id.shape)
    - CUDA graph disabled
    - `SYNC_TOKEN_IDS_ACROSS_TP=1`

**Suspected cause:**                                                                                                                                                 
A data-dependent branch inside the hybrid model forward gates NCCL collectives differently across TP ranks during chunked prefill with cached tokens.

### Reproduction

```
python3 test/registered/4-gpu-models/test_qwen3_next_models_mtp.py
```
run 3~5x may reproduce the hanging

### Environment

H100 / H200
sglang v0.5.10

**Comment by ispobock** [comment]
Issue solved in https://github.com/sgl-project/sglang/pull/22458. Added debuging skills in https://github.com/sgl-project/sglang/pull/22463.
