### ISSUE TITLE
DeepEP Buffer initialization fails with 'invalid resource handle' on GB200

### ISSUE THREAD

**Issue by ishandhanani** [sgl-project/sglang#26196]
## Summary
DeepEP Buffer initialization crashes on GB200 GPUs during scheduler startup, causing all workers to fail to become healthy with `RuntimeError: Failed: CUDA error /build/DeepEP/csrc/deep_ep.cpp:112 'invalid resource handle'`.

## Error
```
File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/token_dispatcher/deepep.py", line 236, in get_deepep_buffer
    cls._buffer = Buffer(...)

File "/usr/local/lib/python3.12/dist-packages/deep_ep/buffer.py", line 132, in __init__
RuntimeError: Failed: CUDA error /build/DeepEP/csrc/deep_ep.cpp:112 'invalid resource handle'
```

Then escalates to:
```
RuntimeError: Failed: CUDA error /build/DeepEP/csrc/deep_ep.cpp:278 'an illegal memory access was encountered'
Fatal Python error: Aborted
```

## Repro context
- **Model**: deepseek-ai/DeepSeek-R1
- **Precision**: fp8
- **Topology**: 2 prefill nodes (tp=8, ep=8, dp=8) + 8 decode nodes (tp=32, ep=32, dp=32)
- **GPU**: NVIDIA GB200 (driver 580.95.05)
- **DeepEP Config**: `{'normal_dispatch': {'num_sms': 128, ...}}`
- **SGLang commit**: `0.0.0.dev1+gaf8f66940`
- **Key flags**: `--moe-a2a-backend deepep`, `--deepep-mode normal`, `--enable-dp-attention`, `--disaggregation-mode prefill`

## Suspect commits
- `af8f66940` — latest dev commit, `[AMD] Dsv4/pr1 fix run time issue (#25898)`

## Suggested Fix
The error originates in DeepEP's native CUDA code (`deep_ep.cpp:112`). Possible causes:
1. DeepEP library version mismatch with GB200 driver 580.95.05
2. `allow_mnnvl=True` flag being passed to Buffer init may be incompatible with GB200 resource handling
3. DeepEP may need a GB200-specific initialization path

Investigate whether `allow_mnnvl=True` in `sglang/srt/layers/moe/token_dispatcher/deepep.py:243` should be conditionally disabled for GB200, or if a newer DeepEP version fixes this issue.

**Comment by Fridge003** [comment]
@ishandhanani What's the docker image that causes this bug?

**Comment by ishandhanani** [comment]
@Fridge003 i believe https://github.com/sgl-project/sglang/actions/runs/26350615690

**Comment by ishandhanani** [comment]
Possible that this has been ongoing for a while https://github.com/sgl-project/sglang/issues/25349

**Comment by Fridge003** [comment]
@ishandhanani Will it be related to the hybrid_ep branch? The hybried_ep branch might not support nvfp4 dispatch

**Comment by ch-wan** [comment]
What's the CUDA version?

**Comment by mmangkad** [comment]
I ran into this exact issue on gb300 quite a while back. I fixed it by passing `use_fabric=True` to the deepep buffer init. Passing this flag forces it to use the cumem fabric api required for cross-node sharing.

Interestingly, I noticed the error isn't perfectly consistent. Sometimes it actually manages to work even without the code change, but applying this seems to completely resolve the underlying crash.

**Comment by trevor-m** [comment]
It looks like when we used to use the `gb200_blog_part_2` DeepEP fork it would check if fabric is supported and enable it automatically: https://github.com/fzyzcjy/DeepEP/blob/814e508537c6ffc775d59f6f1b9ba43f3a65968c/csrc/deep_ep.cpp#L52

Let's try to do the same now whether it's in sglang or we add it to deepep again.

**Comment by ishandhanani** [comment]
Job 5283 (dsr1-fp8-1k1k-max-tpt-27181662432) reproduces this issue on GB200. Additional context: model loaded successfully (mem usage 107.24 GB > avail 74.95 GB) then crashed ~3 minutes later at 03:42:54 UTC with all 8 DP ranks hitting the same DeepEP CUDA errors simultaneously. ETCD/NATS were healthy prior to crash.
