### ISSUE TITLE
about requirements

### ISSUE THREAD

**Issue by LuoKaiGSW** [sgl-project/sglang#284]
When I attempted to run the command pip install "sglang[all]", I encountered an error: "The NVIDIA driver on your system is too old (found version 11080)." Could you provide information on the dependencies for this repository? Thank you!

**Comment by hnyls2002** [comment]
@LuoKaiGSW Could you please provide more details about this error, such as the GPU, NVIDIA driver version, and which packages cause this error?

**Comment by LuoKaiGSW** [comment]
> @LuoKaiGSW Could you please provide more details about this error, such as the GPU, NVIDIA driver version, and which packages cause this error?

Thank you for your reply. I have resolved the issue. If anyone else is using CUDA 11.8, the installation process can refer to the following steps:
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118
pip install https://github.com/vllm-project/vllm/releases/download/v0.3.3/vllm-0.3.3+cu118-cp39-cp39-manylinux1_x86_64.whl
pip install outlines==0.0.34
pip install datasets
pip install "sglang[all]"
