### ISSUE TITLE
[Bug] DeepSeek R1 loading error by multi-node inference

### ISSUE THREAD

**Issue by Neo9061** [sgl-project/sglang#3254]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

I tried to use multi-node inference (2 * 8 H100) to load DeepSeek R1.

However, it kept giving me error on the header node. **Note This error happens model weights are loaded 100%.**
```
Loading safetensors checkpoint shards: 100% Completed | 163/163 [1:09:28<00:00, 26.68s/it]
 
Loading safetensors checkpoint shards: 100% Completed | 163/163 [1:09:28<00:00, 25.57s/it]
 
[2025-02-01 07:03:54 TP6] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.68 GB
[2025-02-01 07:03:54 TP5] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.68 GB
[2025-02-01 07:03:54 TP0] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.71 GB
[2025-02-01 07:03:55 TP3] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.68 GB
[2025-02-01 07:03:55 TP1] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.68 GB
[2025-02-01 07:03:55 TP7] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.68 GB
[2025-02-01 07:03:55 TP4] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.68 GB
[2025-02-01 07:03:55 TP2] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.68 GB
[2025-02-01 07:03:55 TP3] Memory pool end. avail mem=15.10 GB
[2025-02-01 07:03:55 TP4] Memory pool end. avail mem=15.10 GB
[2025-02-01 07:03:55 TP7] Memory pool end. avail mem=15.11 GB
[2025-02-01 07:03:55 TP5] Memory pool end. avail mem=15.10 GB
[2025-02-01 07:03:55 TP6] Memory pool end. avail mem=15.10 GB
[2025-02-01 07:03:55 TP1] Memory pool end. avail mem=15.10 GB
[2025-02-01 07:03:55 TP0] Memory pool end. avail mem=15.14 GB
[2025-02-01 07:03:55 TP2] Memory pool end. avail mem=15.10 GB
[2025-02-01 07:03:55 TP6] The following error message 'operation scheduled before its operands' can be ignored.
[2025-02-01 07:03:55 TP4] The following error message 'operation scheduled before its operands' can be ignored.
[2025-02-01 07:03:55 TP5] The following error message 'operation scheduled before its operands' can be ignored.
[2025-02-01 07:03:55 TP3] The following error message 'operation scheduled before its operands' can be ignored.
[2025-02-01 07:03:55 TP0] The following error message 'operation scheduled before its operands' can be ignored.
[2025-02-01 07:03:55 TP7] The following error message 'operation scheduled before its operands' can be ignored.
[2025-02-01 07:03:55 TP1] The following error message 'operation scheduled before its operands' can be ignored.
[2025-02-01 07:03:55 TP2] The following error message 'operation scheduled before its operands' can be ignored.
[2025-02-01 07:03:55 TP5] Capture cuda graph begin. This can take up to several minutes.
[2025-02-01 07:03:55 TP6] Capture cuda graph begin. This can take up to several minutes.
[2025-02-01 07:03:55 TP7] Capture cuda graph begin. This can take up to several minutes.
[2025-02-01 07:03:55 TP4] Capture cuda graph begin. This can take up to several minutes.
[2025-02-01 07:03:55 TP3] Capture cuda graph begin. This can take up to several minutes.
[2025-02-01 07:03:55 TP0] Capture cuda graph begin. This can take up to several minutes.
 
  0%|          | 0/23 [00:00<?, ?it/s][2025-02-01 07:03:55 TP1] Capture cuda graph begin. This can take up to several minutes.
[2025-02-01 07:03:55 TP2] Capture cuda graph begin. This can take up to several minutes.
 
  0%|          | 0/23 [00:00<?, ?it/s]
[2025-02-01 07:03:55 TP6] Scheduler hit an exception: Traceback (most recent call last):
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 226, in __init__
    self.capture()
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 292, in capture
    ) = self.capture_one_batch_size(bs, forward)
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 368, in capture_one_batch_size
    self.model_runner.tp_group.barrier()
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/distributed/parallel_state.py", line 812, in barrier
    torch.distributed.barrier(group=self.cpu_group)
  File "/opt/conda/envs/xin/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/xin/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4164, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [172.31.18.145]:45492
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/managers/scheduler.py", line 1787, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/managers/scheduler.py", line 240, in __init__
    self.tp_worker = TpWorkerClass(
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/managers/tp_worker.py", line 68, in __init__
    self.model_runner = ModelRunner(
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/model_executor/model_runner.py", line 214, in __init__
    self.init_cuda_graphs()
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/model_executor/model_runner.py", line 730, in init_cuda_graphs
    self.cuda_graph_runner = CudaGraphRunner(self)
  File "/iofsx/sds3/scripts/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 228, in __init__
    raise Exception(
Exception: Capture cuda graph failed: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [172.31.18.145]:45492
Possible solutions:
1. disable cuda graph by --disable-cuda-graph
2. set --mem-fraction-static to a smaller value (e.g., 0.8 or 0.7)
3. disable torch compile by not using --enable-torch-compile
Open an issue on GitHub https://github.com/sgl-project/sglang/issues/new/choose 
```

The error on the worker node is following.

```
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7ea82996c446 in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x282 (0x7ea78d3cc772 in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7ea78d3d3bb3 in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7ea78d3d561d in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x145c0 (0x7ea87843e5c0 in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x94ac3 (0x7ea882494ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x7ea882526850 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 15] Process group watchdog thread terminated with exception: [Rank 15] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600013 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7ea82996c446 in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x282 (0x7ea78d3cc772 in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7ea78d3d3bb3 in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7ea78d3d561d in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x145c0 (0x7ea87843e5c0 in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x94ac3 (0x7ea882494ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x7ea882526850 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7ea82996c446 in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe4271b (0x7ea78d04271b in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x145c0 (0x7ea87843e5c0 in /opt/conda/envs/sglang/lib/python3.10/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x94ac3 (0x7ea882494ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x7ea882526850 in /lib/x86_64-linux-gnu/libc.so.6)
```

### Reproduction

I created a conda virtual env with python 3.10.

Then I followed the method 2 in [here](https://docs.sglang.ai/start/install.html#method-2-from-source) to install sgland.

The invoking command on header and worker node is following.

```
python -m sglang.launch_server \
--model-path /iofsx/sds3/models/DeepSeekV3/DeepSeek-R1 \
--tp 16 \
--dist-init-addr <HEADER_IP>:5000 \
--nnodes 2 \
--node-rank 0 \
--trust-remote-code \
--disable-radix-cache \
--port 8000 \
--host 0.0.0.0 2>&1 | tee RUN_1.log
```

```
python -m sglang.launch_server \
--model-path /iofsx/sds3/models/DeepSeekV3/DeepSeek-R1 \
--tp 16 \
--dist-init-addr <HEADER_IP>:5000 \
--nnodes 2 \
--node-rank 1 \
--trust-remote-code \
--disable-radix-cache \
--port 8000 \
--host 0.0.0.0 2>&1 | tee RUN_2.log
```

### Environment

I created a conda virtual env with python 3.10.

Then I followed the method 2 in [here](https://docs.sglang.ai/start/install.html#method-2-from-source) to install sgland.
```
# Use the last release branch
git clone -b v0.4.2.post1 https://github.com/sgl-project/sglang.git
cd sglang

pip install --upgrade pip
pip install sgl-kernel --force-reinstall --no-deps
pip install -e "python[all]" --find-links https://flashinfer.ai/whl/cu124/torch2.4/flashinfer/
```

Pytorch version is `torch.__version__'2.5.1+cu124'`

**Comment by Neo9061** [comment]
CC @fsygd and @zhyncs if you have any insights as I saw you gave comments in similar threads. Thank you very much!

**Comment by Neo9061** [comment]
Some updates: I have pulled both the latest docker or the `v0.4.1.post6-cu124` and use those dockers run with following command on header node.

```
docker run --gpus all \
    --shm-size 32g \
    --network=host \
    -v /iofsx/sds3/models:/root \
    --name sglang_multinode1 \
    -it \
    --rm \
    --ipc=host \
    lmsysorg/sglang:v0.4.1.post6-cu124 \
    python3 -m sglang.launch_server \
    --model-path /root/DeepSeekV3/DeepSeek-V3 \
    --tp 16 \
    --dist-init-addr ec2-54-191-57-231.us-west-2.compute.amazonaws.com:20000 \
    --nnodes 2 \
    --node-rank 0 \
    --trust-remote-code \
    --disable-radix-cache \
    --port 8085 \
    --host 0.0.0.0 2>&1 | tee v0.4.1.post6_RUN_1.log 
```
And similar command on worker node with `node-rank` to be `1.`

However, the error mostly comes from worker node with WatchDog time out.

```
Cache shape torch.Size([163840, 64])
Cache shape torch.Size([163840, 64])
[2025-02-01 22:46:19 TP15] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.71 GB
[2025-02-01 22:46:19 TP10] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.70 GB
[2025-02-01 22:46:19 TP14] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.70 GB
[2025-02-01 22:46:19 TP8] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.74 GB
[2025-02-01 22:46:19 TP11] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.70 GB
[2025-02-01 22:46:19 TP9] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.70 GB
[2025-02-01 22:46:19 TP12] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.70 GB
[2025-02-01 22:46:19 TP13] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=37.70 GB
[rank9]:[E201 22:56:19.820028643 ProcessGroupNCCL.cpp:616] [Rank 9] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600021 milliseconds before timing out.
[rank9]:[E201 22:56:19.820549823 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 9] Exception (either an error or timeout) detected by watchdog at work: 2, last enqueued NCCL work: 2, last completed NCCL work: 1.
[rank9]:[E201 22:56:19.820570243 ProcessGroupNCCL.cpp:1834] [PG ID 0 PG GUID 0(default_pg) Rank 9] Timeout at NCCL work: 2, last enqueued NCCL work: 2, last completed NCCL work: 1.
[rank9]:[E201 22:56:19.820580383 ProcessGroupNCCL.cpp:630] [Rank 9] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank9]:[E201 22:56:19.820587623 ProcessGroupNCCL.cpp:636] [Rank 9] To avoid data inconsistency, we are taking the entire process down.
[rank9]:[E201 22:56:19.821570452 ProcessGroupNCCL.cpp:1595] [PG ID 0 PG GUID 0(default_pg) Rank 9] Process group watchdog thread terminated with exception: [Rank 9] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600021 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x77a82eda4446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x282 (0x77a8300b7772 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x77a8300bebb3 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x77a8300c061d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x145c0 (0x77a878a415c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x8609 (0x77a87b285609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x77a87b3bf353 in /usr/lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 9] Process group watchdog thread terminated with exception: [Rank 9] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600021 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x77a82eda4446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x282 (0x77a8300b7772 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x77a8300bebb3 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x77a8300c061d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x145c0 (0x77a878a415c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x8609 (0x77a87b285609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x77a87b3bf353 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x77a82eda4446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe4271b (0x77a82fd2d71b in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x145c0 (0x77a878a415c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x8609 (0x77a87b285609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #4: clone + 0x43 (0x77a87b3bf353 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Fatal Python error: Aborted

```

**Comment by zhyncs** [comment]
@antferdom may you help take a look

**Comment by Neo9061** [comment]
The issue is solved. Root cause being the outbound rule needs to be set properly. Thanks a lot!

**Comment by zhaochenyang20** [comment]
@Neo9061 So what's the solution? Could you share it?

**Comment by dochenms** [comment]
@Neo9061  Can you share your solution to avoid the watchdog timeout issue?

**Comment by lll2343** [comment]
@Neo9061 How do you solve this issue, please🙏🙏

**Comment by Neo9061** [comment]
@zhaochenyang20 @dochenms @lll2343 It is specifically related to my cluster. I used EC2 and I realized that I need set the outbound rule to be communicable between those nodes.

**Comment by lll2343** [comment]
use port 5000 may help...

**Comment by zhyncs** [comment]
https://github.com/sgl-project/sglang/tree/main/benchmark/deepseek_v3#example-serving-with-two-h208-nodes

> If the command fails, try setting the GLOO_SOCKET_IFNAME parameter. For more information, see [Common Environment Variables](https://pytorch.org/docs/stable/distributed.html#common-environment-variables).
