### ISSUE TITLE
[Bug] Watchdog caught collective operation timeout:

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [sgl-project/sglang#3368]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

Run DeepSeek-R1 on 2 8* A800s, 
This error occurs after loading the model:  Watchdog caught collective operation timeout:
10.25.117.26
```shell
[2025-02-07 02:59:26 TP13] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
[2025-02-07 02:59:26 TP11] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
[2025-02-07 02:59:26 TP15] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
[2025-02-07 02:59:26 TP8] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
[2025-02-07 02:59:26 TP10] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
[2025-02-07 02:59:26 TP12] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
[2025-02-07 02:59:26 TP14] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
[2025-02-07 02:59:26 TP9] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
Cache shape torch.Size([163840, 64])
Cache shape torch.Size([163840, 64])
Cache shape torch.Size([163840, 64])
Cache shape torch.Size([163840, 64])
Cache shape torch.Size([163840, 64])
Cache shape torch.Size([163840, 64])
Cache shape torch.Size([163840, 64])
Cache shape torch.Size([163840, 64])

```

10.25.117.28
```
Loading safetensors checkpoint shards:  99% Completed | 161/163 [01:15<00:00,  2.24it/s]
Loading safetensors checkpoint shards:  99% Completed | 162/163 [01:15<00:00,  2.62it/s]
Loading safetensors checkpoint shards: 100% Completed | 163/163 [01:15<00:00,  2.44it/s]
Loading safetensors checkpoint shards: 100% Completed | 163/163 [01:15<00:00,  2.15it/s]

[2025-02-07 01:19:40 TP0] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=38.13 GB
[2025-02-07 01:19:42 TP3] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=38.11 GB
[2025-02-07 01:19:47 TP7] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=38.13 GB
[2025-02-07 01:19:47 TP5] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=38.11 GB
[2025-02-07 01:19:47 TP1] Load weight end. type=DeepseekV3ForCausalLM, dtype=torch.bfloat16, avail mem=38.11 GB


[rank6]:[E207 01:29:36.730311765 ProcessGroupNCCL.cpp:616] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, Nume
lOut=1, Timeout(ms)=600000) ran for 600050 milliseconds before timing out.
[rank6]:[E207 01:29:36.730815661 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 6] Exception (either an error or timeout) detected by watchdog at work
: 2, last enqueued NCCL work: 2, last completed NCCL work: 1.
[rank6]:[E207 01:29:36.730845309 ProcessGroupNCCL.cpp:1834] [PG ID 0 PG GUID 0(default_pg) Rank 6] Timeout at NCCL work: 2, last enqueued NCCL work: 2, last completed
 NCCL work: 1.
[rank6]:[E207 01:29:36.730861671 ProcessGroupNCCL.cpp:630] [Rank 6] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank6]:[E207 01:29:36.730893283 ProcessGroupNCCL.cpp:636] [Rank 6] To avoid data inconsistency, we are taking the entire process down.
[rank6]:[E207 01:29:36.732277782 ProcessGroupNCCL.cpp:1595] [PG ID 0 PG GUID 0(default_pg) Rank 6] Process group watchdog thread terminated with exception: [Rank 6] W
atchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600050 milliseconds before timing
 out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fa178140446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x282 (0x7fa179453772 in /usr/local/li
b/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7fa17945abb3 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7fa17945c61d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x145c0 (0x7fa1c4f985c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x8609 (0x7fa1c5d23609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7fa1c5e5d353 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 6] Process group watchdog thread terminated with exception: [Rank 6] Watchdog caught collective operation timeout: Work
NCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600050 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fa178140446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x282 (0x7fa179453772 in /usr/local/li
b/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
```

### Reproduction

IP: 10.25.117.28
```shell
docker pull lmsysorg/sglang:latest

mount -o remount,size=32G /dev/shm

export NCCL_SOCKET_IFNAME=bond0.137
export GLOO_SOCKET_IFNAME=bond0.137

docker run --gpus all   --shm-size 32g  --network=host -v /home/app/sharedir_online/nlp/ark_server:/models  --name sglang_multinode0 -it --ipc=host  lmsysorg/sglang:latest
   
python3 -m sglang.launch_server --model-path /models/DeepSeek-R1 --tp 16 --dist-init-addr 10.25.117.28:5000 --nnodes 2 --node-rank 0 --trust-remote-code
```

IP: 10.25.117.26
```shell
docker pull lmsysorg/sglang:latest

mount -o remount,size=32G /dev/shm

export NCCL_SOCKET_IFNAME=bond0.137
export GLOO_SOCKET_IFNAME=bond0.137

docker run --gpus all   --shm-size 32g  --network=host -v /home/app/sharedir_online/nlp/ark_server:/models  --name sglang_multinode1  -it --ipc=host  lmsysorg/sglang:latest
   
python3 -m sglang.launch_server --model-path /models/DeepSeek-R1 --tp 16 --dist-init-addr 10.25.117.28:5000 --nnodes 2 --node-rank 1 --trust-remote-code
```

I wonder if I made a mistake?

### Environment

```shell
bond0.137: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9000
        inet 10.25.117.28  netmask 255.255.255.0  broadcast 10.25.117.255
        inet6 fe80::9ec2:c4ff:fe21:8392  prefixlen 64  scopeid 0x20<link>
        ether 9c:c2:c4:21:83:92  txqueuelen 1000  (Ethernet)
        RX packets 33681202189  bytes 227770829472403 (207.1 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 171313511956  bytes 235085261869275 (213.8 TiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```shell
Python: 3.10.16 (main, Dec  4 2024, 08:53:37) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA A800-SXM4-80GB
GPU 0,1,2,3,4,5,6,7 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.5, V12.5.82
CUDA Driver Version: 535.104.05
PyTorch: 2.5.1+cu124
flashinfer: 0.2.0.post2+cu124torch2.5
triton: 3.1.0
transformers: 4.48.2
torchao: 0.8.0
numpy: 1.26.4
aiohttp: 3.11.11
fastapi: 0.115.8
hf_transfer: 0.1.9
huggingface_hub: 0.28.1
interegular: 0.3.3
modelscope: 1.22.3
orjson: 3.10.15
packaging: 24.2
psutil: 6.1.1
pydantic: 2.10.6
multipart: 0.0.20
zmq: 26.2.1
uvicorn: 0.34.0
uvloop: 0.21.0
vllm: 0.6.4.post1
openai: 1.61.0
anthropic: 0.45.2
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV8     NV8     NV8     NV8     NV8     NV8     NV8     PXB     NODE    SYS     SYS     0-31    0               N/A
GPU1    NV8      X      NV8     NV8     NV8     NV8     NV8     NV8     PXB     NODE    SYS     SYS     0-31    0               N/A
GPU2    NV8     NV8      X      NV8     NV8     NV8     NV8     NV8     NODE    PXB     SYS     SYS     0-31    0               N/A
GPU3    NV8     NV8     NV8      X      NV8     NV8     NV8     NV8     NODE    PXB     SYS     SYS     0-31    0               N/A
GPU4    NV8     NV8     NV8     NV8      X      NV8     NV8     NV8     SYS     SYS     PXB     NODE    32-63   1               N/A
GPU5    NV8     NV8     NV8     NV8     NV8      X      NV8     NV8     SYS     SYS     PXB     NODE    32-63   1               N/A
GPU6    NV8     NV8     NV8     NV8     NV8     NV8      X      NV8     SYS     SYS     NODE    PXB     32-63   1               N/A
GPU7    NV8     NV8     NV8     NV8     NV8     NV8     NV8      X      SYS     SYS     NODE    PXB     32-63   1               N/A
NIC0    PXB     PXB     NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    SYS     SYS
NIC1    NODE    NODE    PXB     PXB     SYS     SYS     SYS     SYS     NODE     X      SYS     SYS
NIC2    SYS     SYS     SYS     SYS     PXB     PXB     NODE    NODE    SYS     SYS      X      NODE
NIC3    SYS     SYS     SYS     SYS     NODE    NODE    PXB     PXB     SYS     SYS     NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3


ulimit soft: 1048576
```

**Comment by shuaills** [comment]
cc @zhyncs

**Comment by CallmeZhangChenchen** [comment]
@shuaills @zhyncs  
I don't know how to operate it, and the model was successfully loaded, 
but now I reported another error. *AssertionError: fp8e4nv data type is not supported on CUDA arch < 89*,
I  operate on two A800, and do not support FP8 calculation, so is there any way to make it run

**Comment by burling** [comment]
Is there any new progress on this current issue? We have encountered a large number of such problems in the production environment.

**Comment by Orangels** [comment]
> [@shuaills](https://github.com/shuaills) [@zhyncs](https://github.com/zhyncs) I don't know how to operate it, and the model was successfully loaded, but now I reported another error. _AssertionError: fp8e4nv data type is not supported on CUDA arch < 89_, I operate on two A800, and do not support FP8 calculation, so is there any way to make it run

Hi, I'm also encountering the error 'Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600050 milliseconds before timing out'. Could you please tell me how you successfully loaded the model.

**Comment by CallmeZhangChenchen** [comment]
@burling @Orangels 英语不太好，直接中文了哈  Chinese 
1. 我不知道为什么模型就加载成功了，
感觉上哈，可能不对，你们多启动几次服务就好了，因为模型太大，多机器加载速度不一样，就产生了这个超时问题
2. A800跑不了FP8的问题，可以找下有人开源了一个AWQ的模型可以试下
3. 祝成功

**Comment by aooxin** [comment]
> [@burling](https://github.com/burling) [@Orangels](https://github.com/Orangels) 英语不太好，直接中文了哈 Chinese
> 
> 1. 我不知道为什么模型就加载成功了，
>    感觉上哈，可能不对，你们多启动几次服务就好了，因为模型太大，多机器加载速度不一样，就产生了这个超时问题
> 2. A800跑不了FP8的问题，可以找下有人开源了一个AWQ的模型可以试下
> 3. 祝成功

是的是的，我感觉第一条就是这个原因，但是没找到是不是这个 time 可以被环境变量控制

**Comment by teadross** [comment]
i find the same bug. all ENVs cannot fix this. 
this is caused by `/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/distributed/c10d/ProcessGroupNCCL.hpp` in line 132, which set `kProcessGroupNCCLDefaultTimeout` to `10 * 60 * 1000`.
however, in my cluster, when reading the safetensor files, one node need 12 min and another need 20 min, which exceed the kProcessGroupNCCLDefaultTimeout time, while set `TORCH_NCCL_ENABLE_MONITORING` or `TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC` is useless.
so please fix this bug, or just shutdown the watchdog.

**Comment by teadross** [comment]
cc @zhyncs  begging for fix this

**Comment by teadross** [comment]
cc @zhyncs begging for fixing this
