### ISSUE TITLE
deepseek-v3 cannot run multi-node under H20

### ISSUE THREAD

**Issue by joerong888** [sgl-project/sglang#3398]
hi there,

I have followed the doc in https://github.com/sgl-project/sglang/tree/main/benchmark/deepseek_v3, 
however the server was still stuck when setting up. 

**First node:**
ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 11.130.1.53  netmask 255.255.248.0  broadcast 11.130.7.255

**Below is the command:**
export NCCL_SOCKET_IFNAME=eth0
export GLOO_SOCKET_IFNAME=eth0
export NCCL_DEBUG=TRACE

python3 -m sglang.launch_server --model-path /code/llm-benchmark-script/data/raw/DeepSeek-V3 --tp 16 --dist-init-addr 11.130.1.53:5000 --nnodes 2 --node-rank 0 --trust-remote-code --host 0.0.0.0 --port 6178

===========================

**Second node:**
ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 33.18.27.52  netmask 255.255.248.0  broadcast 33.18.31.255

**Below is the command:**
export NCCL_SOCKET_IFNAME=eth0
export GLOO_SOCKET_IFNAME=eth0
export NCCL_DEBUG=TRACE

python3 -m sglang.launch_server --model-path /code/llm-benchmark-script/data/raw/DeepSeek-V3 --tp 16 --dist-init-addr 11.130.1.53:5000 --nnodes 2 --node-rank 1 --trust-remote-code --host 0.0.0.0 --port 6178

**Detail logs:**
**First node logs:**

[2025-02-08 00:24:47] server_args=ServerArgs(model_path='/code/llm-benchmark-script/data/raw/DeepSeek-V3', tokenizer_path='/code/llm-benchmark-script/data/raw/DeepSeek-V3', tokenizer_mode='auto', load_format='auto', trust_remote_code=True, dtype='auto', kv_cache_dtype='auto', quantization_param_path=Non
e, quantization=None, context_length=None, device='cuda', served_model_name='/code/llm-benchmark-script/data/raw/DeepSeek-V3', chat_template=None, is_embedding=False, revision=None, skip_tokenizer_init=False, host='0.0.0.0', port=6178, mem_fraction_static=0.79, max_running_requests=None, max_total_token
s=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, cpu_offload_gb=0, prefill_only_one_req=False, tp_size=16, stream_interval=1, stream_output=False, random_seed=28357384, constrained_json_whitespace_pattern=None, watchdog_timeout=300, downl
oad_dir=None, base_gpu_id=0, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, enable_metrics=False, decode_log_interval=40, api_key=None, file_storage_pth='sglang_storage', enable_cache_report=False, dp_size=1, load_balance_method='round_robin', ep_size=1, dist_init_addr=
'11.130.1.53:5000', nnodes=2, node_rank=0, json_model_override_args='{}', lora_paths=None, max_loras_per_batch=8, lora_backend='triton', attention_backend='flashinfer', sampling_backend='flashinfer', grammar_backend='outlines', speculative_draft_model_path=None, speculative_algorithm=None, speculative_n
um_steps=5, speculative_num_draft_tokens=64, speculative_eagle_topk=8, enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, disable_radix_cache=False, disable_jump_forward=False, disable_c
uda_graph=True, disable_cuda_graph_padding=False, disable_outlines_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, disable_overlap_schedule=False, enable_mixed_chunk=False, enable_dp_attention=False, enable_ep_moe=False, enable_torch_compile=False, torch_compile_max_bs=32, cuda_gra
ph_max_bs=160, cuda_graph_bs=None, torchao_config='', enable_nan_detection=False, enable_p2p_check=False, triton_attention_reduce_in_fp32=False, triton_attention_num_kv_splits=8, num_continuous_decode_steps=1, delete_ckpt_after_loading=False, enable_memory_saver=False, allow_auto_truncate=False, enable_
custom_logit_processor=False, tool_call_parser=None, enable_hierarchical_cache=False)
[2025-02-08 00:25:02 TP3] MLA optimization is turned on. Use triton backend.
[2025-02-08 00:25:02 TP3] Init torch distributed begin.
[2025-02-08 00:25:05 TP6] MLA optimization is turned on. Use triton backend.
[2025-02-08 00:25:05 TP6] Init torch distributed begin.
[2025-02-08 00:25:05 TP1] MLA optimization is turned on. Use triton backend.
[2025-02-08 00:25:05 TP1] Init torch distributed begin.
[2025-02-08 00:25:05 TP7] MLA optimization is turned on. Use triton backend.
[2025-02-08 00:25:05 TP7] Init torch distributed begin.
[2025-02-08 00:25:05 TP5] MLA optimization is turned on. Use triton backend.
[2025-02-08 00:25:05 TP5] Init torch distributed begin.
[2025-02-08 00:25:05 TP0] MLA optimization is turned on. Use triton backend.
[2025-02-08 00:25:05 TP0] Init torch distributed begin.
[2025-02-08 00:25:05 TP4] MLA optimization is turned on. Use triton backend.
[2025-02-08 00:25:05 TP4] Init torch distributed begin.
[2025-02-08 00:25:05 TP2] MLA optimization is turned on. Use triton backend.
[2025-02-08 00:25:05 TP2] Init torch distributed begin.
[2025-02-08 00:25:21 TP0] sglang is using nccl==2.21.5
[2025-02-08 00:25:21 TP1] sglang is using nccl==2.21.5
[2025-02-08 00:25:21 TP2] sglang is using nccl==2.21.5
[2025-02-08 00:25:21 TP3] sglang is using nccl==2.21.5
[2025-02-08 00:25:21 TP4] sglang is using nccl==2.21.5
[2025-02-08 00:25:21 TP5] sglang is using nccl==2.21.5
[2025-02-08 00:25:21 TP6] sglang is using nccl==2.21.5
[2025-02-08 00:25:21 TP7] sglang is using nccl==2.21.5
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75204:75204 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75204:75204 [0] NCCL INFO Bootstrap : Using eth0:11.130.1.53<0>
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75204:75204 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75204:75204 [0] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75204:75204 [0] NCCL INFO NET/Plugin: Using internal network plugin.
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75204:75204 [0] NCCL INFO cudaDriverVersion 12040
NCCL version 2.21.5+cuda12.4
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO cudaDriverVersion 12040
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO Bootstrap : Using eth0:11.130.1.53<0>
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO NET/Plugin: Using internal network plugin.
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO NET/IB : No device found.
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO NET/Socket : Using [0]eth0:11.130.1.53<0>
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO Using non-device net plugin version 0
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO Using network Socket
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO ncclCommInitRank comm 0xb9c26e0 rank 1 nranks 16 cudaDev 1 nvmlDev 1 busId 7e000 commId 0x898b6d578585998c - Init START
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO MNNVL busId 0x7e000 fabric UUID 0.0 cliqueId 0x0 state 3 healthMask 0x0
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO Setting affinity for GPU 1 to 1fff,00000000,0000ffff,ffffffff
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO NCCL_NVLS_ENABLE set by environment to 0.
。。。
。。。
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO NET/Socket : Using [0]eth0:11.130.1.53<0>
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO Using non-device net plugin version 0
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO Using network Socket
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO ncclCommInitRank comm 0xb9b7660 rank 4 nranks 16 cudaDev 4 nvmlDev 4 busId 109000 commId 0x898b6d578585998c - Init START
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO MNNVL busId 0x109000 fabric UUID 0.0 cliqueId 0x0 state 3 healthMask 0x0
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO NCCL_NVLS_ENABLE set by environment to 0.
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO comm 0xb9b7660 rank 4 nRanks 16 nNodes 2 localRanks 8 localRank 4 MNNVL 0
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO Trees [0] 5/-1/-1->4->3 [1] 5/-1/-1->4->3
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO P2P Chunksize set to 131072
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO Channel 00/0 : 4[4] -> 3[3] via P2P/IPC
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO Channel 01/0 : 4[4] -> 3[3] via P2P/IPC
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO Connected all rings
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO Channel 00/0 : 4[4] -> 5[5] via P2P/IPC
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO Channel 01/0 : 4[4] -> 5[5] via P2P/IPC
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO Connected all trees
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO threadThresholds 8/8/64 | 128/8/64 | 512 | 512
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 1 p2p channels per peer
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO TUNER/Plugin: Plugin load returned 11 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-tuner.so
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75208:75208 [4] NCCL INFO ncclCommInitRank comm 0xb9b7660 rank 4 nranks 16 cudaDev 4 nvmlDev 4 busId 109000 commId 0x898b6d578585998c - Init COMPLETE
 comm 0xafd57d0 rank 3 nranks 16 cudaDev 3 nvmlDev 3 busId c6000 commId 0x898b6d578585998c - Init COMPLETE
[rank4]:[W208 00:55:32.441635613 socket.cpp:462] [c10d] waitForInput: poll for socket SocketImpl(fd=103, addr=[::ffff:11.130.1.53]:52372, remote=[::ffff:11.130.1.53]:5000) returned 0, likely a timeout
[rank3]:[W208 00:55:32.441638000 socket.cpp:462] [c10d] waitForInput: poll for socket SocketImpl(fd=103, addr=[::ffff:11.130.1.53]:52362, remote=[::ffff:11.130.1.53]:5000) returned 0, likely a timeout
or directory : when loading libnccl-tuner.so
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
llm-bm-infer-service-prod-1738980864555tkay-4005863815:75205:75205 [1] NCCL INFO ncclCommInitRank comm 0xb9c26e0 rank 1 nranks 16 cudaDev 1 nvmlDev 1 busId 7e000 commId 0x898b6d578585998c - Init COMPLETE
[rank1]:[W208 00:55:32.441637683 socket.cpp:462] [c10d] waitForInput: poll for socket SocketImpl(fd=103, addr=[::ffff:11.130.1.53]:52374, remote=[::ffff:11.130.1.53]:5000) returned 0, likely a timeout
[rank6]:[W208 00:55:32.443873015 socket.cpp:487] [c10d] waitForInput: socket SocketImpl(fd=103, addr=[::ffff:11.130.1.53]:52370, remote=[::ffff:11.130.1.53]:5000) timed out after 1800000ms
[rank1]:[W208 00:55:32.444259976 socket.cpp:487] [c10d] waitForInput: socket SocketImpl(fd=103, addr=[::ffff:11.130.1.53]:52374, remote=[::ffff:11.130.1.53]:5000) timed out after 1800000ms
[rank3]:[W208 00:55:32.444220068 socket.cpp:487] [c10d] waitForInput: socket SocketImpl(fd=103, addr=[::ffff:11.130.1.53]:52362, remote=[::ffff:11.130.1.53]:5000) timed out after 1800000ms
[rank4]:[W208 00:55:32.444221339 socket.cpp:487] [c10d] waitForInput: socket SocketImpl(fd=103, addr=[::ffff:11.130.1.53]:52372, remote=[::ffff:11.130.1.53]:5000) timed out after 1800000ms
[2025-02-08 00:55:32 TP5] Scheduler hit an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/scheduler.py", line 1787, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/scheduler.py", line 240, in __init__
    self.tp_worker = TpWorkerClass(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/tp_worker.py", line 68, in __init__
    self.model_runner = ModelRunner(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_executor/model_runner.py", line 178, in __init__
    min_per_gpu_memory = self.init_torch_distributed()
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_executor/model_runner.py", line 254, in init_torch_distributed
    initialize_dp_attention(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/layers/dp_attention.py", line 33, in initialize_dp_attention
    _ATTN_TP_GROUP = GroupCoordinator(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/distributed/parallel_state.py", line 202, in __init__
    cpu_group = torch.distributed.new_group(ranks, backend="gloo")
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 97, in wrapper
    func_return = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 4565, in new_group
    return _new_group_with_tag(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 4648, in _new_group_with_tag
    pg, pg_store = _new_process_group_helper(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1744, in _new_process_group_helper

。。。
。。。
[2025-02-08 00:55:32] Received sigquit from a child proces. It usually means the child failed.
[2025-02-08 00:55:32 TP4] Scheduler hit an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/scheduler.py", line 1787, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/scheduler.py", line 240, in __init__
    self.tp_worker = TpWorkerClass(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/tp_worker.py", line 68, in __init__
    self.model_runner = ModelRunner(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_executor/model_runner.py", line 178, in __init__
    min_per_gpu_memory = self.init_torch_distributed()
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_executor/model_runner.py", line 254, in init_torch_distributed
    initialize_dp_attention(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/layers/dp_attention.py", line 33, in initialize_dp_attention
    _ATTN_TP_GROUP = GroupCoordinator(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/distributed/parallel_state.py", line 202, in __init__
    cpu_group = torch.distributed.new_group(ranks, backend="gloo")
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 97, in wrapper
    func_return = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 4565, in new_group
    return _new_group_with_tag(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 4648, in _new_group_with_tag
    pg, pg_store = _new_process_group_helper(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1744, in _new_process_group_helper
    backend_class = ProcessGroupGloo(
torch.distributed.DistStoreError: wait timeout after 1800000ms, keys: /default_pg/0//38//cpu//0/0

**Second node logs:**
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO NET/Socket : Using [0]eth0:33.18.27.52<0>
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO Using non-device net plugin version 0
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO Using network Socket
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO ncclCommInitRank comm 0xafd6da0 rank 10 nranks 16 cudaDev 2 nvmlDev 2 busId a2000 commId 0x898b6d578585998c - Init START
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO MNNVL busId 0xa2000 fabric UUID 0.0 cliqueId 0x0 state 3 healthMask 0x0
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO Setting affinity for GPU 2 to 1fff,00000000,0000ffff,ffffffff
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO NCCL_NVLS_ENABLE set by environment to 0.
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO comm 0xafd6da0 rank 10 nRanks 16 nNodes 2 localRanks 8 localRank 2 MNNVL 0
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO Trees [0] 11/-1/-1->10->9 [1] 11/-1/-1->10->9
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO P2P Chunksize set to 131072
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO Channel 00/0 : 10[2] -> 9[1] via P2P/IPC
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO Channel 01/0 : 10[2] -> 9[1] via P2P/IPC
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO Connected all rings
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO Channel 00/0 : 10[2] -> 11[3] via P2P/IPC
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO Channel 01/0 : 10[2] -> 11[3] via P2P/IPC
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO Connected all trees
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO threadThresholds 8/8/64 | 128/8/64 | 512 | 512
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 1 p2p channels per peer
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO TUNER/Plugin: Plugin load returned 11 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-tuner.so
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88008:88008 [2] NCCL INFO ncclllm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO cudaDriverVersion 12040
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Bootstrap : Using eth0:33.18.27.52<0>
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO NET/Plugin: Using internal network plugin.
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO NET/IB : No device found.
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO NET/Socket : Using [0]eth0:33.18.27.52<0>
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Using non-device net plugin version 0
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Using network Socket
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO ncclCommInitRank comm 0xc560d30 rank 11 nranks 16 cudaDev 3 nvmlDev 3 busId c6000 commId 0x898b6d578585998c - Init START
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO MNNVL busId 0xc6000 fabric UUID 0.0 cliqueId 0x0 state 3 healthMask 0x0
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Setting affinity for GPU 3 to 1fff,00000000,0000ffff,ffffffff
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO NCCL_NVLS_ENABLE set by environment to 0.
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO comm 0xc560d30 rank 11 nRanks 16 nNodes 2 localRanks 8 localRank 3 MNNVL 0
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Trees [0] 12/-1/-1->11->10 [1] 12/-1/-1->11->10
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO P2P Chunksize set to 131072
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Channel 00/0 : 11[3] -> 10[2] via P2P/IPC
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Channel 01/0 : 11[3] -> 10[2] via P2P/IPC
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Connected all rings
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Channel 00/0 : 11[3] -> 12[4] via P2P/IPC
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Channel 01/0 : 11[3] -> 12[4] via P2P/IPC
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO Connected all trees
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO threadThresholds 8/8/64 | 128/8/64 | 512 | 512
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 1 p2p channels per peer
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO TUNER/Plugin: Plugin load returned 11 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-tuner.so
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
llm-bm-infer-service-prod-17389809006090t9a-1100014361:88009:88009 [3] NCCL INFO [2025-02-08 00:25:32 TP15] Custom allreduce is disabled because this process group spans across nodes.
[2025-02-08 00:25:32 TP13] Custom allreduce is disabled because this process group spans across nodes.
[2025-02-08 00:25:32 TP12] Custom allreduce is disabled because this process group spans across nodes.
[2025-02-08 00:25:32 TP14] Custom allreduce is disabled because this process group spans across nodes.
[2025-02-08 00:25:32 TP11] Custom allreduce is disabled because this process group spans across nodes.
[2025-02-08 00:25:32 TP9] Custom allreduce is disabled because this process group spans across nodes.
[2025-02-08 00:25:32 TP10] Custom allreduce is disabled because this process group spans across nodes.
[2025-02-08 00:25:32 TP8] Custom allreduce is disabled because this process group spans across nodes.

**Note**
That is to say the first node is killed after 1800s timeout. Acctually, the scheduler port 5000 is ready, while the serving port 6178 is not.

Any suggestion is appreciated!

**Comment by jhinpan** [comment]
cc @ispobock @zhyncs . Could you help take a look on this? Thx a lot!

**Comment by zobinHuang** [comment]
same issue here

**Comment by HelloWorld506** [comment]
same issue here

**Comment by cahya-wirawan** [comment]
Maybe it has todo with the ddp_timeout which is set for 30 minutes (1800s) in transformers. So, try to increase it if you have big dataset to preprocess.
https://huggingface.co/docs/transformers/v4.49.0/en/main_classes/trainer#transformers.TrainingArguments.ddp_timeout

**Comment by tanjunchen** [comment]
same issue here   @joerong888

**Comment by kebe7jun** [comment]
Perhaps you can test the network connectivity by running some commands.

For example, running `nc -k -l 0.0.0.0 5000 -vn` on the first node, running `nc <IP> 5000 -vn` on the second node to check network.

**Comment by purp1e-ace** [comment]
same here

**Comment by tanjunchen** [comment]
this work
```
export SGLANG_HOST_IP=$(hostname -I | awk '{print $1}')
export HOST_IP=$(hostname -I | awk '{print $1}')
```

**Comment by tanjunchen** [comment]
the same issue  https://github.com/sgl-project/sglang/issues/4978

**Comment by ywen666** [comment]
I had similar issue (also ipv6 environment) and this is not working for me. Are there ways to get more info on what the code is stuck?


> ```
> export SGLANG_HOST_IP=$(hostname -I | awk '{print $1}')
> export HOST_IP=$(hostname -I | awk '{print $1}')
> ```

**Comment by ywen666** [comment]
> I had similar issue (also ipv6 environment) and this is not working for me. Are there ways to get more info on what the code is stuck?
> 
> > ```
> > export SGLANG_HOST_IP=$(hostname -I | awk '{print $1}')
> > export HOST_IP=$(hostname -I | awk '{print $1}')
> > ```


Turns out I need to do `connect_ip.strip("[]")`

for this line https://github.com/sgl-project/sglang/blob/a167fd0bcb9ef4b0f4331a109e40c8cdc770b026/python/sglang/srt/distributed/device_communicators/shm_broadcast.py#L289
