### ISSUE TITLE
[Bug]DeepSeek-R1 Process hangs after NCCL initialization in multi-server distributed inference setup

### ISSUE THREAD

**Issue by Orangels** [sgl-project/sglang#3516]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Environment and Setup
I am trying to run the DeepSeek-R1 671B model on three servers, each equipped with 8 A800 GPUs
I have 3 servers, each with 8 * A800 GPUs. I'm trying to create 5 nodes across these three servers using Docker overlay network for distributed inference, with each node using 4 GPUs. I've confirmed that all nodes can ping each other and NCCL communication is working.
 All nodes get stuck at the following log point.
Logs:
```
0d7b897a995a:1334:1334 [1] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 1 p2p channels per peer
0d7b897a995a:1333:1333 [0] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 1 p2p channels per peer
0d7b897a995a:1333:1333 [0] NCCL INFO TUNER/Plugin: Plugin load returned 11 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-tuner.so
0d7b897a995a:1334:1334 [1] NCCL INFO TUNER/Plugin: Plugin load returned 11 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-tuner.so
0d7b897a995a:1333:1333 [0] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
0d7b897a995a:1334:1334 [1] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
0d7b897a995a:1333:1333 [0] NCCL INFO ncclCommInitRank comm 0x39a43760 rank 12 nranks 20 cudaDev 0 nvmlDev 0 busId 9c000 commId 0xa9929a515b8ef6f6 - Init COMPLETE
0d7b897a995a:1334:1334 [1] NCCL INFO ncclCommInitRank comm 0x23c6e370 rank 13 nranks 20 cudaDev 1 nvmlDev 1 busId 9d000 commId 0xa9929a515b8ef6f6 - Init COMPLETE
0d7b897a995a:1335:1335 [2] NCCL INFO TUNER/Plugin: Plugin load returned 11 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-tuner.so
0d7b897a995a:1335:1335 [2] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
0d7b897a995a:1335:1335 [2] NCCL INFO ncclCommInitRank comm 0x46c01570 rank 14 nranks 20 cudaDev 2 nvmlDev 2 busId a0000 commId 0xa9929a515b8ef6f6 - Init COMPLETE
0d7b897a995a:1336:1336 [3] NCCL INFO TUNER/Plugin: Plugin load returned 11 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-tuner.so
0d7b897a995a:1336:1336 [3] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
0d7b897a995a:1336:1336 [3] NCCL INFO ncclCommInitRank comm 0x3ee7d680 rank 15 nranks 20 cudaDev 3 nvmlDev 3 busId a4000 commId 0xa9929a515b8ef6f6 - Init COMPLETE
[2025-02-11 18:41:41 TP15] Custom allreduce is disabled because this process group spans across nodes.
[2025-02-11 18:41:41 TP13] Custom allreduce is disabled because this process group spans across nodes.
[2025-02-11 18:41:41 TP14] Custom allreduce is disabled because this process group spans across nodes.
[2025-02-11 18:41:41 TP12] Custom allreduce is disabled because this process group spans across nodes.
```
Any assistance would be greatly appreciated.

### Reproduction

```
bash
docker run --gpus '"device=0,1,2,3"' \
    --shm-size 32g \
    --network=my_overlay_network \
    -v /data:/data \
    -p 3000:3000 \
    --name sglang_node0 \
    -it \
    --rm \
    --ipc=host \
    -e NCCL_SOCKET_IFNAME=eth0 \
    -e NCCL_DEBUG=INFO \
    lmsysorg/sglang:latest \
    python3 -m sglang.launch_server \
    --model-path /data/ls_data/models/deepseek/DeepSeek-R1-bf16 \
    --tp 20 \
    --dist-init-addr 192.168.200.33:5000 \
    --nnodes 5 \
    --node-rank 0 \
    --trust-remote-code \
    --host 0.0.0.0 \
    --port 3000
```

Similar commands for nodes 0-4 with appropriate GPU device mappings and node ranks
model: DeepSeek-R1-bf16

### Environment

```
Python: 3.10.16 (main, Dec  4 2024, 08:53:37) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A800 80GB PCIe
GPU 0,1,2,3 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.5, V12.5.82
CUDA Driver Version: 565.57.01
PyTorch: 2.5.1+cu124
flashinfer: 0.2.0.post2+cu124torch2.5
triton: 3.1.0
transformers: 4.48.3
torchao: 0.8.0
numpy: 1.26.4
aiohttp: 3.11.12
fastapi: 0.115.8
hf_transfer: 0.1.9
huggingface_hub: 0.28.1
interegular: 0.3.3
modelscope: 1.22.3
orjson: 3.10.15
packaging: 24.2
psutil: 6.1.1
pydantic: 2.10.6
multipart: 0.0.20
zmq: 26.2.1
uvicorn: 0.34.0
uvloop: 0.21.0
vllm: 0.6.4.post1
openai: 1.61.1
anthropic: 0.45.2
decord: 0.6.0
NVIDIA Topology:
        GPU0    GPU1    GPU2    GPU3    NIC0    NIC1    NIC2    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     PXB     PXB     SYS     SYS     NODE    16-31,48-63     1               N/A
GPU1    PIX      X      PXB     PXB     SYS     SYS     NODE    16-31,48-63     1               N/A
GPU2    PXB     PXB      X      PXB     SYS     SYS     NODE    16-31,48-63     1               N/A
GPU3    PXB     PXB     PXB      X      SYS     SYS     NODE    16-31,48-63     1               N/A
NIC0    SYS     SYS     SYS     SYS      X      PIX     SYS
NIC1    SYS     SYS     SYS     SYS     PIX      X      SYS
NIC2    NODE    NODE    NODE    NODE    SYS     SYS      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2


ulimit soft: 1048576
```

**Comment by Time-Limit** [comment]
@Orangels Hi, do you find the reason? I got the same error.

Process hangs on this line
https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/distributed/device_communicators/pynccl.py#L116

**Comment by jhinpan** [comment]
Here is a doc that you can refer: https://github.com/sgl-project/sglang/blob/main/benchmark/deepseek_v3/README.md#example-serving-with-four-a1008-nodes.

Since the BF16 model is over 1.3 TB, we need to prepare four A100 nodes, each with 8 80GB GPUs. I don't think 3 servers of 8 * A800 GPUs is enough.

**Comment by Orangels** [comment]
> Here is a doc that you can refer: https://github.com/sgl-project/sglang/blob/main/benchmark/deepseek_v3/README.md#example-serving-with-four-a1008-nodes.
> 
> Since the BF16 model is over 1.3 TB, we need to prepare four A100 nodes, each with 8 80GB GPUs. I don't think 3 servers of 8 * A800 GPUs is enough.

I was following the instructions from this documentation at https://github.com/sgl-project/sglang/blob/main/benchmark/deepseek_v3/README.md#example-serving-with-four-a1008-nodes.  
I'm trying to run it with 20 GPUs with a total of 1.6TB memory, but the process gets stuck even before loading the model. Could you help me identify what might be causing this issue?

**Comment by Orangels** [comment]
> [@Orangels](https://github.com/Orangels) Hi, do you find the reason? I got the same error.
> 
> Process hangs on this line https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/distributed/device_communicators/pynccl.py#L116

Thank you. I haven't identified the root cause yet. I will run some tests and debug according to your suggestions.

**Comment by ericg108** [comment]
i'm using a800 and got hung also after outputing: 
`INFO 02-13 08:41:37 __init__.py:190] Automatically detected platform cuda.
INFO 02-13 08:41:37 __init__.py:190] Automatically detected platform cuda.
INFO 02-13 08:41:37 __init__.py:190] Automatically detected platform cuda.
INFO 02-13 08:41:37 __init__.py:190] Automatically detected platform cuda.
INFO 02-13 08:41:37 __init__.py:190] Automatically detected platform cuda.
[2025-02-13 08:41:43 TP2] MLA optimization is turned on. Use triton backend.
[2025-02-13 08:41:43 TP2] Init torch distributed begin.
[2025-02-13 08:41:43 TP0] MLA optimization is turned on. Use triton backend.
[2025-02-13 08:41:43 TP0] Init torch distributed begin.
[2025-02-13 08:41:43 TP3] MLA optimization is turned on. Use triton backend.
[2025-02-13 08:41:43 TP3] Init torch distributed begin.
[2025-02-13 08:41:43 TP1] MLA optimization is turned on. Use triton backend.
[2025-02-13 08:41:43 TP1] Init torch distributed begin.`

**Comment by YangZeyu95** [comment]
Same problem, I can load model with NCCL_P2P_DISABLE=1. But it bad for performance, any suggestion?

**Comment by PiyushSawarkar** [comment]
> i'm using a800 and got hung also after outputing: `INFO 02-13 08:41:37 __init__.py:190] Automatically detected platform cuda. INFO 02-13 08:41:37 __init__.py:190] Automatically detected platform cuda. INFO 02-13 08:41:37 __init__.py:190] Automatically detected platform cuda. INFO 02-13 08:41:37 __init__.py:190] Automatically detected platform cuda. INFO 02-13 08:41:37 __init__.py:190] Automatically detected platform cuda. [2025-02-13 08:41:43 TP2] MLA optimization is turned on. Use triton backend. [2025-02-13 08:41:43 TP2] Init torch distributed begin. [2025-02-13 08:41:43 TP0] MLA optimization is turned on. Use triton backend. [2025-02-13 08:41:43 TP0] Init torch distributed begin. [2025-02-13 08:41:43 TP3] MLA optimization is turned on. Use triton backend. [2025-02-13 08:41:43 TP3] Init torch distributed begin. [2025-02-13 08:41:43 TP1] MLA optimization is turned on. Use triton backend. [2025-02-13 08:41:43 TP1] Init torch distributed begin.`

So may I know if anybody is able to resolve this issue? I had followed the same procedure to deploy the Model across 4 H100 Nodes, but it got stuck at the above!

**Comment by whybeyoung** [comment]
set NCCL_DEBUG=TRACE to see the last output.. 

if you find some msg like [this](https://github.com/NVIDIA/nccl/issues/426)
try to set NCCL_IB_GID_INDEX=3

**Comment by zhyncs** [comment]
> set NCCL_DEBUG=TRACE to see the last output..
> 
> if you find some msg like [this](https://github.com/NVIDIA/nccl/issues/426) try to set NCCL_IB_GID_INDEX=3

Thanks! It works!!

**Comment by Ming-hia** [comment]
I got the same error and  NCCL_IB_GID_INDEX=3 does not work

**Comment by HelloWorld506** [comment]
the same error, and it does not work for using NCCL_IB_GID_INDEX=3 and NCCL_P2P_DISABLE=1. could someone can help to fix this problem? I'll appreciate it very much

**Comment by JordiBayarri** [comment]
Same problem.  Mentioned solution does not work for H100 nodes.

**Comment by jue-jue-zi** [comment]
Try to disable IB by `export NCCL_IB_DISABLE=1`.
