### ISSUE TITLE
[Bug] When running multi-level and multi-GPU inference using 2 A100*8 cards, it fails to operate.

### ISSUE THREAD

**Issue by luhairong11** [sgl-project/sglang#3794]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

When running multi-level and multi-GPU inference using 2 A100*8 cards, it fails to operate.
The head node reports an error as follows:

[2025-02-23 06:02:12 TP1] sglang is using nccl==2.21.5
[2025-02-23 06:02:12 TP3] sglang is using nccl==2.21.5
[2025-02-23 06:02:12 TP5] sglang is using nccl==2.21.5
[2025-02-23 06:02:12 TP6] sglang is using nccl==2.21.5
[2025-02-23 06:02:12 TP4] sglang is using nccl==2.21.5
[2025-02-23 06:02:12 TP7] sglang is using nccl==2.21.5
[2025-02-23 06:02:12 TP2] sglang is using nccl==2.21.5
[2025-02-23 06:04:22 TP7] Scheduler hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1816, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 240, in __init__
    self.tp_worker = TpWorkerClass(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 68, in __init__
    self.model_runner = ModelRunner(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 187, in __init__
    min_per_gpu_memory = self.init_torch_distributed()
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 262, in init_torch_distributed
    initialize_model_parallel(tensor_model_parallel_size=self.tp_size)
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 1055, in initialize_model_parallel
    _TP = init_model_parallel_group(
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 890, in init_model_parallel_group
    return GroupCoordinator(
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 233, in __init__
    self.pynccl_comm = PyNcclCommunicator(
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl.py", line 108, in __init__
    self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in ncclCommInitRank
    self.NCCL_CHECK(
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 329, in NCCL_CHECK
    raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)

### Reproduction

head node:
docker run --gpus all \
    --shm-size 32g \
    --network=host \
	--privileged=true \
	-p 31011:31011 \
    -p 31012:31012 \
    -p 31013:31013 \
    -v /data/chdmx/lhr:/home/lhr \
    -v /data/chdmx/models/LLM_models:/data/chdmx/models/LLM_models \
    --name sglang_multinode1 \
    -it \
    --rm \
    --env "HF_TOKEN=$HF_TOKEN" \
    --ipc=host \
    docker.1ms.run/lmsysorg/sglang:dev \
    python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 0 --trust-remote-code --host 0.0.0.0 --port 31012

work node:
docker run --gpus all \
    --shm-size 32g \
    --network=host \
	--privileged=true \
	-p 31011:31011 \
    -p 31012:31012 \
    -p 31013:31013 \
    -v /data/chdmx/lhr:/home/lhr \
    -v /data/chdmx/models/LLM_models:/data/chdmx/models/LLM_models \
    --name sglang_multinode1 \
    -it \
    --rm \
    --env "HF_TOKEN=$HF_TOKEN" \
    --ipc=host \
    docker.1ms.run/lmsysorg/sglang:dev \
    python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 1 --trust-remote-code --host 0.0.0.0 --port 31012

### Environment

Pulled the official development image

lmsysorg/sglang:dev

**Comment by teadross** [comment]
i think it is because you may not specify the NCCL/GLOO network socket. try to add these ENVs when you start the docker container:
```
    -e GLOO_SOCKET_IFNAME='xxx' \
    -e TP_SOCKET_IFNAME='xxx' \
    -e NCCL_SOCKET_IFNAME='xxx' \
    -e NCCL_DEBUG='info' \
    -e NCCL_NET='Socket' \
    -e NCCL_IB_DISABLE='0' \
```
note that the `xxx` part is your network socket which can get from `ifconfig` command.
hopefully it can help you.

**Comment by luhairong11** [comment]
> i think it is because you may not specify the NCCL/GLOO network socket. try to add these ENVs when you start the docker container:
> 
> ```
>     -e GLOO_SOCKET_IFNAME='xxx' \
>     -e TP_SOCKET_IFNAME='xxx' \
>     -e NCCL_SOCKET_IFNAME='xxx' \
>     -e NCCL_DEBUG='info' \
>     -e NCCL_NET='Socket' \
>     -e NCCL_IB_DISABLE='0' \
> ```
> 
> note that the `xxx` part is your network socket which can get from `ifconfig` command. hopefully it can help you.

Now, I have changed to run directly on the host machines of two servers.
## one node:
step1. Set environment variables

export GLOO_SOCKET_IFNAME=bond0
export TP_SOCKET_IFNAME=bond0
export NCCL_SOCKET_IFNAME=bond0
export NCCL_DEBUG=TRACE
export NCCL_NET=Socket
export NCCL_IB_DISABLE=0
step2: 
    python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek_ai/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 0 --trust-remote-code --host 0.0.0.0 --port 31012

## second node:
step1. Set environment variables

export GLOO_SOCKET_IFNAME=bond0
export TP_SOCKET_IFNAME=bond0
export NCCL_SOCKET_IFNAME=bond0
export NCCL_DEBUG=TRACE
export NCCL_NET=Socket
export NCCL_IB_DISABLE=0
step2: 
    python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek_ai/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 1 --trust-remote-code --host 0.0.0.0 --port 31012

## The error reported by the master node is as follows:

bms-schyjdmx07:2242832:2242832 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to bond0
bms-schyjdmx07:2242832:2242832 [0] NCCL INFO NET/Socket : Using [0]bond0:192.168.8.19<0>
bms-schyjdmx07:2242832:2242832 [0] NCCL INFO Using non-device net plugin version 0
bms-schyjdmx07:2242832:2242832 [0] NCCL INFO Using network Socket

bms-schyjdmx07:2242839:2242839 [7] misc/socket.cc:484 NCCL WARN socketStartConnect: Connect to 192.168.8.62<50655> failed : Software caused connection abort
bms-schyjdmx07:2242839:2242839 [7] NCCL INFO misc/socket.cc:567 -> 2
bms-schyjdmx07:2242839:2242839 [7] NCCL INFO misc/socket.cc:621 -> 2
bms-schyjdmx07:2242839:2242839 [7] NCCL INFO bootstrap.cc:297 -> 2
bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1534 -> 2
bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1799 -> 2
bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1837 -> 2
[2025-02-23 20:28:30 TP7] Scheduler hit an exception: Traceback (most recent call last):
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1816, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 240, in __init__
    self.tp_worker = TpWorkerClass(
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 68, in __init__
    self.model_runner = ModelRunner(
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 187, in __init__
    min_per_gpu_memory = self.init_torch_distributed()
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 262, in init_torch_distributed
    initialize_model_parallel(tensor_model_parallel_size=self.tp_size)
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 1055, in initialize_model_parallel
    _TP = init_model_parallel_group(
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 890, in init_model_parallel_group
    return GroupCoordinator(
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 233, in __init__
    self.pynccl_comm = PyNcclCommunicator(
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl.py", line 108, in __init__
    self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in ncclCommInitRank
    self.NCCL_CHECK(
  File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 329, in NCCL_CHECK
    raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)

[2025-02-23 20:28:30] Received sigquit from a child proces. It usually means the child failed.
Killed

**Comment by teadross** [comment]
> > i think it is because you may not specify the NCCL/GLOO network socket. try to add these ENVs when you start the docker container:
> > ```
> >     -e GLOO_SOCKET_IFNAME='xxx' \
> >     -e TP_SOCKET_IFNAME='xxx' \
> >     -e NCCL_SOCKET_IFNAME='xxx' \
> >     -e NCCL_DEBUG='info' \
> >     -e NCCL_NET='Socket' \
> >     -e NCCL_IB_DISABLE='0' \
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > note that the `xxx` part is your network socket which can get from `ifconfig` command. hopefully it can help you.
> 
> Now, I have changed to run directly on the host machines of two servers.
> 
> ## one node:
> step1. Set environment variables
> 
> export GLOO_SOCKET_IFNAME=bond0 export TP_SOCKET_IFNAME=bond0 export NCCL_SOCKET_IFNAME=bond0 export NCCL_DEBUG=TRACE export NCCL_NET=Socket export NCCL_IB_DISABLE=0 step2: python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek_ai/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 0 --trust-remote-code --host 0.0.0.0 --port 31012
> 
> ## second node:
> step1. Set environment variables
> 
> export GLOO_SOCKET_IFNAME=bond0 export TP_SOCKET_IFNAME=bond0 export NCCL_SOCKET_IFNAME=bond0 export NCCL_DEBUG=TRACE export NCCL_NET=Socket export NCCL_IB_DISABLE=0 step2: python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek_ai/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 1 --trust-remote-code --host 0.0.0.0 --port 31012
> 
> ## The error reported by the master node is as follows:
> bms-schyjdmx07:2242832:2242832 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to bond0 bms-schyjdmx07:2242832:2242832 [0] NCCL INFO NET/Socket : Using [0]bond0:192.168.8.19<0> bms-schyjdmx07:2242832:2242832 [0] NCCL INFO Using non-device net plugin version 0 bms-schyjdmx07:2242832:2242832 [0] NCCL INFO Using network Socket
> 
> bms-schyjdmx07:2242839:2242839 [7] misc/socket.cc:484 NCCL WARN socketStartConnect: Connect to 192.168.8.62<50655> failed : Software caused connection abort bms-schyjdmx07:2242839:2242839 [7] NCCL INFO misc/socket.cc:567 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO misc/socket.cc:621 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO bootstrap.cc:297 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1534 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1799 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1837 -> 2 [2025-02-23 20:28:30 TP7] Scheduler hit an exception: Traceback (most recent call last): File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1816, in run_scheduler_process scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 240, in **init** self.tp_worker = TpWorkerClass( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in **init** self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 68, in **init** self.model_runner = ModelRunner( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 187, in **init** min_per_gpu_memory = self.init_torch_distributed() File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 262, in init_torch_distributed initialize_model_parallel(tensor_model_parallel_size=self.tp_size) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 1055, in initialize_model_parallel _TP = init_model_parallel_group( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 890, in init_model_parallel_group return GroupCoordinator( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 233, in **init** self.pynccl_comm = PyNcclCommunicator( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl.py", line 108, in **init** self.comm: ncclComm_t = self.nccl.ncclCommInitRank( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in ncclCommInitRank self.NCCL_CHECK( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 329, in NCCL_CHECK raise RuntimeError(f"NCCL error: {error_str}") RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
> 
> [2025-02-23 20:28:30] Received sigquit from a child proces. It usually means the child failed. Killed

can you show me the result of  `ifconfig` in your nodes?

**Comment by luhairong11** [comment]
> > > i think it is because you may not specify the NCCL/GLOO network socket. try to add these ENVs when you start the docker container:
> > > ```
> > >     -e GLOO_SOCKET_IFNAME='xxx' \
> > >     -e TP_SOCKET_IFNAME='xxx' \
> > >     -e NCCL_SOCKET_IFNAME='xxx' \
> > >     -e NCCL_DEBUG='info' \
> > >     -e NCCL_NET='Socket' \
> > >     -e NCCL_IB_DISABLE='0' \
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > note that the `xxx` part is your network socket which can get from `ifconfig` command. hopefully it can help you.
> > 
> > 
> > Now, I have changed to run directly on the host machines of two servers.
> > ## one node:
> > step1. Set environment variables
> > export GLOO_SOCKET_IFNAME=bond0 export TP_SOCKET_IFNAME=bond0 export NCCL_SOCKET_IFNAME=bond0 export NCCL_DEBUG=TRACE export NCCL_NET=Socket export NCCL_IB_DISABLE=0 step2: python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek_ai/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 0 --trust-remote-code --host 0.0.0.0 --port 31012
> > ## second node:
> > step1. Set environment variables
> > export GLOO_SOCKET_IFNAME=bond0 export TP_SOCKET_IFNAME=bond0 export NCCL_SOCKET_IFNAME=bond0 export NCCL_DEBUG=TRACE export NCCL_NET=Socket export NCCL_IB_DISABLE=0 step2: python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek_ai/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 1 --trust-remote-code --host 0.0.0.0 --port 31012
> > ## The error reported by the master node is as follows:
> > bms-schyjdmx07:2242832:2242832 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to bond0 bms-schyjdmx07:2242832:2242832 [0] NCCL INFO NET/Socket : Using [0]bond0:192.168.8.19<0> bms-schyjdmx07:2242832:2242832 [0] NCCL INFO Using non-device net plugin version 0 bms-schyjdmx07:2242832:2242832 [0] NCCL INFO Using network Socket
> > bms-schyjdmx07:2242839:2242839 [7] misc/socket.cc:484 NCCL WARN socketStartConnect: Connect to 192.168.8.62<50655> failed : Software caused connection abort bms-schyjdmx07:2242839:2242839 [7] NCCL INFO misc/socket.cc:567 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO misc/socket.cc:621 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO bootstrap.cc:297 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1534 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1799 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1837 -> 2 [2025-02-23 20:28:30 TP7] Scheduler hit an exception: Traceback (most recent call last): File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1816, in run_scheduler_process scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 240, in **init** self.tp_worker = TpWorkerClass( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in **init** self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 68, in **init** self.model_runner = ModelRunner( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 187, in **init** min_per_gpu_memory = self.init_torch_distributed() File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 262, in init_torch_distributed initialize_model_parallel(tensor_model_parallel_size=self.tp_size) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 1055, in initialize_model_parallel _TP = init_model_parallel_group( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 890, in init_model_parallel_group return GroupCoordinator( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 233, in **init** self.pynccl_comm = PyNcclCommunicator( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl.py", line 108, in **init** self.comm: ncclComm_t = self.nccl.ncclCommInitRank( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in ncclCommInitRank self.NCCL_CHECK( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 329, in NCCL_CHECK raise RuntimeError(f"NCCL error: {error_str}") RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
> > [2025-02-23 20:28:30] Received sigquit from a child proces. It usually means the child failed. Killed
> 
> can you show me the result of `ifconfig` in your nodes?

![Image](https://github.com/user-attachments/assets/7081f523-7eca-40df-92aa-18635eccdfda)

**Comment by teadross** [comment]
> > > > i think it is because you may not specify the NCCL/GLOO network socket. try to add these ENVs when you start the docker container:
> > > > ```
> > > >     -e GLOO_SOCKET_IFNAME='xxx' \
> > > >     -e TP_SOCKET_IFNAME='xxx' \
> > > >     -e NCCL_SOCKET_IFNAME='xxx' \
> > > >     -e NCCL_DEBUG='info' \
> > > >     -e NCCL_NET='Socket' \
> > > >     -e NCCL_IB_DISABLE='0' \
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > note that the `xxx` part is your network socket which can get from `ifconfig` command. hopefully it can help you.
> > > 
> > > 
> > > Now, I have changed to run directly on the host machines of two servers.
> > > ## one node:
> > > step1. Set environment variables
> > > export GLOO_SOCKET_IFNAME=bond0 export TP_SOCKET_IFNAME=bond0 export NCCL_SOCKET_IFNAME=bond0 export NCCL_DEBUG=TRACE export NCCL_NET=Socket export NCCL_IB_DISABLE=0 step2: python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek_ai/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 0 --trust-remote-code --host 0.0.0.0 --port 31012
> > > ## second node:
> > > step1. Set environment variables
> > > export GLOO_SOCKET_IFNAME=bond0 export TP_SOCKET_IFNAME=bond0 export NCCL_SOCKET_IFNAME=bond0 export NCCL_DEBUG=TRACE export NCCL_NET=Socket export NCCL_IB_DISABLE=0 step2: python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek_ai/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 1 --trust-remote-code --host 0.0.0.0 --port 31012
> > > ## The error reported by the master node is as follows:
> > > bms-schyjdmx07:2242832:2242832 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to bond0 bms-schyjdmx07:2242832:2242832 [0] NCCL INFO NET/Socket : Using [0]bond0:192.168.8.19<0> bms-schyjdmx07:2242832:2242832 [0] NCCL INFO Using non-device net plugin version 0 bms-schyjdmx07:2242832:2242832 [0] NCCL INFO Using network Socket
> > > bms-schyjdmx07:2242839:2242839 [7] misc/socket.cc:484 NCCL WARN socketStartConnect: Connect to 192.168.8.62<50655> failed : Software caused connection abort bms-schyjdmx07:2242839:2242839 [7] NCCL INFO misc/socket.cc:567 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO misc/socket.cc:621 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO bootstrap.cc:297 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1534 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1799 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1837 -> 2 [2025-02-23 20:28:30 TP7] Scheduler hit an exception: Traceback (most recent call last): File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1816, in run_scheduler_process scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 240, in **init** self.tp_worker = TpWorkerClass( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in **init** self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 68, in **init** self.model_runner = ModelRunner( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 187, in **init** min_per_gpu_memory = self.init_torch_distributed() File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 262, in init_torch_distributed initialize_model_parallel(tensor_model_parallel_size=self.tp_size) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 1055, in initialize_model_parallel _TP = init_model_parallel_group( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 890, in init_model_parallel_group return GroupCoordinator( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 233, in **init** self.pynccl_comm = PyNcclCommunicator( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl.py", line 108, in **init** self.comm: ncclComm_t = self.nccl.ncclCommInitRank( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in ncclCommInitRank self.NCCL_CHECK( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 329, in NCCL_CHECK raise RuntimeError(f"NCCL error: {error_str}") RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
> > > [2025-02-23 20:28:30] Received sigquit from a child proces. It usually means the child failed. Killed
> > 
> > 
> > can you show me the result of `ifconfig` in your nodes?
> 
> ![Image](https://github.com/user-attachments/assets/7081f523-7eca-40df-92aa-18635eccdfda)

um, I am not very sure, but since the following info is mentioned in your log:
```
bms-schyjdmx07:2242839:2242839 [7] misc/socket.cc:484 NCCL WARN socketStartConnect: Connect to 192.168.8.62<50655> failed : Software caused connection abort
```
Can you check whether these two nodes can connect with each other? maybe the firewall forbids the connection?

**Comment by luhairong11** [comment]
> > > > > i think it is because you may not specify the NCCL/GLOO network socket. try to add these ENVs when you start the docker container:
> > > > > ```
> > > > >     -e GLOO_SOCKET_IFNAME='xxx' \
> > > > >     -e TP_SOCKET_IFNAME='xxx' \
> > > > >     -e NCCL_SOCKET_IFNAME='xxx' \
> > > > >     -e NCCL_DEBUG='info' \
> > > > >     -e NCCL_NET='Socket' \
> > > > >     -e NCCL_IB_DISABLE='0' \
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > note that the `xxx` part is your network socket which can get from `ifconfig` command. hopefully it can help you.
> > > > 
> > > > 
> > > > Now, I have changed to run directly on the host machines of two servers.
> > > > ## one node:
> > > > step1. Set environment variables
> > > > export GLOO_SOCKET_IFNAME=bond0 export TP_SOCKET_IFNAME=bond0 export NCCL_SOCKET_IFNAME=bond0 export NCCL_DEBUG=TRACE export NCCL_NET=Socket export NCCL_IB_DISABLE=0 step2: python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek_ai/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 0 --trust-remote-code --host 0.0.0.0 --port 31012
> > > > ## second node:
> > > > step1. Set environment variables
> > > > export GLOO_SOCKET_IFNAME=bond0 export TP_SOCKET_IFNAME=bond0 export NCCL_SOCKET_IFNAME=bond0 export NCCL_DEBUG=TRACE export NCCL_NET=Socket export NCCL_IB_DISABLE=0 step2: python3 -m sglang.launch_server --model-path /data/chdmx/models/LLM_models/deepseek_ai/DeepSeek-R1-Distill-Qwen-1.5B --tp 16 --dist-init-addr 192.168.8.19:31011 --nnodes 2 --node-rank 1 --trust-remote-code --host 0.0.0.0 --port 31012
> > > > ## The error reported by the master node is as follows:
> > > > bms-schyjdmx07:2242832:2242832 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to bond0 bms-schyjdmx07:2242832:2242832 [0] NCCL INFO NET/Socket : Using [0]bond0:192.168.8.19<0> bms-schyjdmx07:2242832:2242832 [0] NCCL INFO Using non-device net plugin version 0 bms-schyjdmx07:2242832:2242832 [0] NCCL INFO Using network Socket
> > > > bms-schyjdmx07:2242839:2242839 [7] misc/socket.cc:484 NCCL WARN socketStartConnect: Connect to 192.168.8.62<50655> failed : Software caused connection abort bms-schyjdmx07:2242839:2242839 [7] NCCL INFO misc/socket.cc:567 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO misc/socket.cc:621 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO bootstrap.cc:297 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1534 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1799 -> 2 bms-schyjdmx07:2242839:2242839 [7] NCCL INFO init.cc:1837 -> 2 [2025-02-23 20:28:30 TP7] Scheduler hit an exception: Traceback (most recent call last): File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1816, in run_scheduler_process scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 240, in **init** self.tp_worker = TpWorkerClass( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in **init** self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 68, in **init** self.model_runner = ModelRunner( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 187, in **init** min_per_gpu_memory = self.init_torch_distributed() File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 262, in init_torch_distributed initialize_model_parallel(tensor_model_parallel_size=self.tp_size) File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 1055, in initialize_model_parallel _TP = init_model_parallel_group( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 890, in init_model_parallel_group return GroupCoordinator( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/parallel_state.py", line 233, in **init** self.pynccl_comm = PyNcclCommunicator( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl.py", line 108, in **init** self.comm: ncclComm_t = self.nccl.ncclCommInitRank( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in ncclCommInitRank self.NCCL_CHECK( File "/home/luhr/anaconda3/envs/inf_sg/lib/python3.10/site-packages/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 329, in NCCL_CHECK raise RuntimeError(f"NCCL error: {error_str}") RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
> > > > [2025-02-23 20:28:30] Received sigquit from a child proces. It usually means the child failed. Killed
> > > 
> > > 
> > > can you show me the result of `ifconfig` in your nodes?
> > 
> > 
> > ![Image](https://github.com/user-attachments/assets/7081f523-7eca-40df-92aa-18635eccdfda)
> 
> um, I am not very sure, but since the following info is mentioned in your log:
> 
> ```
> bms-schyjdmx07:2242839:2242839 [7] misc/socket.cc:484 NCCL WARN socketStartConnect: Connect to 192.168.8.62<50655> failed : Software caused connection abort
> ```
> 
> Can you check whether these two nodes can connect with each other? maybe the firewall forbids the connection?
192.168.8.19 is able to access 192.168.8.62
![Image](https://github.com/user-attachments/assets/7cd08672-3778-4065-b2d3-445d1fd78099)

**Comment by teadross** [comment]
`ping` means that the ICMP (Port 1) is allowed. however, in the log, I think NCCL is using Port 50655.

**Comment by luhairong11** [comment]
This port tends to change frequently, and it doesn't seem advisable to open it up.
![Image](https://github.com/user-attachments/assets/559dee96-e5de-4c08-9472-e1eaa1bcadf6)

**Comment by luhairong11** [comment]
It was a firewall issue, and it worked successfully after the firewall was turned off.

**Comment by xinyihaha** [comment]
Hello,

**Comment by xinyihaha** [comment]
hello，I have done:
1、# node 1
export GLOO_SOCKET_IFNAME=bond0
export TP_SOCKET_IFNAME=bond0
export NCCL_SOCKET_IFNAME=bond0
export NCCL_DEBUG=TRACE
export NCCL_NET=Socket
export NCCL_IB_DISABLE=0
export NCCL_IB_HCA=mlx5
export NCCL_IB_GID_INDEX=3
export NCCL_P2P_DISABLE=1

python3 -m sglang.launch_server --model-path /mnt/hpfs/deepseekV3-models/models/deepseek-ai/DeepSeek-V3 --tp 16 --dist-init-addr 10.0.0.4:20002 --nnodes 2 --node-rank 0 --trust-remote-code --host 0.0.0.0 --port 40001

2、node 2
export GLOO_SOCKET_IFNAME=bond0
export TP_SOCKET_IFNAME=bond0
export NCCL_SOCKET_IFNAME=bond0
export NCCL_DEBUG=TRACE
export NCCL_NET=Socket
export NCCL_IB_DISABLE=0
export NCCL_IB_HCA=mlx5
export NCCL_IB_GID_INDEX=3
export NCCL_P2P_DISABLE=1

python3 -m sglang.launch_server --model-path /mnt/hpfs/deepseekV3-models/models/deepseek-ai/DeepSeek-V3 --tp 16 --dist-init-addr 10.0.0.4:20002 --nnodes 2 --node-rank 1 --trust-remote-code --host 0.0.0.0 --port 40001

but  the node 2 can't work：

![Image](https://github.com/user-attachments/assets/a30f3bb5-d15f-4a58-a470-62bcc9c0b3b3)

**Comment by zzjSteven** [comment]
> 是防火墙的问题，关闭防火墙后就可以成功了。

![Image](https://github.com/user-attachments/assets/f950df30-be0c-494f-bf0b-c446c612184c) 我关了防火墙，多卡多节点还是报

**Comment by zzjSteven** [comment]
> It was a firewall issue, and it worked successfully after the firewall was turned off.
Code deployed on L20 machine
![Image](https://github.com/user-attachments/assets/f6cba2ff-e946-448b-9926-a5159028a1bc)

[2025-02-26 12:01:56 TP3] sglang is using nccl==2.21.5
[2025-02-26 12:01:56 TP5] sglang is using nccl==2.21.5
[2025-02-26 12:01:56 TP4] sglang is using nccl==2.21.5
[2025-02-26 12:01:56 TP7] sglang is using nccl==2.21.5
[2025-02-26 12:01:56 TP2] Scheduler hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1816, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 240, in __init__
    self.tp_worker = TpWorkerClass(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 68, in __init__
    self.model_runner = ModelRunner(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 187, in __init__
    min_per_gpu_memory = self.init_torch_distributed()
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 262, in init_torch_distributed
    initialize_model_parallel(tensor_model_parallel_size=self.tp_size)
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 1055, in initialize_model_parallel
    _TP = init_model_parallel_group(
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 890, in init_model_parallel_group
    return GroupCoordinator(
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 233, in __init__
    self.pynccl_comm = PyNcclCommunicator(
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl.py", line 108, in __init__
    self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in ncclCommInitRank
    self.NCCL_CHECK(
  File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 329, in NCCL_CHECK
    raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)       
# node 1
sudo docker run --gpus all \
    --shm-size 32g \
    --network=host \
    -v /data/models:/data/models \
	-v /tmp/nccl_logs:/mnt/nccl_logs \
    --name sglang_multinode1 \
    -it \
    --rm \
    --env "HF_TOKEN=$HF_TOKEN" \
	--env "NCCL_IB_GID_INDEX=3" \
	--env "NCCL_DEBUG_INFO=WARN" \
	--env "NCCL_DEBUG=TRACE" \
	--env "NCCL_DEBUG_FILE=/mnt/nccl_logs/nccl_debug_$(date +%Y%m%d_%H%M%S).log" \
	--env "GLOO_SOCKET_IFNAME=bond0" \
	--env "TP_SOCKET_IFNAME=bond0" \
	--env "NCCL_SOCKET_IFNAME=bond0" \
	--env "NCCL_NET=Socket" \
	--env "NCCL_IB_DISABLE=0" \
    --ipc=host \
    lmsysorg/sglang:v0.4.2.post4-cu125 \
    python3 -m sglang.launch_server --model-path /data/models/DeepSeek/DeepSeek-R1-671 --tp 16 --dist-init-addr xxxx:20000 --nnodes 2 --node-rank 0 --trust-remote-code --host 0.0.0.0 --port 40000

# node 2
sudo docker run --gpus all \
    --shm-size 32g \
    --network=host \
    -v /data/models:/data/models \
	-v /tmp/nccl_logs:/mnt/nccl_logs \
    --name sglang_multinode2 \
    -it \
    --rm \
	--env "HF_TOKEN=$HF_TOKEN" \
	--env "NCCL_IB_GID_INDEX=3" \
	--env "NCCL_DEBUG_INFO=WARN" \
	--env "NCCL_DEBUG=TRACE" \
	--env "NCCL_DEBUG_FILE=/mnt/nccl_logs/nccl_debug_$(date +%Y%m%d_%H%M%S).log" \
	--env "GLOO_SOCKET_IFNAME=bond0" \
	--env "TP_SOCKET_IFNAME=bond0" \
	--env "NCCL_SOCKET_IFNAME=bond0" \
	--env "NCCL_NET=Socket" \
	--env "NCCL_IB_DISABLE=0" \
    --ipc=host \
    lmsysorg/sglang:v0.4.2.post4-cu125 \
    python3 -m sglang.launch_server --model-path /data/models/DeepSeek/DeepSeek-R1-671 --tp 16 --dist-init-addr xxxx:20000 --nnodes 2 --node-rank 1 --trust-remote-code --host 0.0.0.0 --port 40000

**Comment by chuangzhidan** [comment]
> It was a firewall issue, and it worked successfully after the firewall was turned off.

can i ask how to turn off  firewall
