### ISSUE TITLE
[Bug] sglang offline inference: "cuda out of memory" error, while vllm works fine

### ISSUE THREAD

**Issue by xhd0728** [sgl-project/sglang#4248]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

I am performing offline inference with sglang using 4 * Nvidia A100 80G GPUs and the [Qwen2.5-7B-Instruct](https://huggingface.co/Qwen/Qwen2.5-7B-Instruct) model. However, when launching sglang, I encountered a "CUDA out of memory" error, even though I attempted to adjust the mem_fraction_static parameter. There is no such problem when using vllm.


### Reproduction

Below is my python code and running log, no additional bash script needed.

```python
import os
import json
from typing import List, Dict, Any
from vllm import LLM, SamplingParams
import sglang as sgl

os.environ["CUDA_VISIBLE_DEVICES"] = "4,5,6,7"
backend = "sglang"

# MODEL_PATH = "/home/xinhaidong/model/openbmb/MiniCPM-o-2_6"
MODEL_PATH = "/home/xinhaidong/model/Qwen/Qwen2.5-7B-Instruct"
DATA_PATHS = {
    "train": "/home/xinhaidong/TASTE/data/toys/train.txt",
    "valid": "/home/xinhaidong/TASTE/data/toys/valid.txt",
    "test": "/home/xinhaidong/TASTE/data/toys/test.txt",
    "item": "/home/xinhaidong/TASTE/data/toys/item.txt",
    "output": {
        "train": "/home/xinhaidong/TASTE/gen/output/qwen2.5_7b/toys/train_cot.json",
        "valid": "/home/xinhaidong/TASTE/gen/output/qwen2.5_7b/toys/valid_cot.json",
        "test": "/home/xinhaidong/TASTE/gen/output/qwen2.5_7b/toys/test_cot.json",
    },
}


def read_data_file(file_path: str) -> List[Dict[str, Any]]:
    data = []
    with open(file_path, "r") as f:
        next(f)
        for line in f:
            parts = line.strip().split("\t")
            if len(parts) < 3:
                continue
            data.append(
                {
                    "user_id": parts[0],
                    "seq_ids": [pid for pid in parts[1:-1] if pid != "0"],
                    "target_id": parts[-1],
                }
            )
    return data


def read_item_mappings(file_path: str) -> Dict[str, str]:
    items = {}
    with open(file_path, "r") as f:
        next(f)
        for line in f:
            parts = line.strip().split("\t")
            if len(parts) >= 2:
                items[parts[0]] = parts[1]
    return items


def generate_prompts(data: List[Dict[str, Any]], item_map: Dict[str, str]) -> List[str]:
    prompts = []
    for entry in data:
        try:
            item_names = [item_map[pid] for pid in entry["seq_ids"] if pid in item_map]
            if not item_names:
                continue
            prompts.append(
                "Given a user's purchases of items in the Amazon toys category in order of timestamps, "
                "please analyze the characteristics of the items and the user's behavior logic, "
                "then predict the user's next purchase preference.\n\n"
                "Item list:\n" + "\n".join(item_names)
            )
        except KeyError as e:
            print(f"Warning: Missing item {e} in catalog")
    return prompts


def generate_explanations(prompts: List[str]) -> List[str]:
    if backend == "vllm":
        sampling_params = SamplingParams(
            temperature=0.8,
            top_p=0.95,
            max_tokens=2048,
        )
    elif backend == "sglang":
        sampling_params = {
            "temperature": 0.8,
            "top_p": 0.95,
            "max_new_tokens": 2048,
        }
    else:
        raise ValueError(f"Invalid backend: {backend}")

    outputs = llm.generate(prompts, sampling_params)
    return [output.outputs[0].text.strip() for output in outputs]


def process_dataset(
    data: List[Dict[str, Any]], item_map: Dict[str, str]
) -> List[Dict[str, Any]]:
    prompts = generate_prompts(data, item_map)
    explanations = generate_explanations(prompts)
    return [{"id": i + 1, "cot": exp} for i, exp in enumerate(explanations)]


def save_results(data: List[Dict[str, Any]], output_path: str):
    folder = os.path.dirname(output_path)
    if not os.path.exists(folder):
        os.makedirs(folder)
    with open(output_path, "w") as f:
        for entry in data:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")


def main():
    train_data = read_data_file(DATA_PATHS["train"])
    # valid_data = read_data_file(DATA_PATHS["valid"])
    # test_data = read_data_file(DATA_PATHS["test"])
    item_map = read_item_mappings(DATA_PATHS["item"])

    train_results = process_dataset(train_data, item_map)
    # valid_results = process_dataset(valid_data, item_map)
    # test_results = process_dataset(test_data, item_map)

    save_results(train_results, DATA_PATHS["output"]["train"])
    # save_results(valid_results, DATA_PATHS["output"]["valid"])
    # save_results(test_results, DATA_PATHS["output"]["test"])


if __name__ == "__main__":

    if backend == "vllm":
        llm = LLM(
            model=MODEL_PATH,
            trust_remote_code=True,
            tokenizer_mode="auto",
            tensor_parallel_size=4,
            dtype="auto",
            gpu_memory_utilization=0.9,
        )
    elif backend == "sglang":
        llm = sgl.Engine(
            model_path=MODEL_PATH,
            trust_remote_code=True,
            tp_size=4,
            mem_fraction_static=0.9,
        )
    else:
        raise ValueError(f"Invalid backend: {backend}")

    main()

```

```log
(sglang) xinhaidong@g3012:~/TASTE$ python gen/gen_cot.py                                                                                                                                                         
INFO 03-10 10:40:47 __init__.py:190] Automatically detected platform cuda.                                                                                                                                       
2025-03-10 10:41:31,611 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend                                                                                                                   
INFO 03-10 10:41:46 __init__.py:190] Automatically detected platform cuda.                                                                                                                                       
INFO 03-10 10:41:46 __init__.py:190] Automatically detected platform cuda.                                                                                                                                       
INFO 03-10 10:41:46 __init__.py:190] Automatically detected platform cuda.                                                                                                                                       
INFO 03-10 10:41:46 __init__.py:190] Automatically detected platform cuda.                                                                                                                                       
INFO 03-10 10:41:46 __init__.py:190] Automatically detected platform cuda.                                                                                                                                       
2025-03-10 10:41:52,925 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend                                                                                                                   
2025-03-10 10:41:53,801 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend                                                                                                                   
2025-03-10 10:41:53,961 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend                                                                                                                   
2025-03-10 10:41:54,060 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend                                                                                                                   
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]                                                                                                                                     
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:04<00:14,  4.68s/it]                                                                                                                             
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:15<00:16,  8.43s/it]                                                                                                                             
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:21<00:07,  7.22s/it]                                                                                                                             
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:25<00:00,  6.08s/it]                                                                                                                             
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:25<00:00,  6.46s/it]                                                                                                                             
                                                                                                                                                                                                                 
  0%|                                                                                                                                                                                     | 0/23 [00:00<?, ?it/s]
2025-03-10 10:42:50,999 - INFO - flashinfer.jit: Loading JIT ops: batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_128_head_dim_vo_128_posenc_0_use_swa_False_use_lo
gits_cap_False_f16qk_False
2025-03-10 10:42:50,999 - INFO - flashinfer.jit: Loading JIT ops: batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_128_head_dim_vo_128_posenc_0_use_swa_False_use_lo
gits_cap_False_f16qk_False
2025-03-10 10:42:50,999 - INFO - flashinfer.jit: Loading JIT ops: batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_128_head_dim_vo_128_posenc_0_use_swa_False_use_lo
gits_cap_False_f16qk_False
2025-03-10 10:42:50,999 - INFO - flashinfer.jit: Loading JIT ops: batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_128_head_dim_vo_128_posenc_0_use_swa_False_use_lo
gits_cap_False_f16qk_False
2025-03-10 10:44:19,606 - INFO - flashinfer.jit: Finished loading JIT ops: batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_128_head_dim_vo_128_posenc_0_use_swa_Fal
se_use_logits_cap_False_f16qk_False
2025-03-10 10:44:19,732 - INFO - flashinfer.jit: Finished loading JIT ops: batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_128_head_dim_vo_128_posenc_0_use_swa_Fal
se_use_logits_cap_False_f16qk_False
2025-03-10 10:44:19,810 - INFO - flashinfer.jit: Finished loading JIT ops: batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_128_head_dim_vo_128_posenc_0_use_swa_Fal
se_use_logits_cap_False_f16qk_False
2025-03-10 10:44:19,914 - INFO - flashinfer.jit: Finished loading JIT ops: batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_128_head_dim_vo_128_posenc_0_use_swa_Fal
se_use_logits_cap_False_f16qk_False
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [01:48<00:00,  4.71s/it]
2025-03-10 10:45:12,862 - INFO - flashinfer.jit: Loading JIT ops: cascade
2025-03-10 10:45:14,399 - INFO - flashinfer.jit: Loading JIT ops: cascade
2025-03-10 10:45:15,370 - INFO - flashinfer.jit: Loading JIT ops: cascade
2025-03-10 10:45:15,943 - INFO - flashinfer.jit: Loading JIT ops: cascade
2025-03-10 10:45:34,667 - INFO - flashinfer.jit: Finished loading JIT ops: cascade
2025-03-10 10:45:34,791 - INFO - flashinfer.jit: Finished loading JIT ops: cascade
2025-03-10 10:45:15,370 - INFO - flashinfer.jit: Loading JIT ops: cascade
2025-03-10 10:45:15,943 - INFO - flashinfer.jit: Loading JIT ops: cascade
2025-03-10 10:45:34,667 - INFO - flashinfer.jit: Finished loading JIT ops: cascade
2025-03-10 10:45:34,791 - INFO - flashinfer.jit: Finished loading JIT ops: cascade
2025-03-10 10:45:34,850 - INFO - flashinfer.jit: Finished loading JIT ops: cascade
2025-03-10 10:45:35,013 - INFO - flashinfer.jit: Finished loading JIT ops: cascade
[2025-03-10 10:46:09 TP0] TpModelWorkerClient hit an exception: Traceback (most recent call last):
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 109, in forward_thread_func
    self.forward_thread_func_()
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 140, in forward_thread_func_
    logits_output, next_token_ids = self.worker.forward_batch_generation(
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 172, in forward_batch_generation
    logits_output = self.model_runner.forward(forward_batch)
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 907, in forward
    return self.forward_decode(forward_batch)
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 858, in forward_decode
    return self.model.forward(
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 376, in forward
    return self.logits_processor(
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/layers/logits_processor.py", line 306, in forward
    logits = self._get_logits(pruned_states, lm_head, logits_metadata)
  File "/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/layers/logits_processor.py", line 439, in _get_logits
    logits = logits[:, : self.config.vocab_size].float()
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.84 GiB. GPU 0 has a total capacity of 79.19 GiB of which 1.72 GiB is free. Including non-PyTorch memory, this process has 77.47 GiB memory in use
. Of the allocated memory 72.20 GiB is allocated by PyTorch, with 959.14 MiB allocated in private pools (e.g., CUDA Graphs), and 615.93 MiB is reserved by PyTorch but unallocated. If reserved but unallocated m
emory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variab
les)

[2025-03-10 10:46:09] Received sigquit from a child process. It usually means the child failed.
Killed
(sglang) xinhaidong@g3012:~/TASTE$
```

### Environment

```
(sglang) xinhaidong@g3012:~/TASTE$ python3 -m sglang.check_env                                                                                                                                                   
2025-03-10 11:01:28,361 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend                                                                                                                   
INFO 03-10 11:01:41 __init__.py:190] Automatically detected platform cuda.                                                                                                                                       
/home/xinhaidong/miniconda3/envs/sglang/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.  
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].                                                                                                                                           
  warnings.warn(                                                                                                                                                                                                 
Python: 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0]                                                                                                                                                       
CUDA available: True                                                                                                                                                                                             
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB                                                                                                                                                                       
GPU 0,1,2,3,4,5,6,7 Compute Capability: 8.0                                                                                                                                                                      
CUDA_HOME: /usr/local/cuda                                                                                                                                                                                       
NVCC: Cuda compilation tools, release 12.1, V12.1.66                                                                                                                                                             
CUDA Driver Version: 530.30.02                                                                                                                                                                                   
PyTorch: 2.5.1+cu124                                                                                                                                                                                             
sglang: 0.4.3.post4                                                                                                                                                                                              
sgl_kernel: 0.0.3.post6                                                                                                                                                                                          
flashinfer: 0.2.2.post1+cu121torch2.5                                                                                                                                                                            
triton: 3.1.0                                                                                                                                                                                                    
transformers: 4.48.3                                                                                                                                                                                             
torchao: 0.9.0                                                                                                                                                                                                   
numpy: 1.26.4                                                                                                                                                                                                    
aiohttp: 3.11.13                                                                                                                                                                                                 
fastapi: 0.115.11                                                                                                                                                                                                
hf_transfer: 0.1.9                                                                                                                                                                                               
huggingface_hub: 0.29.2                                                                                                                                                                                          
interegular: 0.3.3                                                                                                                                                                                               
modelscope: 1.23.2
orjson: 3.10.15
packaging: 24.2
psutil: 7.0.0
pydantic: 2.10.6
multipart: 0.0.20
zmq: 26.2.1
uvicorn: 0.34.0
uvloop: 0.21.0
vllm: 0.7.2
openai: 1.65.4
tiktoken: 0.9.0
anthropic: 0.49.0
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    CPU Affinity    NUMA Affinity
GPU0     X      NV12    NV12    NV12    NV12    NV12    NV12    NV12    PXB     SYS     SYS     SYS     41,45,105,109   0-1
GPU1    NV12     X      NV12    NV12    NV12    NV12    NV12    NV12    PXB     SYS     SYS     SYS     41,45,105,109   0-1
GPU2    NV12    NV12     X      NV12    NV12    NV12    NV12    NV12    SYS     PXB     SYS     SYS     41,45,105,109   0-1
GPU3    NV12    NV12    NV12     X      NV12    NV12    NV12    NV12    SYS     PXB     SYS     SYS     41,45,105,109   0-1
GPU4    NV12    NV12    NV12    NV12     X      NV12    NV12    NV12    SYS     SYS     PXB     SYS     41,45,105,109   0-1
GPU5    NV12    NV12    NV12    NV12    NV12     X      NV12    NV12    SYS     SYS     PXB     SYS     41,45,105,109   0-1
GPU6    NV12    NV12    NV12    NV12    NV12    NV12     X      NV12    SYS     SYS     SYS     PXB     41,45,105,109   0-1
GPU7    NV12    NV12    NV12    NV12    NV12    NV12    NV12     X      SYS     SYS     SYS     PXB     41,45,105,109   0-1
NIC0    PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS     SYS
NIC1    SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS
NIC2    SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS      X      SYS
NIC3    SYS     SYS     SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3


ulimit soft: 655360
(sglang) xinhaidong@g3012:~/TASTE$ 
```

**Comment by SwarmKit** [comment]
我使用 4* A40 GPU 使用 --tp 2 时可以运行，但是当使用 --tp 4 时就h会报错；
`python3 -m sglang.launch_server --model-path /data/modelsfiles/DeepSeek-R1-Distill-Qwen-7B --served-model-name DeepSeek-R1-Distill-Qwen-7B --tp 2 --trust-remote-code --host 0.0.0.0 --port 40000 --disable-cuda-graph --log-level debug`
上面可以正常运行
```
root@9fe7aac881d5:/# python3 -m sglang.launch_server --model-path /data/modelsfiles/DeepSeek-R1-Distill-Qwen-7B --served-model-name DeepSeek-R1-Distill-Qwen-7B --tp 4 --trust-remote-code --host 0.0.0.0 --port 40000 --disable-cuda-graph --log-level debug
INFO 03-10 07:19:58 __init__.py:190] Automatically detected platform cuda.
2025-03-10 07:20:00,523 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
[2025-03-10 07:20:03] Setting Triton cache manager to: sglang.srt.utils:CustomCacheManager
[2025-03-10 07:20:03] server_args=ServerArgs(model_path='/data/modelsfiles/DeepSeek-R1-Distill-Qwen-7B', tokenizer_path='/data/modelsfiles/DeepSeek-R1-Distill-Qwen-7B', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', trust_remote_code=True, dtype='auto', kv_cache_dtype='auto', quantization=None, quantization_param_path=None, context_length=None, device='cuda', served_model_name='DeepSeek-R1-Distill-Qwen-7B', chat_template=None, is_embedding=False, revision=None, host='0.0.0.0', port=40000, mem_fraction_static=0.85, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='fcfs', schedule_conservativeness=1.0, cpu_offload_gb=0, tp_size=4, stream_interval=1, stream_output=False, random_seed=1034100912, constrained_json_whitespace_pattern=None, watchdog_timeout=300, dist_timeout=None, download_dir=None, base_gpu_id=0, gpu_id_step=1, log_level='debug', log_level_http=None, log_requests=False, log_requests_level=0, show_time_cost=False, enable_metrics=False, decode_log_interval=40, api_key=None, file_storage_path='sglang_storage', enable_cache_report=False, reasoning_parser=None, dp_size=1, load_balance_method='round_robin', ep_size=1, dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', lora_paths=None, max_loras_per_batch=8, lora_backend='triton', attention_backend='flashinfer', sampling_backend='flashinfer', grammar_backend='outlines', speculative_algorithm=None, speculative_draft_model_path=None, speculative_num_steps=5, speculative_eagle_topk=4, speculative_num_draft_tokens=8, speculative_accept_threshold_single=1.0, speculative_accept_threshold_acc=1.0, speculative_token_map=None, enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, disable_radix_cache=False, disable_cuda_graph=True, disable_cuda_graph_padding=False, enable_nccl_nvls=False, disable_outlines_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, disable_overlap_schedule=False, enable_mixed_chunk=False, enable_dp_attention=False, enable_ep_moe=False, enable_torch_compile=False, torch_compile_max_bs=32, cuda_graph_max_bs=160, cuda_graph_bs=None, torchao_config='', enable_nan_detection=False, enable_p2p_check=False, triton_attention_reduce_in_fp32=False, triton_attention_num_kv_splits=8, num_continuous_decode_steps=1, delete_ckpt_after_loading=False, enable_memory_saver=False, allow_auto_truncate=False, enable_custom_logit_processor=False, tool_call_parser=None, enable_hierarchical_cache=False, enable_flashinfer_mla=False, flashinfer_mla_disable_ragged=False, warmups=None, debug_tensor_dump_output_folder=None, debug_tensor_dump_input_file=None, debug_tensor_dump_inject=False)
INFO 03-10 07:20:06 __init__.py:190] Automatically detected platform cuda.
INFO 03-10 07:20:06 __init__.py:190] Automatically detected platform cuda.
INFO 03-10 07:20:06 __init__.py:190] Automatically detected platform cuda.
INFO 03-10 07:20:06 __init__.py:190] Automatically detected platform cuda.
INFO 03-10 07:20:06 __init__.py:190] Automatically detected platform cuda.
2025-03-10 07:20:08,651 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
2025-03-10 07:20:09,018 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
2025-03-10 07:20:09,132 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
2025-03-10 07:20:09,182 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
2025-03-10 07:20:09,197 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
[2025-03-10 07:20:11 TP2] Init torch distributed begin.
[2025-03-10 07:20:11 TP2] world_size=4 rank=2 local_rank=2 distributed_init_method=tcp://127.0.0.1:40547 backend=nccl
[2025-03-10 07:20:12 TP1] Init torch distributed begin.
[2025-03-10 07:20:12 TP1] world_size=4 rank=1 local_rank=1 distributed_init_method=tcp://127.0.0.1:40547 backend=nccl
[2025-03-10 07:20:12 TP0] Init torch distributed begin.
[2025-03-10 07:20:12 TP3] Init torch distributed begin.
[2025-03-10 07:20:12 TP0] world_size=4 rank=0 local_rank=0 distributed_init_method=tcp://127.0.0.1:40547 backend=nccl
[2025-03-10 07:20:12 TP3] world_size=4 rank=3 local_rank=3 distributed_init_method=tcp://127.0.0.1:40547 backend=nccl
[2025-03-10 07:20:13 TP0] Found nccl from library libnccl.so.2
[2025-03-10 07:20:13 TP1] Found nccl from library libnccl.so.2
[2025-03-10 07:20:13 TP0] sglang is using nccl==2.21.5
[2025-03-10 07:20:13 TP1] sglang is using nccl==2.21.5
[2025-03-10 07:20:13 TP2] Found nccl from library libnccl.so.2
[2025-03-10 07:20:13 TP3] Found nccl from library libnccl.so.2
[2025-03-10 07:20:13 TP2] sglang is using nccl==2.21.5
[2025-03-10 07:20:13 TP3] sglang is using nccl==2.21.5
[2025-03-10 07:20:13 TP0] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[2025-03-10 07:20:13 TP1] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[2025-03-10 07:20:13 TP2] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[2025-03-10 07:20:13 TP3] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[2025-03-10 07:20:13 TP0] Binding to tcp://127.0.0.1:56479
[2025-03-10 07:20:13 TP0] Message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1, 2, 3], buffer=<sglang.srt.distributed.device_communicators.shm_broadcast.ShmRingBuffer object at 0x7fc393df31c0>, local_subscribe_port=56479, remote_subscribe_port=None)
[2025-03-10 07:20:13 TP2] Connecting to tcp://127.0.0.1:56479
[2025-03-10 07:20:13 TP1] Connecting to tcp://127.0.0.1:56479
[2025-03-10 07:20:13 TP3] Connecting to tcp://127.0.0.1:56479
[2025-03-10 07:20:14 TP1] Init torch distributed ends. mem usage=0.16 GB
[2025-03-10 07:20:14 TP1] Load weight begin. avail mem=47.01 GB
[2025-03-10 07:20:14 TP3] Init torch distributed ends. mem usage=0.16 GB
[2025-03-10 07:20:14 TP2] Init torch distributed ends. mem usage=0.16 GB
[2025-03-10 07:20:14 TP0] Init torch distributed ends. mem usage=0.16 GB
[2025-03-10 07:20:14 TP3] Load weight begin. avail mem=47.01 GB
[2025-03-10 07:20:14 TP2] Load weight begin. avail mem=47.01 GB
[2025-03-10 07:20:14 TP0] Load weight begin. avail mem=45.96 GB
[2025-03-10 07:20:14 TP1] The following error message 'operation scheduled before its operands' can be ignored.
[2025-03-10 07:20:14 TP3] The following error message 'operation scheduled before its operands' can be ignored.
[2025-03-10 07:20:14 TP2] The following error message 'operation scheduled before its operands' can be ignored.
[2025-03-10 07:20:14 TP0] The following error message 'operation scheduled before its operands' can be ignored.
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
[2025-03-10 07:20:15 TP2] Scheduler hit an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/scheduler.py", line 2255, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/scheduler.py", line 216, in __init__
    self.tp_worker = TpWorkerClass(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/tp_worker.py", line 74, in __init__
    self.model_runner = ModelRunner(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_executor/model_runner.py", line 169, in __init__
    self.load_model()
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_executor/model_runner.py", line 351, in load_model
    self.model = get_model(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_loader/__init__.py", line 22, in get_model
    return loader.load_model(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_loader/loader.py", line 362, in load_model
    model.load_weights(self._get_all_weights(model_config, model))
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/models/qwen2.py", line 393, in load_weights
    for name, loaded_weight in weights:
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_loader/loader.py", line 335, in _get_all_weights
    yield from self._get_weights_iterator(primary_weights)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_loader/loader.py", line 321, in <genexpr>
    return ((source.prefix + name, tensor) for (name, tensor) in weights_iterator)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/model_loader/weight_utils.py", line 440, in safetensors_weights_iterator
    result = safetensors.torch.load_file(st_file, device="cpu")
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
RuntimeError: unable to mmap 6624675384 bytes from file </data/modelsfiles/DeepSeek-R1-Distill-Qwen-7B/model-00002-of-000002.safetensors>: Cannot allocate memory (12)

[2025-03-10 07:20:15] Received sigquit from a child process. It usually means the child failed.
Killed
root@9fe7aac881d5:/# 
```
报错`RuntimeError: unable to mmap 6624675384 bytes from file </data/modelsfiles/DeepSeek-R1-Distill-Qwen-7B/model-00002-of-000002.safetensors>: Cannot allocate memory (12)`

```
root@9fe7aac881d5:/# python3 -m sglang.check_env
2025-03-10 07:24:20,051 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
INFO 03-10 07:24:24 __init__.py:190] Automatically detected platform cuda.
Python: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A40
GPU 0,1,2,3 Compute Capability: 8.6
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 560.35.03
PyTorch: 2.5.1+cu124
sglang: 0.4.3.post4
sgl_kernel: 0.0.3.post6
flashinfer: 0.2.2.post1
triton: 3.1.0
transformers: 4.48.3
torchao: 0.9.0
numpy: 1.26.4
aiohttp: 3.11.13
fastapi: 0.115.11
hf_transfer: 0.1.9
huggingface_hub: 0.29.2
interegular: 0.3.3
modelscope: 1.23.2
orjson: 3.10.15
packaging: 24.2
psutil: 7.0.0
pydantic: 2.10.6
multipart: 0.0.20
zmq: 26.2.1
uvicorn: 0.34.0
uvloop: 0.21.0
vllm: 0.7.2
openai: 1.65.4
tiktoken: 0.9.0
anthropic: 0.49.0
decord: 0.6.0
NVIDIA Topology: 
	GPU0	GPU1	GPU2	GPU3	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NODE	SYS	SYS	0-15,32-47	0		N/A
GPU1	NODE	 X 	SYS	SYS	0-15,32-47	0		N/A
GPU2	SYS	SYS	 X 	NODE	16-31,48-63	1		N/A
GPU3	SYS	SYS	NODE	 X 	16-31,48-63	1		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1048576
root@9fe7aac881d5:/#
```
