### ISSUE TITLE
[Bug] release_memory_occupation not work

### ISSUE THREAD

**Issue by yitianlian** [sgl-project/sglang#4336]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

I find that the function of `release_memory_occupation` (both for engine and server) is not working well as I find it cannot offload the parameter on the GPU device, which leads to OOM.

@fzyzcjy 

![Image](https://github.com/user-attachments/assets/5186675b-62c6-4caa-a1cc-b8f0a2b762d6)

### Reproduction

```python


import time
import unittest

import torch
from transformers import AutoModelForCausalLM

import sglang as sgl
from sglang.test.test_utils import DEFAULT_SMALL_MODEL_NAME_FOR_TEST

def test_release_and_resume_occupation():
    model_name = "Llama-3.2-1B-Instruct"

    engine = sgl.Engine(
        model_path=model_name,
        random_seed=42,
    )


    print(_try_allocate_big_tensor())

    print("release_memory_occupation start")
    t = time.time()
    engine.release_memory_occupation()
    time.sleep(30)


    print(_try_allocate_big_tensor())

    engine.shutdown()


def _try_allocate_big_tensor(size: int = 20_000_000_000):
    try:
        torch.empty((size,), dtype=torch.uint8, device="cuda")
        torch.cuda.empty_cache()
        return True
    except torch.cuda.OutOfMemoryError:
        return False


if __name__=="__main__":
    test_release_and_resume_occupation()
```

### Environment

python 3.11
NVCC: Cuda compilation tools, release 12.4, V12.4.131

**Comment by fzyzcjy** [comment]
Hi, could you please try `Engine(enable_memory_saver=True, ...)` which enables the feature

**Comment by yitianlian** [comment]
Thanks! It solves my problem. Can I also set this in the HTTP server for enabling the offload parameter in the server?

**Comment by yitianlian** [comment]
I find that this arg isn't one of the legal input arguments when launching the server. Maybe I can add it?

**Comment by jhinpan** [comment]
> I find that this arg isn't one of the legal input arguments when launching the server. Maybe I can add it?

cc @fzyzcjy . Is it fine that we quickly raise a PR to add this new input arguments for server?

**Comment by fzyzcjy** [comment]
Looks reasonable! But it seems `--enable-memory-saver` flag is there

**Comment by yitianlian** [comment]
Yes, but we should first run `pip3 install torch-memory-saver` to install the dependency. Then it works.
