### ISSUE TITLE
install SGLang with source, encountered the RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasGemmEx()`

### ISSUE THREAD

**Issue by Sun1Plus** [sgl-project/sglang#4584]
Did anyone encountered the following ERROR? when I was running "tp=16 dp=16", there's an error:

```
[2025-03-19 19:58:45 TP13] TpModelWorkerClient hit an exception: Traceback (most recent call last):
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 112, in forward_thread_func
    self.forward_thread_func_()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 143, in forward_thread_func_
    logits_output, next_token_ids = self.worker.forward_batch_generation(
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/managers/tp_worker.py", line 172, in forward_batch_generation
    logits_output = self.model_runner.forward(forward_batch)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/model_executor/model_runner.py", line 976, in forward
    return self.forward_extend(
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/model_executor/model_runner.py", line 937, in forward_extend
    return self.model.forward(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 1206, in forward
    hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 1166, in forward
    hidden_states, residual = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 1101, in forward
    hidden_states = self.mlp(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 126, in forward
    x, _ = self.down_proj(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/layers/linear.py", line 1277, in forward
    output_parallel = self.quant_method.apply(self, input_parallel, bias=bias_)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/layers/linear.py", line 172, in apply
    return F.linear(x, layer.weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16BF, lda, b, CUDA_R_16BF, ldb, &fbeta, c, CUDA_R_16BF, ldc, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
```

some frame error info:
```
[rank2]:[E319 19:58:45.837235025 ProcessGroupNCCL.cpp:1595] [PG ID 2 PG GUID 3 Rank 2] Process group watchdog thread terminated with exception: CUDA error: misaligned address
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f2a29f6c446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f2a29f166e4 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f2a2a3d6a18 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7f29dfe25726 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7f29dfe2a3f0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7f29dfe31b5a in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f29dfe3361d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7f2a2a4515c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x94ac3 (0x7f2acd9c2ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7f2acda54850 in /usr/lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 2 PG GUID 3 Rank 2] Process group watchdog thread terminated with exception: CUDA error: misaligned address
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

my exec command:
```
GLOO_SOCKET_IFNAME=bond0 TP_SOCKET_IFNAME=bond0 NCCL_SOCKET_IFNAME=bond0 TORCH_USE_CUDA_DSA=1 CUDA_LAUNCH_BLOCKING=1 python3 -m sglang.launch_server --model-path /DATA/disk1/sunyijia/models/DeepSeek-V2-Lite-Chat --trust-remote-code --tp 16 --dp 16 --dist-init-addr 10.42.1.126:5000 --nnodes 2 --node-rank 1 --mem-fraction-static 0.9 --disable-cuda-graph --enable-deepep-moe --enable-dp-attention 
```

I have tried without "--enable-dp-attention" or "--enable-deepep-moe", this error still stays. 

And I have check the idea of [issue 1479](https://github.com/sgl-project/sglang/issues/1479), but I install the sglang with source, it maybe not effective for this situation.

I have encounted this error before, it disappeared when i merged the main branch , so I didn't delve into it, but this time it blocks. 😭

Did anyone encountered the same error?

_Originally posted by @Sun1Plus in https://github.com/sgl-project/sglang/issues/4232#issuecomment-2736446799_

**Comment by anapple-hub** [comment]
similar error. 
I have repo the new branch([f81a27f](https://github.com/sgl-project/sglang/commit/f81a27f65ec1d0f3a7d695031a93ba05fb43de8c)), which includes pr #4499 
I use "tp=16 dp=8 or 16" to run DeepSeekR1 with 2 nodes, each node with 8 * H200, when benchmarking DeepSeekR1 with `request-rate = 1` the following error occurred ( if request-rate and max-concurrency are unset, benchmarking works fine ):
```
[rank14]:[E319 05:16:21.789822241 ProcessGroupNCCL.cpp:1595] [PG ID 2 PG GUID 3 Rank 14] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
```
```
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f0582ab9446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f0582a636e4 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f0582ba5a18 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7f05385c7726 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7f05385cc3f0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7f05385d3b5a in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f05385d561d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7f0582f085c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x94ac3 (0x7f0626094ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7f0626126850 in /usr/lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 2 PG GUID 3 Rank 14] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f0582ab9446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f0582a636e4 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f0582ba5a18 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7f05385c7726 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7f05385cc3f0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7f05385d3b5a in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f05385d561d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7f0582f085c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x94ac3 (0x7f0626094ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7f0626126850 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f0582ab9446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe4271b (0x7f053824271b in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x145c0 (0x7f0582f085c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x94ac3 (0x7f0626094ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x7f0626126850 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Fatal Python error: Aborted

Thread 0x00007ee43dfff640 (most recent call first):
  File "/lpai/volumes/lpai-yharnam-ali-sh/yuxiaoyang/lpex-sglang/python/sglang/srt/managers/scheduler.py", line 1419 in watchdog_thread
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007ee43d7fe640 (most recent call first):
  File "/usr/lib/python3.10/linecache.py", line 72 in checkcache
  File "/usr/lib/python3.10/traceback.py", line 379 in extract
  File "/usr/local/lib/python3.10/dist-packages/exceptiongroup/_formatting.py", line 96 in __init__
  File "/usr/local/lib/python3.10/dist-packages/exceptiongroup/_formatting.py", line 179 in __init__
  File "/usr/lib/python3.10/traceback.py", line 135 in format_exception
  File "/lpai/volumes/lpai-yharnam-ali-sh/yuxiaoyang/lpex-sglang/python/sglang/utils.py", line 34 in get_exception_traceback
  File "/lpai/volumes/lpai-yharnam-ali-sh/yuxiaoyang/lpex-sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 114 in forward_thread_func
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007ef3beb9b640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/usr/local/lib/python3.10/dist-packages/tqdm/_monitor.py", line 60 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f0101fc3640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/usr/local/lib/python3.10/dist-packages/tqdm/_monitor.py", line 60 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f062633e480 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 320 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/lpai/volumes/lpai-yharnam-ali-sh/yuxiaoyang/lpex-sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 174 in resolve_batch_result
  File "/lpai/volumes/lpai-yharnam-ali-sh/yuxiaoyang/lpex-sglang/python/sglang/srt/managers/scheduler_output_processor_mixin.py", line 190 in process_batch_result_decode
  File "/lpai/volumes/lpai-yharnam-ali-sh/yuxiaoyang/lpex-sglang/python/sglang/srt/managers/scheduler.py", line 1266 in process_batch_result
  File "/lpai/volumes/lpai-yharnam-ali-sh/yuxiaoyang/lpex-sglang/python/sglang/srt/managers/scheduler.py", line 543 in event_loop_overlap
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116 in decorate_context
  File "/lpai/volumes/lpai-yharnam-ali-sh/yuxiaoyang/lpex-sglang/python/sglang/srt/managers/scheduler.py", line 1817 in run_scheduler_process
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314 in _bootstrap
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129 in _main
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116 in spawn_main
  File "<string>", line 1 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, psutil._psutil_linux, psutil._psutil_posix, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, zmq.backend.cython._zmq, multidict._multidict, yarl._quoting_c, propcache._helpers_c, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket.mask, aiohttp._websocket.reader_c, frozenlist._frozenlist, uvloop.loop, setproctitle, yaml._yaml, markupsafe._speedups, PIL._imaging, PIL._imagingft, sentencepiece._sentencepiece, msgspec._core, msgpack._cmsgpack, google._upb._message, ray._raylet, cuda_utils, regex._regex, __triton_launcher (total: 52)
```
Strangely, when I set TP=16 and DP=2 or 4, the benchmarking does not throw errors when request-rate or max-concurrency are configured. However, when DP=8 or 16, benchmarking works fine if request-rate and max-concurrency are unset, but errors occur as soon as these parameters are configured. What could be causing this inconsistency?

**Comment by Sun1Plus** [comment]
Could you show the entire command? The error is similar to me, but I don't use the params "request-rate" or "max-concurrency".

Following is my command:
```
GLOO_SOCKET_IFNAME=bond0 TP_SOCKET_IFNAME=bond0 NCCL_SOCKET_IFNAME=bond0 TORCH_USE_CUDA_DSA=1 CUDA_LAUNCH_BLOCKING=1 python3 -m sglang.launch_server --model-path /DATA/disk1/sunyijia/models/DeepSeek-V2-Lite-Chat --trust-remote-code --tp 16 --dp 16 --dist-init-addr 10.42.1.126:5000 --nnodes 2 --node-rank 0 --mem-fraction-static 0.9 --disable-cuda-graph --enable-dp-attention --enable-deepep-moe
```

And I tried several --tp and --dp combinations, acted as [this](https://github.com/sgl-project/sglang/pull/4232#issuecomment-2736767617)

**Comment by anapple-hub** [comment]
@Sun1Plus 
```
# launch server
python3 -m sglang.launch_server --model-pathdeepseek-ai__deepseek-r1 --tp 16 --dp 16 --dist-init-addr ***:2222 --nnodes 2 --node-rank 0 --trust-remote-code --enable-flashinfer-mla --enable-dp-attention --enable-ep-moe --host 0.0.0.0 --port 30000
python3 -m sglang.launch_server --model-path deepseek-ai__deepseek-r1 --tp 16 --dp 16 --dist-init-addr ***:2222 --nnodes 2 --node-rank 1 --trust-remote-code --enable-flashinfer-mla --enable-dp-attention --enable-ep-moe --host 0.0.0.0 --port 30000
# bench_serving
python3 -m sglang.bench_serving --backend sglang --dataset-name random --random-range-ratio 1 --random-input 1024 --random-output 1024 --num-prompt 300 --request-rate 1 --host 127.0.0.1 --port 30000
```
I use commit[f81a27f](https://github.com/sgl-project/sglang/commit/f81a27f65ec1d0f3a7d695031a93ba05fb43de8c)) and  unset `enable-deepep-moe`

**Comment by Sun1Plus** [comment]
let me try your command, set 
```
 --enable-flashinfer-mla --enable-dp-attention --enable-ep-moe 
```

but it still has error "cublasGemmEx"
```
[2025-03-19 22:50:20] INFO:     Uvicorn running on http://127.0.0.1:30000 (Press CTRL+C to quit)
[2025-03-19 22:50:26 DP0 TP0] Prefill batch. #new-seq: 1, #new-token: 8, #cached-token: 0, token usage: 0.00, #running-req: 0, #queue-req: 0, 
2025-03-19 22:50:27,781 - INFO - flashinfer.jit: Loading JIT ops: batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_192_head_dim_vo_128_posenc_0_use_swa_False_use_logits_cap_False_f16qk_False_sm90
2025-03-19 22:51:10,172 - INFO - flashinfer.jit: Finished loading JIT ops: batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_192_head_dim_vo_128_posenc_0_use_swa_False_use_logits_cap_False_f16qk_False_sm90
[2025-03-19 22:51:16 DP6 TP6] TpModelWorkerClient hit an exception: Traceback (most recent call last):
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 112, in forward_thread_func
    self.forward_thread_func_()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 143, in forward_thread_func_
    logits_output, next_token_ids = self.worker.forward_batch_generation(
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/managers/tp_worker.py", line 172, in forward_batch_generation
    logits_output = self.model_runner.forward(forward_batch)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/model_executor/model_runner.py", line 980, in forward
    return self.forward_idle(forward_batch)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/model_executor/model_runner.py", line 957, in forward_idle
    return self.model.forward(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 1206, in forward
    hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 1166, in forward
    hidden_states, residual = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 1101, in forward
    hidden_states = self.mlp(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 126, in forward
    x, _ = self.down_proj(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/layers/linear.py", line 1277, in forward
    output_parallel = self.quant_method.apply(self, input_parallel, bias=bias_)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/layers/linear.py", line 172, in apply
    return F.linear(x, layer.weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16BF, lda, b, CUDA_R_16BF, ldb, &fbeta, c, CUDA_R_16BF, ldc, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
```


My env is cuda-12.2, does this cuda version is incompatible some lib?

**Comment by ch-wan** [comment]
@Sun1Plus I was trying to reproduce the error you reported in https://github.com/sgl-project/sglang/pull/4232#issuecomment-2736767617 with DP4TP8, but did not confront any issue. Here is the command I was using. I will test it under a multi-node setting later. Could you please share the detailed settings of your error?

```
python3 -m sglang.launch_server --model-path deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct --trust-remote-code --tp 8 --dp 4 --enable-dp-attention --disable-cuda-graph
python3 -m sglang.bench_serving --backend sglang --dataset-name random --num-prompts 600 --random-input 180 --random-output 400 --request-rate 40
```

```
# tp != dp is not recommended under `--enable-deepep-moe` at this moment
python3 -m sglang.launch_server --model-path deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct --trust-remote-code --tp 8 --dp 4 --enable-dp-attention --disable-cuda-graph --enable-deepep-moe
python3 -m sglang.bench_serving --backend sglang --dataset-name random --num-prompts 600 --random-input 180 --random-output 400 --request-rate 40
```

**Comment by Sun1Plus** [comment]
@ch-wan It's OK in single-node, both DP8TP8 and DP4TP8, the error only appeared on two-node setting.

My env detailed setting:
```
hardware:
  two node, every node has 8 * H100
in-docker system version:
  Ubuntu 22.04
  cuda_12.4.r12.4/compiler.33961263_0
  python 3.10
pip:
  torch          2.5.1
  sgl-kernel  0.0.5.post3
  sglang        install with source
  flashinfer-python    0.2.3+cu121torch2.5
```

two node exec command:
node1:
```
GLOO_SOCKET_IFNAME=bond0 TP_SOCKET_IFNAME=bond0 NCCL_SOCKET_IFNAME=bond0 TORCH_USE_CUDA_DSA=1 CUDA_LAUNCH_BLOCKING=1 python3 -m sglang.launch_server --model-path /DATA/disk1/sunyijia/models/DeepSeek-V2-Lite-Chat --trust-remote-code --tp 16 --dp 16 --dist-init-addr 10.42.1.126:5000 --nnodes 2 --node-rank 0 --mem-fraction-static 0.9 --disable-cuda-graph --enable-dp-attention --enable-deepep-moe
```

node2:
```
GLOO_SOCKET_IFNAME=bond0 TP_SOCKET_IFNAME=bond0 NCCL_SOCKET_IFNAME=bond0 TORCH_USE_CUDA_DSA=1 CUDA_LAUNCH_BLOCKING=1 python3 -m sglang.launch_server --model-path /DATA/disk1/sunyijia/models/DeepSeek-V2-Lite-Chat --trust-remote-code --tp 16 --dp 16 --dist-init-addr 10.42.1.126:5000 --nnodes 2 --node-rank 1 --mem-fraction-static 0.9 --disable-cuda-graph --enable-dp-attention --enable-deepep-moe
```


Detailed log and Error:
```
[2025-03-20 10:46:10] INFO:     127.0.0.1:56108 - "GET /get_model_info HTTP/1.1" 200 OK
[2025-03-20 10:46:10 DP0 TP0] Prefill batch. #new-seq: 1, #new-token: 7, #cached-token: 0, token usage: 0.00, #running-req: 0, #queue-req: 0, 
[2025-03-20 10:46:14 DP2 TP2] TpModelWorkerClient hit an exception: Traceback (most recent call last):
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 112, in forward_thread_func
    self.forward_thread_func_()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 143, in forward_thread_func_
    logits_output, next_token_ids = self.worker.forward_batch_generation(
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/managers/tp_worker.py", line 172, in forward_batch_generation
    logits_output = self.model_runner.forward(forward_batch)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/model_executor/model_runner.py", line 980, in forward
    return self.forward_idle(forward_batch)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/model_executor/model_runner.py", line 957, in forward_idle
    return self.model.forward(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 1206, in forward
    hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 1166, in forward
    hidden_states, residual = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 1101, in forward
    hidden_states = self.mlp(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/models/deepseek_v2.py", line 126, in forward
    x, _ = self.down_proj(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/layers/linear.py", line 1277, in forward
    output_parallel = self.quant_method.apply(self, input_parallel, bias=bias_)
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/layers/linear.py", line 172, in apply
    return F.linear(x, layer.weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16BF, lda, b, CUDA_R_16BF, ldb, &fbeta, c, CUDA_R_16BF, ldc, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/DATA/disk1/sunyijia/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 111, in forward_thread_func
    with torch.get_device_module(self.device).stream(self.forward_stream):
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 595, in __exit__
    torch.cuda.set_stream(self.src_prev_stream)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 962, in _patched_set_stream
    prev_set_stream(stream)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 636, in set_stream
    _set_stream_by_id(
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 618, in _set_stream_by_id
    torch._C._cuda_setStream(
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```


### something latest
I used two node DP2TP16 to debug, then I located the error, it occurs on DeepseekV2MLP-SiluAndMul, then calling sgl_kernel silu_and mul(), following is detailed code: 
```
def silu_and_mul(input: torch.Tensor, out: torch.Tensor = None) -> torch.Tensor:
    if input.shape[-1] * input.dtype.itemsize % 16 != 0:
        raise ValueError("The pointers must be multiple of 16 bytes.")
    if out is not None:
        _check_shape(input, out)
    else:
        out = torch.empty(
            input.shape[:-1] + (input.shape[-1] // 2,),
            device=input.device,
            dtype=input.dtype,
        )
    torch.ops.sgl_kernel.silu_and_mul(out, input, get_cuda_stream())
    return out
``` 

After exec `torch.ops.sgl_kernel.silu_and_mul(out, input, get_cuda_stream())`, output doesn't have data, so the latter cublasGemmEx trigger Error.

**Comment by Sun1Plus** [comment]
Now, error occurs on this function, so I use torch native process to replace cuda process temporarily, then it runs ok.

<img width="810" alt="Image" src="https://github.com/user-attachments/assets/c2adb77e-14da-40ec-86a4-317d9526f173" />

I will delve into the detailed error later, then add to this comment.
If someone encounter the same question, hope it a bit helpful.

**Comment by zhangml** [comment]
I encountered exactly the same error when running 2-node H800 in a RoCE environment. @ch-wan @Sun1Plus

**Comment by Sun1Plus** [comment]
@zhangmln Hi, do you resolve the problem? I didn't use RoCE env, if you still have the problem, could you list the detailed output, maybe I can provide some support.

**Comment by ch-wan** [comment]
I reproduced the same issue for DeepSeek-Coder-V2-Lite-Instruct, but the issue disappeared for DeepSeek-V3.

**Comment by zhangml** [comment]
> @zhangmln Hi, do you resolve the problem? I didn't use RoCE env, if you still have the problem, could you list the detailed output, maybe I can provide some support.

The error is exactly the same as yours. After updating to the latest code, I no longer encounter this problem.

**Comment by cjy0x** [comment]
I met the same problem when I run qwen3.5 9b using sglang v0.5.10
