### ISSUE TITLE
[Bug] ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by githust66** [sgl-project/sglang#4778]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

There are no CUDA-related libraries in the rocm environment, but the SGLANG 0.4.4.post1 version will report an error,，The following error message is from having the sgl_kernel module installed. python -m sglang.check_env also reports an error. If you don't install sgl_kernel, an error will be reported: Failed to import from custom_ar with ModuleNotFoundError("No module named 'sgl_kernel'")

**error info:**
[2025-03-26 11:03:17 TP0] Failed to import from custom_ar with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')
[W326 11:03:17.247903641 HIPAllocatorConfig.h:29] Warning: expandable_segments not supported on this platform (function operator())
[2025-03-26 11:03:17 TP0] Init torch distributed ends. mem usage=0.01 GB
[2025-03-26 11:03:17 TP0] Load weight begin. avail mem=17.52 GB
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[2025-03-26 11:03:17 TP0] Scheduler hit an exception: Traceback (most recent call last):
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1748, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 218, in __init__
    self.tp_worker = TpWorkerClass(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 74, in __init__
    self.model_runner = ModelRunner(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 166, in __init__
    self.initialize(min_per_gpu_memory)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 176, in initialize
    self.load_model()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 358, in load_model
    monkey_patch_isinstance_for_vllm_base_layer()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/srt/layers/quantization/__init__.py", line 202, in monkey_patch_isinstance_for_vllm_base_layer
    from sglang.srt.layers.moe.fused_moe_triton.layer import FusedMoE as PatchedFusedMoE
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/srt/layers/moe/fused_moe_triton/__init__.py", line 4, in <module>
    import sglang.srt.layers.moe.fused_moe_triton.fused_moe  # noqa
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/srt/layers/moe/fused_moe_triton/fused_moe.py", line 51, in <module>
    from sgl_kernel import moe_align_block_size as sgl_moe_align_block_size
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sgl_kernel/__init__.py", line 12, in <module>
    from sgl_kernel import common_ops
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

[2025-03-26 11:03:17] Received sigquit from a child process. It usually means the child failed.
2025-03-26 11:03:17,945 xinference.core.worker 97103 ERROR    Failed to load model qwen2.5-instruct-0
Traceback (most recent call last):
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/worker.py", line 926, in launch_builtin_model
    await model_ref.load()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 667, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 466, in load
    self._model.load()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/llm/sglang/core.py", line 217, in load
    self._engine = sgl.Runtime(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/api.py", line 38, in Runtime
    return Runtime(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sglang/lang/backend/runtime_endpoint.py", line 392, in __init__
    raise RuntimeError(
RuntimeError: [address=0.0.0.0:35787, pid=99796] Initialization failed. Please see the error messages above.

### Reproduction

qwen2.5-instruct-7B

### Environment

(xinf) root@DESKTOP-ESRGKIB:~/.xinference/logs#  python -m sglang.check_env
is_rocm: True
INFO 03-26 11:12:30 __init__.py:207] Automatically detected platform rocm.
WARNING 03-26 11:12:30 rocm.py:33] `fork` method is not supported by ROCm. VLLM_WORKER_MULTIPROC_METHOD is overridden to `spawn` instead.
Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
ROCM available: True
GPU 0: AMD Radeon RX 7900 XT
GPU 0 Compute Capability: 11.0
ROCM_HOME: /opt/rocm
HIPCC: HIP version: 6.3.42134-a9a80e791
ROCM Driver Version: 
PyTorch: 2.8.0.dev20250325+rocm6.3
sglang: 0.4.4.post1
sgl_kernel: Module Not Found
flashinfer: Module Not Found
triton: 3.3.0
transformers: 4.48.3
torchao: Module Not Found
numpy: 1.26.4
aiohttp: 3.11.14
fastapi: 0.115.12
hf_transfer: Module Not Found
huggingface_hub: 0.29.3
interegular: 0.3.3
modelscope: 1.24.0
orjson: 3.10.16
packaging: 24.2
psutil: 7.0.0
pydantic: 2.10.6
multipart: 0.0.20
zmq: 26.3.0
uvicorn: 0.34.0
uvloop: 0.21.0
vllm: 0.7.3.dev0+g0408efc6.d20250309
openai: 1.68.2
tiktoken: 0.9.0
anthropic: Module Not Found
litellm: Module Not Found
decord: 0.6.0
AMD Topology: 

Hypervisor vendor: Microsoft
ulimit soft: 1024

**Comment by githust66** [comment]
>>> import sgl_kernel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sgl_kernel/__init__.py", line 12, in <module>
    from sgl_kernel import common_ops
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by githust66** [comment]
>>> import sgl_kernel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/sgl_kernel/__init__.py", line 12, in <module>
    from sgl_kernel import common_ops
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by wplf** [comment]
Maybe try to add $LD_LIBRARY_PATH will help you

1. ` find /usr/local/  -name "libcuda.so*" `
2.   get the directory and  `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"THE_PATH_YOU_JUST_FIND"`

Example:
```
$ find /usr/local/  -name "libcuda.so*" 
/usr/local/cuda-12.1/compat/libcuda.so
/usr/local/cuda-12.1/compat/libcuda.so.1
/usr/local/cuda-12.1/compat/libcuda.so.530.30.02
/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-12.4/targets/x86_64-linux/lib/stubs/libcuda.so
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.1/compat/
```

**Comment by githust66** [comment]
> 也许尝试添加 $LD_LIBRARY_PATH 会对您有所帮助
> 
> 1. `find /usr/local/  -name "libcuda.so*"`
> 2. 获取目录和 `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"THE_PATH_YOU_JUST_FIND"`
> 
> 例：
> 
> ```
> $ find /usr/local/  -name "libcuda.so*" 
> /usr/local/cuda-12.1/compat/libcuda.so
> /usr/local/cuda-12.1/compat/libcuda.so.1
> /usr/local/cuda-12.1/compat/libcuda.so.530.30.02
> /usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/libcuda.so
> /usr/local/cuda-12.4/targets/x86_64-linux/lib/stubs/libcuda.so
> $ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.1/compat/
> ```

Thanks, but I'm in the ROCm environment and there is no CUDA.

**Comment by whyisverysmart** [comment]
Hi~ I encountered the same problem. Did you solve it?

**Comment by githust66** [comment]
> Hi~ I encountered the same problem. Did you solve it?

Didn't work out

**Comment by githust66** [comment]
After upgrading to the latest version, the problem has disappeared ，But the following problem has occurred.
https://github.com/sgl-project/sglang/issues/5494
