### ISSUE TITLE
[Bug] `init_weights_update_group` triggers `CUDA error: invalid device ordinal`

### ISSUE THREAD

**Issue by yangky11** [sgl-project/sglang#5077]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

I'm trying to use `update_weights_from_distributed` in my RL workflow but got an error when trying to initialize the process group. Below is a simplified version of my program  for reproducing the error:

test_init_weights_update_group.py:
```python
import os

os.environ["RAY_DEDUP_LOGS"] = "0"
import ray
import requests
from sglang.srt.utils import init_custom_process_group
from sglang.utils import launch_server_cmd, wait_for_server

SGLANG_SERVER_PORT = 30000


@ray.remote(num_cpus=2, num_gpus=1)
class SGLangWorker:
    def initialize(self) -> None:
        launch_server_cmd(
            "python -m sglang.launch_server --model-path Qwen/Qwen2.5-3B-Instruct",
            port=SGLANG_SERVER_PORT,
        )
        wait_for_server(f"http://localhost:{SGLANG_SERVER_PORT}")
        assert requests.get(
            f"http://localhost:{SGLANG_SERVER_PORT}/health_generate"
        ).ok

    def init_weights_update_group(self) -> None:
        print("SGLangWorker:init_weights_update_group")
        res = requests.post(
            f"http://localhost:{SGLANG_SERVER_PORT}/init_weights_update_group",
            json={
                "master_address": "localhost",
                "master_port": 30001,
                "rank_offset": 1,
                "world_size": 2,
                "group_name": "test_group",
                "backend": "nccl",
            },
        )
        print(res)
        print(res.text)
        assert res.ok


@ray.remote(num_cpus=2, num_gpus=1)
class PyTorchWorker:
    def initialize(self) -> None:
        os.environ["NCCL_CUMEM_ENABLE"] = "0"
        os.environ["NCCL_NVLS_ENABLE"] = "0"

    def init_weights_update_group(self) -> None:
        print("PyTorchWorker:init_weights_update_group")
        init_custom_process_group(
            backend="nccl",
            init_method=f"tcp://localhost:30001",
            rank=0,
            world_size=2,
            group_name="test_group",
        )


if __name__ == "__main__":
    ray.init(address="local")
    sglang = SGLangWorker.remote()
    pytorch = PyTorchWorker.remote()
    print("Initializing workers...")
    ray.get([sglang.initialize.remote(), pytorch.initialize.remote()])
    print("Initializing weights update group...")
    ray.get(
        [
            sglang.init_weights_update_group.remote(),
            pytorch.init_weights_update_group.remote(),
        ]
    )
```

Running it (on a node with at least two GPUs) leads to the following error:
```
(wei) kaiyuy@learnfair6025:~/WEI/wei-agent$ python test_init_weights_update_group.py 
2025-04-05 03:19:45,261	INFO worker.py:1832 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
Initializing workers...
(SGLangWorker pid=1107016) INFO 04-05 03:19:58 __init__.py:190] Automatically detected platform cuda.
(SGLangWorker pid=1107016) [2025-04-05 03:20:01] server_args=ServerArgs(model_path='Qwen/Qwen2.5-3B-Instruct', tokenizer_path='Qwen/Qwen2.5-3B-Instruct', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', trust_remote_code=False, dtype='auto', kv_cache_dtype='auto', quantization=None, quantization_param_path=None, context_length=None, device='cuda', served_model_name='Qwen/Qwen2.5-3B-Instruct', chat_template=None, completion_template=None, is_embedding=False, revision=None, host='127.0.0.1', port=30000, mem_fraction_static=0.88, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='fcfs', schedule_conservativeness=1.0, cpu_offload_gb=0, page_size=1, tp_size=1, stream_interval=1, stream_output=False, random_seed=37573141, constrained_json_whitespace_pattern=None, watchdog_timeout=300, dist_timeout=None, download_dir=None, base_gpu_id=0, gpu_id_step=1, log_level='info', log_level_http=None, log_requests=False, log_requests_level=0, show_time_cost=False, enable_metrics=False, decode_log_interval=40, api_key=None, file_storage_path='sglang_storage', enable_cache_report=False, reasoning_parser=None, dp_size=1, load_balance_method='round_robin', ep_size=1, dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', lora_paths=None, max_loras_per_batch=8, lora_backend='triton', attention_backend='flashinfer', sampling_backend='flashinfer', grammar_backend='xgrammar', speculative_algorithm=None, speculative_draft_model_path=None, speculative_num_steps=None, speculative_eagle_topk=None, speculative_num_draft_tokens=None, speculative_accept_threshold_single=1.0, speculative_accept_threshold_acc=1.0, speculative_token_map=None, enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, disable_radix_cache=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, enable_nccl_nvls=False, disable_outlines_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, disable_overlap_schedule=False, enable_mixed_chunk=False, enable_dp_attention=False, enable_ep_moe=False, enable_deepep_moe=False, deepep_mode=None, enable_torch_compile=False, torch_compile_max_bs=32, cuda_graph_max_bs=160, cuda_graph_bs=None, torchao_config='', enable_nan_detection=False, enable_p2p_check=False, triton_attention_reduce_in_fp32=False, triton_attention_num_kv_splits=8, num_continuous_decode_steps=1, delete_ckpt_after_loading=False, enable_memory_saver=False, allow_auto_truncate=False, enable_custom_logit_processor=False, tool_call_parser=None, enable_hierarchical_cache=False, hicache_ratio=2.0, enable_flashinfer_mla=False, enable_flashmla=False, flashinfer_mla_disable_ragged=False, warmups=None, debug_tensor_dump_output_folder=None, debug_tensor_dump_input_file=None, debug_tensor_dump_inject=False, disaggregation_mode='null', disaggregation_bootstrap_port=8998)
(SGLangWorker pid=1107016) INFO 04-05 03:20:08 __init__.py:190] Automatically detected platform cuda.
(SGLangWorker pid=1107016) INFO 04-05 03:20:08 __init__.py:190] Automatically detected platform cuda.
(SGLangWorker pid=1107016) [2025-04-05 03:20:12 TP0] Init torch distributed begin.
(SGLangWorker pid=1107016) [2025-04-05 03:20:12 TP0] Init torch distributed ends. mem usage=0.00 GB
(SGLangWorker pid=1107016) [2025-04-05 03:20:12 TP0] Load weight begin. avail mem=78.73 GB
(SGLangWorker pid=1107016) [2025-04-05 03:20:13 TP0] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:00<00:00,  2.05it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.18it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.16it/s]
(SGLangWorker pid=1107016) 
(SGLangWorker pid=1107016) [2025-04-05 03:20:15 TP0] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=72.77 GB, mem usage=5.96 GB.
(SGLangWorker pid=1107016) [2025-04-05 03:20:15 TP0] KV Cache is allocated. #tokens: 1844428, K size: 31.66 GB, V size: 31.66 GB
(SGLangWorker pid=1107016) [2025-04-05 03:20:15 TP0] Memory pool end. avail mem=8.81 GB
(SGLangWorker pid=1107016) [2025-04-05 03:20:15 TP0] Capture cuda graph begin. This can take up to several minutes. avail mem=8.19 GB
Capturing batches (avail_mem=8.16 GB):   0%|          | 0/23 [00:00<?, ?it/s]
Capturing batches (avail_mem=7.96 GB):   4%|▍         | 1/23 [00:00<00:20,  1.06it/s]
Capturing batches (avail_mem=7.85 GB):   9%|▊         | 2/23 [00:01<00:11,  1.82it/s]
Capturing batches (avail_mem=7.76 GB):  13%|█▎        | 3/23 [00:01<00:08,  2.39it/s]
Capturing batches (avail_mem=7.66 GB):  17%|█▋        | 4/23 [00:01<00:06,  2.86it/s]
Capturing batches (avail_mem=7.58 GB):  22%|██▏       | 5/23 [00:01<00:05,  3.18it/s]
Capturing batches (avail_mem=7.49 GB):  26%|██▌       | 6/23 [00:02<00:05,  3.37it/s]
Capturing batches (avail_mem=7.42 GB):  30%|███       | 7/23 [00:02<00:04,  3.54it/s]
Capturing batches (avail_mem=7.33 GB):  35%|███▍      | 8/23 [00:02<00:04,  3.65it/s]
Capturing batches (avail_mem=7.27 GB):  39%|███▉      | 9/23 [00:02<00:03,  3.76it/s]
Capturing batches (avail_mem=7.20 GB):  43%|████▎     | 10/23 [00:03<00:03,  3.66it/s]
Capturing batches (avail_mem=7.15 GB):  48%|████▊     | 11/23 [00:03<00:03,  3.80it/s]
Capturing batches (avail_mem=7.08 GB):  52%|█████▏    | 12/23 [00:03<00:02,  3.77it/s]
Capturing batches (avail_mem=7.08 GB):  57%|█████▋    | 13/23 [00:04<00:02,  3.70it/s]
Capturing batches (avail_mem=7.02 GB):  61%|██████    | 14/23 [00:04<00:02,  3.76it/s]
Capturing batches (avail_mem=6.99 GB):  65%|██████▌   | 15/23 [00:04<00:02,  3.78it/s]
Capturing batches (avail_mem=6.94 GB):  70%|██████▉   | 16/23 [00:04<00:01,  3.88it/s]
Capturing batches (avail_mem=6.93 GB):  74%|███████▍  | 17/23 [00:05<00:01,  3.95it/s]
Capturing batches (avail_mem=6.89 GB):  78%|███████▊  | 18/23 [00:05<00:01,  3.95it/s]
Capturing batches (avail_mem=6.87 GB):  83%|████████▎ | 19/23 [00:05<00:01,  3.98it/s]
Capturing batches (avail_mem=6.84 GB):  87%|████████▋ | 20/23 [00:05<00:00,  3.90it/s]
Capturing batches (avail_mem=6.84 GB):  91%|█████████▏| 21/23 [00:06<00:00,  3.88it/s]
Capturing batches (avail_mem=6.81 GB):  96%|█████████▌| 22/23 [00:06<00:00,  3.88it/s]
Capturing batches (avail_mem=6.81 GB): 100%|██████████| 23/23 [00:06<00:00,  3.47it/s]
(SGLangWorker pid=1107016) [2025-04-05 03:20:22 TP0] Capture cuda graph end. Time elapsed: 6.65 s. avail mem=6.80 GB. mem usage=1.39 GB.
(SGLangWorker pid=1107016) [2025-04-05 03:20:22 TP0] max_total_num_tokens=1844428, chunked_prefill_size=8192, max_prefill_tokens=16384, max_running_requests=4097, context_len=32768
(SGLangWorker pid=1107016) [2025-04-05 03:20:23] INFO:     Started server process [1114234]
(SGLangWorker pid=1107016) [2025-04-05 03:20:23] INFO:     Waiting for application startup.
(SGLangWorker pid=1107016) [2025-04-05 03:20:23] INFO:     Application startup complete.
(SGLangWorker pid=1107016) [2025-04-05 03:20:23] INFO:     Uvicorn running on http://127.0.0.1:30000 (Press CTRL+C to quit)
(SGLangWorker pid=1107016) [2025-04-05 03:20:23] INFO:     127.0.0.1:37096 - "GET /v1/models HTTP/1.1" 200 OK
(SGLangWorker pid=1107016) [2025-04-05 03:20:24] INFO:     127.0.0.1:37112 - "GET /get_model_info HTTP/1.1" 200 OK
(SGLangWorker pid=1107016) [2025-04-05 03:20:24 TP0] Prefill batch. #new-seq: 1, #new-token: 6, #cached-token: 0, token usage: 0.00, #running-req: 0, #queue-req: 0, 
(SGLangWorker pid=1107016) [2025-04-05 03:20:26] INFO:     127.0.0.1:37116 - "POST /generate HTTP/1.1" 200 OK
(SGLangWorker pid=1107016) [2025-04-05 03:20:26] The server is fired up and ready to roll!
(SGLangWorker pid=1107016) 
(SGLangWorker pid=1107016) 
(SGLangWorker pid=1107016)                     NOTE: Typically, the server runs in a separate terminal.
(SGLangWorker pid=1107016)                     In this notebook, we run the server and notebook code together, so their outputs are combined.
(SGLangWorker pid=1107016)                     To improve clarity, the server logs are displayed in the original black color, while the notebook outputs are highlighted in blue.
(SGLangWorker pid=1107016)                     We are running those notebooks in a CI parallel environment, so the throughput is not representative of the actual performance.
(SGLangWorker pid=1107016)                     
(SGLangWorker pid=1107016) [2025-04-05 03:20:36 TP0] Prefill batch. #new-seq: 1, #new-token: 1, #cached-token: 0, token usage: 0.00, #running-req: 0, #queue-req: 0, 
(SGLangWorker pid=1107016) [2025-04-05 03:20:37] INFO:     127.0.0.1:34074 - "GET /health_generate HTTP/1.1" 200 OK
Initializing weights update group...
Traceback (most recent call last):
  File "/private/home/kaiyuy/WEI/wei-agent/test_init_weights_update_group.py", line 66, in <module>
    ray.get(
  File "/private/home/kaiyuy/miniconda3/envs/wei/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/private/home/kaiyuy/miniconda3/envs/wei/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/kaiyuy/miniconda3/envs/wei/lib/python3.12/site-packages/ray/_private/worker.py", line 2771, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/kaiyuy/miniconda3/envs/wei/lib/python3.12/site-packages/ray/_private/worker.py", line 919, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::SGLangWorker.init_weights_update_group() (pid=1107016, ip=100.96.180.136, actor_id=0709fc6eb52d08f5573333c701000000, repr=<test_init_weights_update_group.SGLangWorker object at 0x7f07c441a180>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/kaiyuy/WEI/wei-agent/test_init_weights_update_group.py", line 39, in init_weights_update_group
    assert res.ok
           ^^^^^^
AssertionError
(PyTorchWorker pid=1107021) PyTorchWorker:init_weights_update_group
(SGLangWorker pid=1107016) SGLangWorker:init_weights_update_group
(SGLangWorker pid=1107016) [2025-04-05 03:20:37 TP0] init custom process group: master_address=localhost, master_port=30001, rank_offset=1, rank=1, world_size=2, group_name=test_group, backend=nccl
(SGLangWorker pid=1107016) [2025-04-05 03:20:37 TP0] Failed to initialize custom process group: CUDA error: invalid device ordinal
(SGLangWorker pid=1107016) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(SGLangWorker pid=1107016) For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(SGLangWorker pid=1107016) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(SGLangWorker pid=1107016) .
(SGLangWorker pid=1107016) [2025-04-05 03:20:37] INFO:     127.0.0.1:60992 - "POST /init_weights_update_group HTTP/1.1" 400 Bad Request
(SGLangWorker pid=1107016) <Response [400]>
(SGLangWorker pid=1107016) {"success":false,"message":"Failed to initialize custom process group: CUDA error: invalid device ordinal\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n."}
```

I'm not sure is this is the correct way of using `init_weights_update_group` and `update_weights_from_distributed`. I'm trying to follow https://github.com/sgl-project/sglang/blob/main/test/srt/test_update_weights_from_distributed.py but may have missed something. Any guidance or pointers are appreciated!

### Reproduction

See above.

### Environment

```
Python: 3.12.9 | packaged by Anaconda, Inc. | (main, Feb  6 2025, 18:56:27) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A100-SXM4-80GB
GPU 0,1,2,3 Compute Capability: 8.0
CUDA_HOME: /public/apps/cuda/12.2.0
NVCC: Cuda compilation tools, release 12.2, V12.2.91
CUDA Driver Version: 550.144.03
PyTorch: 2.5.1+cu121
sglang: 0.4.4.post3
sgl_kernel: 0.0.5.post4
flashinfer: Module Not Found
triton: 3.1.0
transformers: 4.50.0
torchao: 0.9.0
numpy: 1.26.4
aiohttp: 3.11.13
fastapi: 0.115.11
hf_transfer: 0.1.9
huggingface_hub: 0.29.3
interegular: 0.3.3
modelscope: 1.23.2
orjson: 3.10.15
outlines: 0.1.11
packaging: 24.2
psutil: 7.0.0
pydantic: 2.10.6
multipart: Module Not Found
zmq: Module Not Found
uvicorn: 0.34.0
uvloop: 0.21.0
vllm: 0.7.2
xgrammar: 0.1.17
openai: 1.66.3
tiktoken: 0.9.0
anthropic: 0.49.0
litellm: 1.63.11
decord: 0.6.0
NVIDIA Topology: 
	GPU0	GPU1	GPU2	GPU3	NIC0	NIC1	NIC2	NIC3	NIC4	NIC5	NIC6	NIC7	NIC8	NIC9	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV12	NV12	NV12	PXB	PXB	NODE	NODE	SYS	SYS	SYS	SYS	NODE	SYS	0-39	0		N/A
GPU1	NV12	 X 	NV12	NV12	PXB	PXB	NODE	NODE	SYS	SYS	SYS	SYS	NODE	SYS	0-39	0		N/A
GPU2	NV12	NV12	 X 	NV12	NODE	NODE	PXB	PXB	SYS	SYS	SYS	SYS	NODE	SYS	0-39	0		N/A
GPU3	NV12	NV12	NV12	 X 	SYS	SYS	SYS	SYS	PXB	PXB	NODE	NODE	SYS	NODE		1		N/A
NIC0	PXB	PXB	NODE	SYS	 X 	PXB	NODE	NODE	SYS	SYS	SYS	SYS	NODE	SYS				
NIC1	PXB	PXB	NODE	SYS	PXB	 X 	NODE	NODE	SYS	SYS	SYS	SYS	NODE	SYS				
NIC2	NODE	NODE	PXB	SYS	NODE	NODE	 X 	PXB	SYS	SYS	SYS	SYS	NODE	SYS				
NIC3	NODE	NODE	PXB	SYS	NODE	NODE	PXB	 X 	SYS	SYS	SYS	SYS	NODE	SYS				
NIC4	SYS	SYS	SYS	PXB	SYS	SYS	SYS	SYS	 X 	PXB	NODE	NODE	SYS	NODE				
NIC5	SYS	SYS	SYS	PXB	SYS	SYS	SYS	SYS	PXB	 X 	NODE	NODE	SYS	NODE				
NIC6	SYS	SYS	SYS	NODE	SYS	SYS	SYS	SYS	NODE	NODE	 X 	PXB	SYS	NODE				
NIC7	SYS	SYS	SYS	NODE	SYS	SYS	SYS	SYS	NODE	NODE	PXB	 X 	SYS	NODE				
NIC8	NODE	NODE	NODE	SYS	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	 X 	SYS				
NIC9	SYS	SYS	SYS	NODE	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	SYS	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: ibp18s0
  NIC1: ibp21s0
  NIC2: ibp69s0
  NIC3: ibp94s0
  NIC4: ibp162s0
  NIC5: ibp165s0
  NIC6: ibp226s0
  NIC7: ibp229s0
  NIC8: rocep49s0
  NIC9: rocep129s0


ulimit soft: 500000
```

**Comment by yangky11** [comment]
Never mind. I resolved this issue.

**Comment by tyler-griggs** [comment]
Hi Kaiyu, I'm having a similar issue -- how did you resolve this?

**Comment by yangky11** [comment]
I fixed a small bug related to this but don't have the bandwidth to go through a PR review process now: https://github.com/yangky11/sglang.

**Comment by tyler-griggs** [comment]
Thanks for sharing!

**Comment by tyler-griggs** [comment]
By the way, it looks like the barrier was removed here: https://github.com/sgl-project/sglang/commit/44a3783d13146ba106a88c44be89518698ef6065

**Comment by yangky11** [comment]
Ok. Then my fix is probably not needed.
