### ISSUE TITLE
[Bug]  shared memory (/dev/shm) error when using FA3 with meta-llama/Llama-3.1-70B-Instruct on a multi-GPU host

### ISSUE THREAD

**Issue by harrisonlimh** [sgl-project/sglang#5096]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

Hello, 

I am trying to run `meta-llama/Llama-3.1-70B-Instruct` with SGLang's FA3  setting and running into /dev/shm error, when running on a multi-gpu host (8xH100).

Would anyone have seen the issue? 

Error log

```
ERROR 2025-04-05T00:01:19.509514570Z ./entrypoint.sh: line 48: 28 Killed python3 -m sglang.launch_server --host 0.0.0.0 --port ...
ERROR 2025-04-05T00:01:19.209237575Z [2025-04-05 00:01:19] Received sigquit from a child process. It usually means the child failed.
ERROR 2025-04-05T00:01:19.209112405Z {}
ERROR 2025-04-05T00:01:19.209110975Z Error while creating shared memory segment /dev/shm/nccl-lNPZ0f (size 7340384)
ERROR 2025-04-05T00:01:19.209109067Z Last error:
ERROR 2025-04-05T00:01:19.209107160Z ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.
ERROR 2025-04-05T00:01:19.209104776Z torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:317, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.21.5
ERROR 2025-04-05T00:01:19.209101915Z work = group.allreduce([tensor], opts)
ERROR 2025-04-05T00:01:19.209100008Z File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2501, in all_reduce
ERROR 2025-04-05T00:01:19.209097862Z return func(*args, **kwargs)
ERROR 2025-04-05T00:01:19.209095001Z File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
ERROR 2025-04-05T00:01:19.209093332Z torch.distributed.all_reduce(tensor, op=torch.distributed.ReduceOp.MIN)
ERROR 2025-04-05T00:01:19.209090709Z File "/sgl-workspace/sglang/python/sglang/srt/utils.py", line 315, in get_available_gpu_memory
ERROR 2025-04-05T00:01:19.209086656Z min_per_gpu_memory = get_available_gpu_memory(
ERROR 2025-04-05T00:01:19.209083795Z File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 328, in init_torch_distributed
ERROR 2025-04-05T00:01:19.209080696Z min_per_gpu_memory = self.init_torch_distributed()
ERROR 2025-04-05T00:01:19.209076881Z File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 169, in __init__
ERROR 2025-04-05T00:01:19.209074258Z self.model_runner = ModelRunner(
ERROR 2025-04-05T00:01:19.209071636Z File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 74, in __init__
ERROR 2025-04-05T00:01:19.209069252Z self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
ERROR 2025-04-05T00:01:19.209066629Z File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
ERROR 2025-04-05T00:01:19.209064722Z self.tp_worker = TpWorkerClass(
ERROR 2025-04-05T00:01:19.209062099Z File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 249, in __init__
ERROR 2025-04-05T00:01:19.209059476Z scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
ERROR 2025-04-05T00:01:19.209055185Z File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1999, in run_scheduler_process
ERROR 2025-04-05T00:01:19.209014177Z [2025-04-05 00:01:19 TP0] Scheduler hit an exception: Traceback (most recent call last):
ERROR 2025-04-05T00:01:19.199748277Z [2025-04-05 00:01:19] Received sigquit from a child process. It usually means the child failed.
ERROR 2025-04-05T00:01:19.199052572Z {}
ERROR 2025-04-05T00:01:19.199050426Z Error while creating shared memory segment /dev/shm/nccl-ufmqwQ (size 7340384)
ERROR 2025-04-05T00:01:19.199037551Z Last error:
ERROR 2025-04-05T00:01:19.199035406Z ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.
ERROR 2025-04-05T00:01:19.199032783Z torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:317, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.21.5
ERROR 2025-04-05T00:01:19.199029922Z work = group.allreduce([tensor], opts)
ERROR 2025-04-05T00:01:19.199027538Z File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2501, in all_reduce
ERROR 2025-04-05T00:01:19.199025154Z return func(*args, **kwargs)
ERROR 2025-04-05T00:01:19.199022293Z File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
ERROR 2025-04-05T00:01:19.199019670Z torch.distributed.all_reduce(tensor, op=torch.distributed.ReduceOp.MIN)
ERROR 2025-04-05T00:01:19.199017047Z File "/sgl-workspace/sglang/python/sglang/srt/utils.py", line 315, in get_available_gpu_memory
ERROR 2025-04-05T00:01:19.199014186Z min_per_gpu_memory = get_available_gpu_memory(
ERROR 2025-04-05T00:01:19.199009656Z File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 328, in init_torch_distributed
ERROR 2025-04-05T00:01:19.199005603Z min_per_gpu_memory = self.init_torch_distributed()
ERROR 2025-04-05T00:01:19.199002265Z File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 169, in __init__
ERROR 2025-04-05T00:01:19.198998451Z self.model_runner = ModelRunner(
ERROR 2025-04-05T00:01:19.198993444Z File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 74, in __init__
ERROR 2025-04-05T00:01:19.198991060Z self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
ERROR 2025-04-05T00:01:19.198988437Z File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
ERROR 2025-04-05T00:01:19.198985815Z self.tp_worker = TpWorkerClass(
ERROR 2025-04-05T00:01:19.198982954Z File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 249, in __init__
ERROR 2025-04-05T00:01:19.198980331Z scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
ERROR 2025-04-05T00:01:19.198975563Z File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1999, in run_scheduler_process
ERROR 2025-04-05T00:01:19.198923587Z [2025-04-05 00:01:19 TP1] Scheduler hit an exception: Traceback (most recent call last):
ERROR 2025-04-05T00:01:04.681244850Z [2025-04-05 00:01:04 TP7] sglang is using nccl==2.21.5
ERROR 2025-04-05T00:01:04.681155443Z [2025-04-05 00:01:04 TP4] sglang is using nccl==2.21.5
ERROR 2025-04-05T00:01:04.681041002Z [2025-04-05 00:01:04 TP5] sglang is using nccl==2.21.5
ERROR 2025-04-05T00:01:04.680786132Z [2025-04-05 00:01:04 TP6] sglang is using nccl==2.21.5
ERROR 2025-04-05T00:01:04.680771112Z [2025-04-05 00:01:04 TP2] sglang is using nccl==2.21.5
ERROR 2025-04-05T00:01:04.680658578Z [2025-04-05 00:01:04 TP1] sglang is using nccl==2.21.5
ERROR 2025-04-05T00:01:04.680569648Z [2025-04-05 00:01:04 TP3] sglang is using nccl==2.21.5
ERROR 2025-04-05T00:01:04.680526733Z [2025-04-05 00:01:04 TP0] sglang is using nccl==2.21.5
ERROR 2025-04-05T00:01:02.885493516Z [2025-04-05 00:01:02 TP4] Init torch distributed begin.
ERROR 2025-04-05T00:01:02.880952596Z [2025-04-05 00:01:02 TP0] Init torch distributed begin.
ERROR 2025-04-05T00:01:02.818879842Z [2025-04-05 00:01:02 TP7] Init torch distributed begin.
ERROR 2025-04-05T00:01:02.735132217Z [2025-04-05 00:01:02 TP1] Init torch distributed begin.
ERROR 2025-04-05T00:01:02.720506668Z [2025-04-05 00:01:02 TP5] Init torch distributed begin.
ERROR 2025-04-05T00:01:02.307281494Z [2025-04-05 00:01:02 TP3] Init torch distributed begin.
ERROR 2025-04-05T00:01:02.116440296Z [2025-04-05 00:01:02 TP2] Init torch distributed begin.
ERROR 2025-04-05T00:01:01.875401735Z [2025-04-05 00:01:01 TP6] Init torch distributed begin.
ERROR 2025-04-05T00:00:52.673557043Z [2025-04-05 00:00:52] server_args=ServerArgs(model_path='meta-llama/Llama-3.1-70B-Instruct', tokenizer_path='meta-llama/Llama-3.1-70B-Instruct', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', trust_remote_code=True, dtype='auto', kv_cache_dtype='auto', quantization=None, quantization_param_path=None, context_length=None, device='cuda', served_model_name='meta-llama/Llama-3.1-70B-Instruct', chat_template=None, completion_template=None, is_embedding=False, revision=None, host='0.0.0.0', port=30000, mem_fraction_static=0.81, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='fcfs', schedule_conservativeness=1.0, cpu_offload_gb=0, page_size=1, tp_size=8, stream_interval=1, stream_output=False, random_seed=792723648, constrained_json_whitespace_pattern=None, watchdog_timeout=300, dist_timeout=None, download_dir=None, base_gpu_id=0, gpu_id_step=1, log_level='info', log_level_http=None, log_requests=False, log_requests_level=0, show_time_cost=False, enable_metrics=False, decode_log_interval=40, api_key=None, file_storage_path='sglang_storage', enable_cache_report=False, reasoning_parser=None, dp_size=1, load_balance_method='round_robin', ep_size=1, dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', lora_paths=None, max_loras_per_batch=8, lora_backend='triton', attention_backend='fa3', sampling_backend='flashinfer', grammar_backend='xgrammar', speculative_algorithm=None, speculative_draft_model_path=None, speculative_num_steps=None, speculative_eagle_topk=None, speculative_num_draft_tokens=None, speculative_accept_threshold_single=1.0, speculative_accept_threshold_acc=1.0, speculative_token_map=None, enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, disable_radix_cache=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, enable_nccl_nvls=False, disable_outlines_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, disable_overlap_schedule=False, enable_mixed_chunk=False, enable_dp_attention=False, enable_ep_moe=False, enable_deepep_moe=False, deepep_mode=None, enable_torch_compile=True, torch_compile_max_bs=32, cuda_graph_max_bs=160, cuda_graph_bs=None, torchao_config='', enable_nan_detection=False, enable_p2p_check=False, triton_attention_reduce_in_fp32=False, triton_attention_num_kv_splits=8, num_conti…
INFO 2025-04-05T00:00:45.209044218Z Starting API server with user-specified arguments...
INFO 2025-04-05T00:00:45.209043025Z ==> No LWS_LEADER_ADDRESS environment variable detected, assuming single node
INFO 2025-04-05T00:00:45.209039211Z SGLang server arguments: --model=meta-llama/Llama-3.1-70B-Instruct --tp=8 --attention-backend=fa3 --trust-remote-code --enable-torch-compile
```

### Reproduction

I am using SGLang server arguments: `--model=meta-llama/Llama-3.1-70B-Instruct --tp=8 --attention-backend=fa3 --trust-remote-code --enable-torch-compile`. The error appears at the start up.

### Environment

INFO 2025-04-06T03:02:45.843368291Z Python: 3.10.12 (main, Feb 4 2025, 14:57:36) [GCC 11.4.0]
--
INFO 2025-04-06T03:02:45.843415975Z CUDA available: True
INFO 2025-04-06T03:02:45.843419551Z GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
INFO 2025-04-06T03:02:45.843421697Z GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
INFO 2025-04-06T03:02:45.843424320Z CUDA_HOME: /usr/local/cuda
INFO 2025-04-06T03:02:45.843426227Z NVCC: Cuda compilation tools, release 12.4, V12.4.131
INFO 2025-04-06T03:02:45.843428611Z CUDA Driver Version: 535.230.02
INFO 2025-04-06T03:02:45.843430757Z PyTorch: 2.5.1+cu124
INFO 2025-04-06T03:02:45.843432664Z sglang: 0.4.4.post3
INFO 2025-04-06T03:02:45.843434810Z sgl_kernel: 0.0.7
INFO 2025-04-06T03:02:45.843438386Z flashinfer: Module Not Found
INFO 2025-04-06T03:02:45.843440294Z triton: 3.1.0
INFO 2025-04-06T03:02:45.843442201Z transformers: 4.50.0
INFO 2025-04-06T03:02:45.843443632Z torchao: 0.9.0
INFO 2025-04-06T03:02:45.843445539Z numpy: 2.2.4
INFO 2025-04-06T03:02:45.843447208Z aiohttp: 3.11.16
INFO 2025-04-06T03:02:45.843448877Z fastapi: 0.115.12
INFO 2025-04-06T03:02:45.843450546Z hf_transfer: 0.1.9
INFO 2025-04-06T03:02:45.843452692Z huggingface_hub: 0.30.1
INFO 2025-04-06T03:02:45.843454360Z interegular: 0.3.3
INFO 2025-04-06T03:02:45.843456029Z modelscope: 1.24.1
INFO 2025-04-06T03:02:45.843457698Z orjson: 3.10.16
INFO 2025-04-06T03:02:45.843459367Z outlines: 0.1.11
INFO 2025-04-06T03:02:45.843461275Z packaging: 24.2
INFO 2025-04-06T03:02:45.843462944Z psutil: 7.0.0
INFO 2025-04-06T03:02:45.843464612Z pydantic: 2.11.2
INFO 2025-04-06T03:02:45.843466281Z multipart: Module Not Found
INFO 2025-04-06T03:02:45.843468189Z zmq: Module Not Found
INFO 2025-04-06T03:02:45.843469858Z uvicorn: 0.34.0
INFO 2025-04-06T03:02:45.843471527Z uvloop: 0.21.0
INFO 2025-04-06T03:02:45.843472957Z vllm: Module Not Found
INFO 2025-04-06T03:02:45.843474864Z xgrammar: 0.1.17
INFO 2025-04-06T03:02:45.843476533Z openai: 1.70.0
INFO 2025-04-06T03:02:45.843478202Z tiktoken: 0.9.0
INFO 2025-04-06T03:02:45.843479871Z anthropic: 0.49.0
INFO 2025-04-06T03:02:45.843481779Z litellm: 1.65.3
INFO 2025-04-06T03:02:45.843483448Z decord: 0.6.0
INFO 2025-04-06T03:02:45.843485116Z NVIDIA Topology:
INFO 2025-04-06T03:02:45.843487262Z [4mGPU0 GPU1 GPU2 GPU3 GPU4 GPU5 GPU6 GPU7 CPU Affinity NUMA Affinity GPU NUMA ID[0m
INFO 2025-04-06T03:02:45.843489170Z GPU0 X NV18 NV18 NV18 NV18 NV18 NV18 NV18 0-51,104-155 0 N/A
INFO 2025-04-06T03:02:45.843491315Z GPU1 NV18 X NV18 NV18 NV18 NV18 NV18 NV18 0-51,104-155 0 N/A
INFO 2025-04-06T03:02:45.843493223Z GPU2 NV18 NV18 X NV18 NV18 NV18 NV18 NV18 0-51,104-155 0 N/A
INFO 2025-04-06T03:02:45.843494892Z GPU3 NV18 NV18 NV18 X NV18 NV18 NV18 NV18 0-51,104-155 0 N/A
INFO 2025-04-06T03:02:45.843507289Z GPU4 NV18 NV18 NV18 NV18 X NV18 NV18 NV18 52-103,156-207 1 N/A
INFO 2025-04-06T03:02:45.843509197Z GPU5 NV18 NV18 NV18 NV18 NV18 X NV18 NV18 52-103,156-207 1 N/A
INFO 2025-04-06T03:02:45.843510866Z GPU6 NV18 NV18 NV18 NV18 NV18 NV18 X NV18 52-103,156-207 1 N/A
INFO 2025-04-06T03:02:45.843512773Z GPU7 NV18 NV18 NV18 NV18 NV18 NV18 NV18 X 52-103,156-207 1 N/A
INFO 2025-04-06T03:02:45.843514919Z {}
INFO 2025-04-06T03:02:45.843516588Z Legend:
INFO 2025-04-06T03:02:45.843518018Z {}
INFO 2025-04-06T03:02:45.843519926Z X = Self
INFO 2025-04-06T03:02:45.843521595Z SYS = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
INFO 2025-04-06T03:02:45.843524694Z NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
INFO 2025-04-06T03:02:45.843526601Z PHB = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
INFO 2025-04-06T03:02:45.843539714Z PXB = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
INFO 2025-04-06T03:02:45.843541383Z PIX = Connection traversing at most a single PCIe bridge
INFO 2025-04-06T03:02:45.843542814Z NV# = Connection traversing a bonded set of # NVLinks
INFO 2025-04-06T03:02:45.843544244Z {}
INFO 2025-04-06T03:02:45.843545675Z Hypervisor vendor: KVM
INFO 2025-04-06T03:02:45.843546867Z ulimit soft: 1048576

**Comment by FrankLeeeee** [comment]
Are you running with Docker?

**Comment by harrisonlimh** [comment]
Hi! I was able to resolve the error after increasing the shared memory size for the container. Thank you!
