### ISSUE TITLE
[Bug] CUDA OOM when DP attention enabled, maybe due to incorrect acceptable length estimation.

### ISSUE THREAD

**Issue by junliu-mde** [sgl-project/sglang#6027]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

In my understanding, sglang should estimate max acceptable length with the calculation result of remaining VRAM and kvcache size, for instance server log shows:

```
[2025-05-05 03:55:08 TP0] KV Cache is allocated. #tokens: 274934, KV size: 17.99 GB
```

However, a single 64k-length input can consistently cause the server to crash due to OOM on my H100*8*2 environment.

I also tried 64k-length input on same machine with out dp-attn. This time, the scheduler has processed the input request normally.

### Reproduction

I'm using LWS in K8s,

```
        containers:
          - name: sglang-leader
            image: lmsysorg/sglang:latest
            env:
              - name: LWS_WORKER_INDEX
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
            command:
              - /bin/sh
              - -c
              - |
                cd /sgl-workspace/sglang/
                git pull
                pip install -e python[all]

                python3 -m sglang.compile_deep_gemm --model-path /tmp/scratch-space/DeepSeek-V3-0324 --tp 16 --trust-remote-code \
                  --dist-init-addr $(LWS_LEADER_ADDRESS):5000 --nnodes 2 --node-rank $(LWS_WORKER_INDEX)

                python3 -m sglang.launch_server  --model-path /tmp/scratch-space/DeepSeek-V3-0324  --trust-remote-code  --tp 16 --dp 16 \
                    --dist-init-addr $(LWS_LEADER_ADDRESS):5000 --nnodes 2 --node-rank $(LWS_WORKER_INDEX) \
                    --trust-remote-code --show-time-cost --enable-dp-attention
```
Then send request with `python3 -m sglang.bench_serving --backend sglang --num-prompts 1 --dataset-name random --random-input 64000 --random-output 1 --max-concurrency 1`

The server crash with:
```
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 148, in forward_thread_func_
    logits_output, next_token_ids = self.worker.forward_batch_generation(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 206, in forward_batch_generation
    logits_output = self.model_runner.forward(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1097, in forward
    return self.forward_extend(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1056, in forward_extend
    return self.model.forward(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1522, in forward
    hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1442, in forward
    hidden_states, residual = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1224, in forward
    return self.forward_ffn_with_full_input(
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1253, in forward_ffn_with_full_input
    hidden_states = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 635, in forward
    return self.forward_normal_chunked_kv(
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1089, in forward_normal_chunked_kv
    attn_output = self._chunked_prefix_attn_mha(
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1008, in _chunked_prefix_attn_mha
    k = torch.empty(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.63 GiB. GPU 2 has a total capacity of 79.11 GiB of which 2.61 GiB is free. Process 3596736 has 76.49 GiB memory in use. Of the allocated memory 71.19 GiB is allocated by PyTorch, with 3.63 GiB allocated in private pools (e.g., CUDA Graphs), and 1.30 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Environment

```
Python: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 535.161.07
PyTorch: 2.6.0+cu124
sglang: 0.4.6.post2
sgl_kernel: 0.1.1
flashinfer_python: 0.2.5+cu124torch2.6
triton: 3.2.0
transformers: 4.51.1
torchao: 0.10.0
numpy: 2.2.5
aiohttp: 3.11.18
fastapi: 0.115.12
hf_transfer: 0.1.9
huggingface_hub: 0.30.2
interegular: 0.3.3
modelscope: 1.25.0
orjson: 3.10.18
outlines: 0.1.11
packaging: 25.0
psutil: 7.0.0
pydantic: 2.11.4
python-multipart: 0.0.20
pyzmq: 26.4.0
uvicorn: 0.34.2
uvloop: 0.21.0
vllm: Module Not Found
xgrammar: 0.1.17
openai: 1.76.2
tiktoken: 0.9.0
anthropic: 0.50.0
litellm: 1.67.5
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    NIC8    NIC9    NIC10   NIC11   NIC12   NIC13   NIC14   NIC15   NIC16   NIC17   NIC18   CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS     PIX     NODE    SYS     NODE    SYS     SYS     NODE    SYS     SYS     SYS     0-55,112-167    0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    NODE    PIX     NODE    NODE    NODE    NODE    SYS     SYS     SYS     NODE    PIX     SYS     NODE    SYS     SYS     NODE    SYS     SYS     SYS     0-55,112-167    0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    NODE    NODE    PIX     NODE    NODE    NODE    SYS     SYS     SYS     NODE    NODE    SYS     NODE    SYS     SYS     PIX     SYS     SYS     SYS     0-55,112-167    0               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    NODE    NODE    NODE    NODE    NODE    PIX     SYS     SYS     SYS     NODE    NODE    SYS     PIX     SYS     SYS     NODE    SYS     SYS     SYS     0-55,112-167    0               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     SYS     SYS     SYS     SYS     PIX     NODE    NODE    SYS     SYS     NODE    SYS     PIX     NODE    SYS     NODE    NODE    NODE    56-111,168-223  1               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     SYS     SYS     SYS     SYS     NODE    PIX     NODE    SYS     SYS     NODE    SYS     NODE    NODE    SYS     PIX     NODE    NODE    56-111,168-223  1               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    PIX     SYS     SYS     NODE    SYS     NODE    NODE    SYS     NODE    PIX     NODE    56-111,168-223  1               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE    SYS     SYS     PIX     SYS     NODE    PIX     SYS     NODE    NODE    NODE    56-111,168-223  1               N/A
NIC0    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS     PIX     NODE    SYS     NODE    SYS     SYS     NODE    SYS     SYS     SYS
NIC1    NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    NODE    NODE    SYS     SYS     SYS     NODE    PIX     SYS     NODE    SYS     SYS     NODE    SYS     SYS     SYS
NIC2    NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    NODE    NODE    SYS     SYS     SYS     NODE    NODE    SYS     NODE    SYS     SYS     PIX     SYS     SYS     SYS
NIC3    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      PIX     NODE    SYS     SYS     SYS     NODE    NODE    SYS     NODE    SYS     SYS     NODE    SYS     SYS     SYS
NIC4    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX      X      NODE    SYS     SYS     SYS     NODE    NODE    SYS     NODE    SYS     SYS     NODE    SYS     SYS     SYS
NIC5    NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    NODE     X      SYS     SYS     SYS     NODE    NODE    SYS     PIX     SYS     SYS     NODE    SYS     SYS     SYS
NIC6    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS      X      NODE    NODE    SYS     SYS     NODE    SYS     PIX     NODE    SYS     NODE    NODE    NODE
NIC7    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE     X      NODE    SYS     SYS     NODE    SYS     NODE    NODE    SYS     PIX     NODE    NODE
NIC8    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE     X      SYS     SYS     NODE    SYS     NODE    NODE    SYS     NODE    PIX     NODE
NIC9    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS      X      NODE    SYS     NODE    SYS     SYS     NODE    SYS     SYS     SYS
NIC10   NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    NODE    NODE    SYS     SYS     SYS     NODE     X      SYS     NODE    SYS     SYS     NODE    SYS     SYS     SYS
NIC11   SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE    SYS     SYS      X      SYS     NODE    PIX     SYS     NODE    NODE    NODE
NIC12   NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    NODE    PIX     SYS     SYS     SYS     NODE    NODE    SYS      X      SYS     SYS     NODE    SYS     SYS     SYS
NIC13   SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     PIX     NODE    NODE    SYS     SYS     NODE    SYS      X      NODE    SYS     NODE    NODE    NODE
NIC14   SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE    SYS     SYS     PIX     SYS     NODE     X      SYS     NODE    NODE    NODE
NIC15   NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    NODE    NODE    SYS     SYS     SYS     NODE    NODE    SYS     NODE    SYS     SYS      X      SYS     SYS     SYS
NIC16   SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE    PIX     NODE    SYS     SYS     NODE    SYS     NODE    NODE    SYS      X      NODE    NODE
NIC17   SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    PIX     SYS     SYS     NODE    SYS     NODE    NODE    SYS     NODE     X      NODE
NIC18   SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE    SYS     SYS     NODE    SYS     NODE    NODE    SYS     NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5
  NIC6: mlx5_6
  NIC7: mlx5_7
  NIC8: mlx5_8
  NIC9: mlx5_9
  NIC10: mlx5_10
  NIC11: mlx5_11
  NIC12: mlx5_12
  NIC13: mlx5_13
  NIC14: mlx5_14
  NIC15: mlx5_15
  NIC16: mlx5_16
  NIC17: mlx5_17
  NIC18: mlx5_bond_0


ulimit soft: 1048576
```

**Comment by junliu-mde** [comment]
Previously, It was reported that DP attention did not support DP>4 in #4616 (illegal memory access), I also sometimes met illegal memory access with dp=16 when input concurrency is very high (usually appears when >1024). Not sure whether it's not suggested to use dp>4 at current time.

**Comment by junliu-mde** [comment]
Update: still OOM with `--mem-fraction-static 0.8`, can not start up with `--mem-fraction-static 0.7` (error with "not enough memory, please increase mem-fraction-static)

with `--mem-fraction-static 0.75` the kv cache pool is relatively small...

![Image](https://github.com/user-attachments/assets/4b734a5f-551b-4051-a8a2-8c7a199ba17a)

Manually restrict the context length works for me, but I think there should be some smart detection...

**Comment by JerryKwan** [comment]
Encountered the same issue when running Deepseek R1 0528 with 8xH200 GPUs.

**Comment by JerryKwan** [comment]
And the following is the logs when the system crashed
```text
[2025-07-07 19:00:30 DP4 TP4] TpModelWorkerClient hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 127, in forward_thread_func
    self.forward_thread_func_()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 162, in forward_thread_func_
    self.worker.forward_batch_generation(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 212, in forward_batch_generation
    logits_output, can_run_cuda_graph = self.model_runner.forward(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1231, in forward
    output = self._forward_raw(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1260, in _forward_raw
    ret = self.forward_extend(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1199, in forward_extend
    return self.model.forward(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1962, in forward
    hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1855, in forward
    hidden_states, residual = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1693, in forward
    hidden_states = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 920, in forward
    return self.forward_core(s)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 974, in forward_core
    return self.forward_normal_chunked_kv_core(*inner_state)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1575, in forward_normal_chunked_kv_core
    attn_output = self._chunked_prefix_attn_mha(
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1490, in _chunked_prefix_attn_mha
    k = torch.empty(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.64 GiB. GPU 4 has a total capacity of 139.81 GiB of which 1.38 GiB is free. Including non-PyTorch memory, this process has 138.43 GiB memory in use. Of the allocated memory 132.74 GiB is allocated by PyTorch, with 5.08 GiB allocated in private pools (e.g., CUDA Graphs), and 1.94 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
@zhyncs Any suggestion about what caused that problem and how to solve it? thank you.

**Comment by ch-wan** [comment]
SGLang only preallocate memory for static tensors such as model weights and kv cache. Encountering OOM during runtime is reasonable because we cannot estimate dynamic memory requirement. You can consider to reduce `--mem-fraction-static` to leave more room for dynamic memory or reduce `--chunked-prefill-size` to decrease dynamic memory requirement.

**Comment by JerryKwan** [comment]
@ch-wan 
Thanks for the explanation.
The question is if dp attention is not enabled, there is no OOM occurred. and It's tricky to set the correct --mem-fraction-static value. As outlined previous, the service failed to start when --mem-fraction-static set to 0.8.

**Comment by ch-wan** [comment]
This is reasonable because DP attn requires all-gather across DP ranks. The processing token size and peak memory usage is proportional to DP size. You can see the analysis in our blog (https://lmsys.org/blog/2025-05-05-large-scale-ep/#dense-ffns).

**Comment by JerryKwan** [comment]
@ch-wan 
Thanks for the information.
One more question, Is there any documents about how to calculate the value of --mem-fraction-static? As https://github.com/sgl-project/sglang/issues/322#issuecomment-2041370727 outlined, --mem-fraction-static is used to calculate the KV cache, but it can not be too large or too small. 
Let's take running Deepseek R1 on 8xH200 as an example, in order to support max input length (--context-length 163840), what value should we use? Thank you.

**Comment by ch-wan** [comment]
Perhaps you are looking for `--max-total-tokens`. You can use it to control kv size directly based on your setting.

**Comment by JerryKwan** [comment]
@ch-wan 
ah, it's my fault. I can use --max-total-tokens to control kv size. Does it mean --max-total-tokens and --mem-fraction-static can not use at the same time? According to what I understand, --max-total-tokens and --mem-fraction-static are all means to control the kv cache size, right? thank you.

**Comment by junliu-mde** [comment]
> [@ch-wan](https://github.com/ch-wan) ah, it's my fault. I can use --max-total-tokens to control kv size. Does it mean --max-total-tokens and --mem-fraction-static can not use at the same time? According to what I understand, --max-total-tokens and --mem-fraction-static are all means to control the kv cache size, right? thank you.

No. They can be used at the same time.
Lower `--mem-fraction-static` means use fewer VRAM as kv cache, as a result, more VRAM for activation/accumulation etc (although this part of VRAM consumption is hard to estimate, also may change in the future).

If I understand correctly, Ch-wan mentioned `--max-total-tokens` because you can accurately know how many VRAM needed for a certain context size.

**Comment by JerryKwan** [comment]
@junliu-mde 
Got it, thanks for your input.

**Comment by junliu-mde** [comment]
> SGLang only preallocate memory for static tensors such as model weights and kv cache. Encountering OOM during runtime is reasonable because we cannot estimate dynamic memory requirement. You can consider to reduce `--mem-fraction-static` to leave more room for dynamic memory or reduce `--chunked-prefill-size` to decrease dynamic memory requirement.

So in my current understanding, there are 2 conclusions:
1. Runtime OOM cannot be avoided unless sglang sets a very conservative mem-fraction value by default in the code - which is not deserved.
2. Users should test before upgrade sglang version by themselves because I assume dynamic memory requirements are changing among versions.

Correct me if I'm wrong. Thanks.
