### ISSUE TITLE
[Bug] eagle2【CUDA error: an illegal memory access was encountered】

### ISSUE THREAD

**Issue by dongyibo** [sgl-project/sglang#6309]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

I was running eagle2 online（based on sglang=0.4.5，sgl-kernel=0.0.5 ，flashinfer-python=0.2.5）, and after a while, I encountered an cuda error saying "an illegal memory access was encountered". Here are the details of the error. Could you help me take a look?

---------------------
File "/root/python/betelgeuse/srt/managers/scheduler.py", line 2582, in run_scheduler_process
    scheduler.event_loop_normal()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/python/betelgeuse/srt/managers/scheduler.py", line 702, in event_loop_normal
    result = self.run_batch(batch)
  File "/root/python/betelgeuse/srt/managers/scheduler.py", line 1657, in run_batch
    ) = self.draft_worker.forward_batch_speculative_generation(batch)
  File "/root/python/betelgeuse/srt/speculative/eagle_worker.py", line 254, in forward_batch_speculative_generation
    logits_output, verify_output, model_worker_batch = self.verify(
  File "/root/python/betelgeuse/srt/speculative/eagle_worker.py", line 490, in verify
    logits_output,_,_,_ = self.target_worker.forward_batch_generation(
  File "/root/python/betelgeuse/srt/managers/tp_worker.py", line 292, in forward_batch_generation
    logits_output = self.model_runner.forward(forward_batch)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/python/betelgeuse/srt/model_executor/model_runner.py", line 1257, in forward
    return self.cuda_graph_runner.replay(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/python/betelgeuse/srt/model_executor/cuda_graph_runner.py", line 569, in replay
    self.replay_prepare(forward_batch)
  File "/root/python/betelgeuse/srt/model_executor/cuda_graph_runner.py", line 548, in replay_prepare
    self.model_runner.attn_backend.init_forward_metadata_replay_cuda_graph(
  File "/root/python/betelgeuse/srt/layers/attention/flashinfer_backend.py", line 369, in init_forward_metadata_replay_cuda_graph
    self.indices_updater_prefill.update(
  File "/root/python/betelgeuse/srt/layers/attention/flashinfer_backend.py", line 738, in update_single_wrapper
    self.call_begin_forward(
  File "/root/python/betelgeuse/srt/layers/attention/flashinfer_backend.py", line 895, in call_begin_forward
    wrapper_paged.begin_forward(
  File "/usr/local/lib/python3.10/dist-packages/flashinfer/prefill.py", line 1302, in plan
    qo_indptr_host = qo_indptr.to("cpu")
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Reproduction

target model is Mixtral，eagle model trained by myself
config：
"mem_fraction_static": 0.7,
"max_running_requests": 800,
"speculative_algorithm": "EAGLE",
"speculative_num_steps": 3,
"speculative_eagle_topk": 1,
"speculative_num_draft_tokens": 4,

### Environment

Python: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
CUDA available: True
GPU 0: NVIDIA A800-SXM4-80GB
GPU 0 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda-12.4
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 470.161.03
PyTorch: 2.5.1+cu124
sglang: 0.4.5
sgl_kernel: 0.0.5
flashinfer: Module Not Found
triton: 3.1.0
transformers: 4.51.0
torchao: 0.10.0
numpy: 1.26.4
aiohttp: 3.11.16
fastapi: 0.115.12
hf_transfer: 0.1.9
huggingface_hub: 0.30.2
interegular: 0.3.3
modelscope: 1.25.0
orjson: 3.10.16
outlines: 0.1.11
packaging: 24.2
psutil: 7.0.0
pydantic: 2.11.3
multipart: Module Not Found
zmq: Module Not Found
uvicorn: 0.34.1
uvloop: 0.21.0
vllm: 0.7.2
xgrammar: 0.1.17
openai: 1.73.0
tiktoken: 0.9.0
anthropic: 0.49.0
litellm: 1.66.0
decord: 0.6.0
NVIDIA Topology: 
        GPU0    mlx5_0  mlx5_1  mlx5_2  mlx5_3  mlx5_4  mlx5_5  mlx5_6  mlx5_7  mlx5_8  CPU Affinity    NUMA Affinity
GPU0     X      SYS     SYS     SYS     SYS     SYS     PXB     PXB     NODE    NODE    32-63,96-127    1
mlx5_0  SYS      X      NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS
mlx5_1  SYS     NODE     X      PIX     NODE    NODE    SYS     SYS     SYS     SYS
mlx5_2  SYS     NODE    PIX      X      NODE    NODE    SYS     SYS     SYS     SYS
mlx5_3  SYS     NODE    NODE    NODE     X      PIX     SYS     SYS     SYS     SYS
mlx5_4  SYS     NODE    NODE    NODE    PIX      X      SYS     SYS     SYS     SYS
mlx5_5  PXB     SYS     SYS     SYS     SYS     SYS      X      PIX     NODE    NODE
mlx5_6  PXB     SYS     SYS     SYS     SYS     SYS     PIX      X      NODE    NODE
mlx5_7  NODE    SYS     SYS     SYS     SYS     SYS     NODE    NODE     X      PIX
mlx5_8  NODE    SYS     SYS     SYS     SYS     SYS     NODE    NODE    PIX      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1048576

**Comment by dongyibo** [comment]
> I think the parameters should meets the requirements: speculative_num_draft_tokens <= speculative_num_steps * speculative_eagle_topk In your case, speculative_num_draft_tokens=4, which is larger than 1*3.

@hotelll 
This doesn't seem to be true, does it? Please refer to the content on this website：
https://docs.sglang.ai/backend/speculative_decoding.html

**Comment by dongyibo** [comment]
The error occurred after a relatively long period of operation, not at the time of startup

**Comment by hotelll** [comment]
The reason might be that: the init cuda graph will allocate  max_num_token = max_bs(i.e., cuda_graph_max_bs) * speculative_num_draft_tokens. Therefore, if during running, the (running req_num * speculative_num_draft_tokens > max_num_token)，an illegal memory access was encountered. 
This is just my guess, for reference only.

**Comment by dongyibo** [comment]
> The reason might be that: the init cuda graph will allocate max_num_token = max_bs(i.e., cuda_graph_max_bs) * speculative_num_draft_tokens. Therefore, if during running, the (running req_num * speculative_num_draft_tokens > max_num_token)，an illegal memory access was encountered. This is just my guess, for reference only.

@hotelll Thank you for sharing.
my settings：
cuda_graph_max_bs=160
speculative_num_draft_tokens=4
so，max_num_token=640，but when error occurs，running_req_num=12，It doesn't seem to be caused by this, does it?

**Comment by dongyibo** [comment]
export CUDA_LAUNCH_BLOCKING=1：



[rank1]:[E519 05:58:22.475481966 ProcessGroupNCCL.cpp:1595] [PG ID 2 PG GUID 3 Rank 1] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f309436c446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f30943166e4 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f3094806a18 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7f304a225726 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7f304a22a3f0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7f304a231b5a in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f304a23361d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7f30970b95c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x94ac3 (0x7f30e9932ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7f30e99c4850 in /usr/lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 2 PG GUID 3 Rank 1] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f309436c446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f30943166e4 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f3094806a18 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7f304a225726 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7f304a22a3f0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7f304a231b5a in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f304a23361d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7f30970b95c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x94ac3 (0x7f30e9932ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7f30e99c4850 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f309436c446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe4271b (0x7f3049ea071b in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x145c0 (0x7f30970b95c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x94ac3 (0x7f30e9932ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x7f30e99c4850 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Fatal Python error: Aborted

Thread 0x00007f1d4dffb640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/usr/lib/python3.10/threading.py", line 1376 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f1e2ffff640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/usr/lib/python3.10/threading.py", line 1376 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f1f21fff640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/usr/local/lib/python3.10/dist-packages/tqdm/_monitor.py", line 60 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f2db17fe640 (most recent call first):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f22677fe640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/local/lib/python3.10/dist-packages/grpc/_common.py", line 116 in _wait_once
  File "/usr/local/lib/python3.10/dist-packages/grpc/_common.py", line 156 in wait
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 958 in _next
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 541 in __next__
  File "/usr/local/lib/python3.10/dist-packages/leo2_client/remote/conn/grpc_connection.py", line 82 in __refresh_config_response_action
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58 in run
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 83 in _worker
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f2267fff640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/queue.py", line 180 in get
  File "/usr/local/lib/python3.10/dist-packages/leo2_client/remote/conn/grpc_connection.py", line 69 in __refresh_config_request_iterator
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 274 in consume_request_iterator
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f2288ff9640 (most recent call first):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 1656 in channel_spin
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f22897fa640 (most recent call first):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f2df8fc8640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/schedulers/blocking.py", line 30 in _main_loop
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f2df97c9640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/schedulers/blocking.py", line 30 in _main_loop
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f2e097fa640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/usr/local/lib/python3.10/dist-packages/tqdm/_monitor.py", line 60 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007f30e989d1c0 (most recent call first):
  File "/usr/lib/python3.10/linecache.py", line 72 in checkcache
  File "/usr/lib/python3.10/traceback.py", line 379 in extract
  File "/usr/local/lib/python3.10/dist-packages/exceptiongroup/_formatting.py", line 96 in __init__
  File "/usr/lib/python3.10/traceback.py", line 135 in format_exception
  File "/home/jovyan/workspace-0/sunrise-engine/python/betelgeuse/utils.py", line 64 in get_exception_traceback
  File "/home/jovyan/workspace-0/sunrise-engine/python/betelgeuse/srt/managers/scheduler.py", line 2589 in run_scheduler_process
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314 in _bootstrap
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129 in _main
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116 in spawn_main
  File "<string>", line 1 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, multidict._multidict, yarl._quoting_c, propcache._helpers_c, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket.mask, aiohttp._websocket.reader_c, frozenlist._frozenlist, psutil._psutil_linux, psutil._psutil_posix, uvloop.loop, zmq.backend.cython._zmq, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, setproctitle, PIL._imaging, yaml._yaml, markupsafe._speedups, PIL._imagingft, sklearn.__check_build._check_build, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg._matfuncs_expm, scipy.linalg._linalg_pythran, scipy.linalg.cython_blas, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._cython_nnls, scipy._lib._uarray._uarray, scipy.linalg._decomp_interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.interpolate._fitpack, scipy.interpolate._dfitpack, scipy.interpolate._dierckx, scipy.interpolate._ppoly, scipy.interpolate._interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.interpolate._bspl, scipy.special.cython_special, scipy.stats._stats, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._biasedurn, scipy.stats._stats_pythran, scipy.stats._levy_stable.levyst, scipy.stats._ansari_swilk_statistics, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.ndimage._nd_image, scipy.ndimage._rank_filter_1d, _ni_label, scipy.ndimage._ni_label, pyarrow.lib, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pyarrow._compute, pandas._libs.ops, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, sklearn.utils._isfinite, sklearn.utils.sparsefuncs_fast, sklearn.utils.murmurhash, sklearn.utils._openmp_helpers, sklearn.metrics.cluster._expected_mutual_info_fast, sklearn.preprocessing._csr_polynomial_expansion, sklearn.preprocessing._target_encoder_fast, sklearn.metrics._dist_metrics, sklearn.metrics._pairwise_distances_reduction._datasets_pair, sklearn.utils._cython_blas, sklearn.metrics._pairwise_distances_reduction._base, sklearn.metrics._pairwise_distances_reduction._middle_term_computer, sklearn.utils._heap, sklearn.utils._sorting, sklearn.metrics._pairwise_distances_reduction._argkmin, sklearn.metrics._pairwise_distances_reduction._argkmin_classmode, sklearn.utils._vector_sentinel, sklearn.metrics._pairwise_distances_reduction._radius_neighbors, sklearn.metrics._pairwise_distances_reduction._radius_neighbors_classmode, sklearn.metrics._pairwise_fast, sentencepiece._sentencepiece, msgspec._core, _cffi_backend, msgpack._cmsgpack, google._upb._message, ray._raylet, grpc._cython.cygrpc, regex._regex, cuda_utils, __triton_launcher (total: 200)
[2025-05-19 05:58:37] Child process unexpectedly failed with an exit code 134. pid=8265
[rank0]:[E519 06:08:25.815896403 ProcessGroupNCCL.cpp:1484] [PG ID 2 PG GUID 3 Rank 0] ProcessGroupNCCL's watchdog got stuck for 480 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API (e.g., CudaEventDestroy) hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api (for example, CudaEventDestroy), or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang.

**Comment by hotelll** [comment]
https://github.com/flashinfer-ai/flashinfer/issues/1005 maybe this issue in flashinfer can be helpful. This might be a bug in flashinfer.

**Comment by 191220042** [comment]
Hello, I have the same question, and I disabled flashinfer, my backend is flashattention3, and when I use eagle2, the same error will appear at the position encoding after a period of inference

**Comment by dongyibo** [comment]
> Hello, I have the same question, and I disabled flashinfer, my backend is flashattention3, and when I use eagle2, the same error will appear at the position encoding after a period of inference

Does this error also occur when using flashattention3? @191220042

**Comment by 191220042** [comment]
> > Hello, I have the same question, and I disabled flashinfer, my backend is flashattention3, and when I use eagle2, the same error will appear at the position encoding after a period of inference
> 
> Does this error also occur when using flashattention3? [@191220042](https://github.com/191220042)


Yes, but the specific location where the memory access out of bounds occurs is different.哥，好像是校友诶，我是软件所的

**Comment by lingkong-q** [comment]
Our problems were exactly the same. I reduced the value of --mem-fraction, and the problem was solved.

**Comment by arashStone** [comment]
I have the same problem, and my backend is flashattention3, traceback like this:

[2025-07-18 01:04:08 TP4] Scheduler hit an exception: Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 2737, in run_scheduler_process
    scheduler.event_loop_normal()
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 762, in event_loop_normal
    result = self.run_batch(batch)
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1743, in run_batch
    ) = self.draft_worker.forward_batch_speculative_generation(batch)
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/sglang/srt/speculative/eagle_worker.py", line 325, in forward_batch_speculative_generation
    self.verify(batch, spec_info)
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/sglang/srt/speculative/eagle_worker.py", line 687, in verify
    res: EagleVerifyOutput = spec_info.verify(
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/sglang/srt/speculative/eagle_utils.py", line 360, in verify
    accept_index = torch.full(
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Qing-zy** [comment]
the problem is in the custom_mask of verify process, the shape is not fit for kv_indptr, so in flashinfer :        if packed_custom_mask is None and custom_mask is not None:
            # create packed custom mask from custom mask
            packed_custom_mask, mask_indptr = segment_packbits(
                custom_mask.contiguous().view(-1),
                mask_indptr,
                bitorder="little",
            ) this kernel will access out of bound memory, and the error may occur in qo_indptr_host = qo_indptr.to("cpu")

**Comment by guapisolo** [comment]
> the problem is in the custom_mask of verify process, the shape is not fit for kv_indptr, so in flashinfer : if packed_custom_mask is None and custom_mask is not None: # create packed custom mask from custom mask packed_custom_mask, mask_indptr = segment_packbits( custom_mask.contiguous().view(-1), mask_indptr, bitorder="little", ) this kernel will access out of bound memory, and the error may occur in qo_indptr_host = qo_indptr.to("cpu")

Could you provide more details about this? Thank you very much

**Comment by Qing-zy** [comment]
> > the problem is in the custom_mask of verify process, the shape is not fit for kv_indptr, so in flashinfer : if packed_custom_mask is None and custom_mask is not None: # create packed custom mask from custom mask packed_custom_mask, mask_indptr = segment_packbits( custom_mask.contiguous().view(-1), mask_indptr, bitorder="little", ) this kernel will access out of bound memory, and the error may occur in qo_indptr_host = qo_indptr.to("cpu")
> 
> Could you provide more details about this? Thank you very much

the custom mask shape is constructed with real batch size,   
        tree_mask = torch.full(
            (
                seq_lens_sum * num_verify_tokens
                + num_verify_tokens * num_verify_tokens * bs,
            ),
            True,
            device=device,
        )if the bs is not in cuda graph, the custom mask needs padding, but now sglang not implement this padding

**Comment by thbupt** [comment]
> > > the problem is in the custom_mask of verify process, the shape is not fit for kv_indptr, so in flashinfer : if packed_custom_mask is None and custom_mask is not None: # create packed custom mask from custom mask packed_custom_mask, mask_indptr = segment_packbits( custom_mask.contiguous().view(-1), mask_indptr, bitorder="little", ) this kernel will access out of bound memory, and the error may occur in qo_indptr_host = qo_indptr.to("cpu")
> > 
> > 
> > Could you provide more details about this? Thank you very much
> 
> the custom mask shape is constructed with real batch size, tree_mask = torch.full( ( seq_lens_sum * num_verify_tokens + num_verify_tokens * num_verify_tokens * bs, ), True, device=device, )if the bs is not in cuda graph, the custom mask needs padding, but now sglang not implement this padding

@Qing-zy Did you solve the problem?

**Comment by Qing-zy** [comment]
> > > > the problem is in the custom_mask of verify process, the shape is not fit for kv_indptr, so in flashinfer : if packed_custom_mask is None and custom_mask is not None: # create packed custom mask from custom mask packed_custom_mask, mask_indptr = segment_packbits( custom_mask.contiguous().view(-1), mask_indptr, bitorder="little", ) this kernel will access out of bound memory, and the error may occur in qo_indptr_host = qo_indptr.to("cpu")
> > > 
> > > 
> > > Could you provide more details about this? Thank you very much
> > 
> > 
> > the custom mask shape is constructed with real batch size, tree_mask = torch.full( ( seq_lens_sum * num_verify_tokens + num_verify_tokens * num_verify_tokens * bs, ), True, device=device, )if the bs is not in cuda graph, the custom mask needs padding, but now sglang not implement this padding
> 
> [@Qing-zy](https://github.com/Qing-zy) Did you solve the problem?
https://github.com/sgl-project/sglang/compare/main...Qing-zy:sglang:main try this？Not a good fix position

**Comment by guapisolo** [comment]
> > > > > the problem is in the custom_mask of verify process, the shape is not fit for kv_indptr, so in flashinfer : if packed_custom_mask is None and custom_mask is not None: # create packed custom mask from custom mask packed_custom_mask, mask_indptr = segment_packbits( custom_mask.contiguous().view(-1), mask_indptr, bitorder="little", ) this kernel will access out of bound memory, and the error may occur in qo_indptr_host = qo_indptr.to("cpu")
> > > > 
> > > > 
> > > > Could you provide more details about this? Thank you very much
> > > 
> > > 
> > > the custom mask shape is constructed with real batch size, tree_mask = torch.full( ( seq_lens_sum * num_verify_tokens + num_verify_tokens * num_verify_tokens * bs, ), True, device=device, )if the bs is not in cuda graph, the custom mask needs padding, but now sglang not implement this padding
> > 
> > 
> > [@Qing-zy](https://github.com/Qing-zy) Did you solve the problem?
> > [main...Qing-zy:sglang:main](https://github.com/sgl-project/sglang/compare/main...Qing-zy:sglang:main) try this？Not a good fix position

It works after I test a lot of cases. Thank you very much.
If it’s convenient, could you share your name and email with me so I can add you as a co-author in this PR #9687 ?

**Comment by hnyls2002** [comment]
@dongyibo #10892 has been merged. Could you please check whether your problem still exists?

**Comment by liyucheng09** [comment]
I have this error when I am using MTP with Qwen3Next.

```
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/managers/scheduler.py", line 2812, in run_scheduler_process
    scheduler.event_loop_normal()
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/managers/scheduler.py", line 977, in event_loop_normal
    result = self.run_batch(batch)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/managers/scheduler.py", line 2024, in run_batch
    batch_result = self.model_worker.forward_batch_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/speculative/eagle_worker.py", line 276, in forward_batch_generation
    self.verify(batch, spec_info)
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/speculative/eagle_worker.py", line 650, in verify
    batch_result = self.target_worker.forward_batch_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/managers/tp_worker.py", line 368, in forward_batch_generation
    logits_output, can_run_cuda_graph = self.model_runner.forward(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/model_executor/model_runner.py", line 2116, in forward
    output = self._forward_raw(
             ^^^^^^^^^^^^^^^^^^
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/model_executor/model_runner.py", line 2149, in _forward_raw
    ret = self.graph_runner.replay(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/model_executor/cuda_graph_runner.py", line 831, in replay
    self.replay_prepare(forward_batch, pp_proxy_tensors)
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/model_executor/cuda_graph_runner.py", line 806, in replay_prepare
    self.model_runner.attn_backend.init_forward_metadata_replay_cuda_graph(
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/layers/attention/hybrid_linear_attn_backend.py", line 806, in init_forward_metadata_replay_cuda_graph
    attn_backend.init_forward_metadata_replay_cuda_graph(
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/layers/attention/flashinfer_backend.py", line 663, in init_forward_metadata_replay_cuda_graph
    self.indices_updater_prefill.update(
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/layers/attention/flashinfer_backend.py", line 1175, in update_single_wrapper
    self.call_begin_forward(
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/sglang/srt/layers/attention/flashinfer_backend.py", line 1371, in call_begin_forward
    wrapper_paged.begin_forward(
  File "/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/flashinfer/prefill.py", line 1717, in plan
    qo_indptr_host = qo_indptr.to("cpu")
                     ^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


INFO Channel 07/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 08/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 09/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 10/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 11/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 12/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 13/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 14/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 15/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 16/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 17/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 18/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 19/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 20/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 21/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 22/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Channel 23/0 : 4[4] -> 3[3] via P2P/IPC
sh-l20x-0465:17829:20720 [4] NCCL INFO Connected all trees
sh-l20x-0465:17829:20741 [4] NCCL INFO [Proxy Progress] Device 4 CPU core 167
sh-l20x-0465:17829:20720 [4] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 512 | 512
sh-l20x-0465:17829:20720 [4] NCCL INFO 24 coll channels, 24 collnet channels, 0 nvls channels, 32 p2p channels, 32 p2p channels per peer
sh-l20x-0465:17829:20720 [4] NCCL INFO ncclCommInitRankConfig comm 0x3aba02a0 rank 4 nranks 8 cudaDev 4 nvmlDev 4 busId 9b000 commId 0x15ba39726d9c7f2f - Init COMPLETE
sh-l20x-0465:17829:20720 [4] NCCL INFO Init timings - ncclCommInitRankConfig: rank 4 nranks 8 total 1.40 (kernels 0.00, alloc 0.00, bootstrap 0.00, allgathers 0.01, topo 1.06, graphs 0.01, connections 0.31, rest 0.01)
[rank4]:[W1104 19:50:12.815361361 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
nanobind: leaked 1 instances!
 - leaked instance 0x7ff0bca58ee8 of type "xgrammar.xgrammar_bindings.GrammarCompiler"
nanobind: leaked 1 types!
 - leaked type "xgrammar.xgrammar_bindings.GrammarCompiler"
nanobind: leaked 9 functions!
 - leaked function "compile_regex"
 - leaked function "__init__"
 - leaked function "compile_grammar"
 - leaked function "compile_builtin_json_grammar"
 - leaked function "compile_structural_tag"
 - leaked function "get_cache_size_bytes"
 - leaked function "clear_cache"
 - leaked function ""
 - leaked function "compile_json_schema"
nanobind: this is likely caused by a reference counting issue in the binding code.
[2025-11-05 01:48:53] [http_server] Error: Request is disconnected from the client side (type 1). Abort request obj.rid='5667210b82fc46fd9e40f714c42f6293'
```

```
(sglang) /cpfs02/user/lyc508653/codespace/sglang> python -m sglang.check_env
/cpfs02/user/lyc508653/codespace/sglang/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
Python: 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda-12.8
NVCC: Cuda compilation tools, release 12.8, V12.8.93
CUDA Driver Version: 550.127.08
PyTorch: 2.8.0+cu128
sglang: 0.5.4.post2
sgl_kernel: 0.3.16.post4
flashinfer_python: 0.4.1
triton: 3.4.0
transformers: 4.57.1
torchao: 0.9.0
numpy: 2.3.4
aiohttp: 3.13.2
fastapi: 0.120.4
hf_transfer: 0.1.9
huggingface_hub: 0.36.0
interegular: 0.3.3
modelscope: 1.31.0
orjson: 3.11.4
outlines: 0.1.11
packaging: 25.0
psutil: 7.1.2
pydantic: 2.12.3
python-multipart: 0.0.20
pyzmq: 27.1.0
uvicorn: 0.38.0
uvloop: 0.22.1
vllm: Module Not Found
xgrammar: 0.1.25
openai: 2.6.1
tiktoken: 0.12.0
anthropic: 0.72.0
litellm: Module Not Found
decord2: 2.0.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    48-95,144-191   1               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    48-95,144-191   1               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    48-95,144-191   1               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     48-95,144-191   1               N/A
NIC0    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    SYS     SYS     SYS     SYS
NIC1    NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    SYS     SYS     SYS     SYS
NIC2    NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    SYS     SYS     SYS     SYS
NIC3    NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      SYS     SYS     SYS     SYS
NIC4    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE
NIC5    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE
NIC6    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE
NIC7    SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0
  NIC1: mlx5_bond_1
  NIC2: mlx5_bond_2
  NIC3: mlx5_bond_3
  NIC4: mlx5_bond_4
  NIC5: mlx5_bond_5
  NIC6: mlx5_bond_6
  NIC7: mlx5_bond_7


ulimit soft: 1048576
(sglang) /cpfs02/user/lyc508653/codespace/sglang> 
```

**Comment by sam571128** [comment]
Same thing happened to me when using v0.5.4.post1:

```
(SGLangEngine pid=952, ip=10.150.236.219) [2025-11-06 01:16:21 TP0] Scheduler hit an exception: Traceback (most recent call last):
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2857, in run_scheduler_process
(SGLangEngine pid=952, ip=10.150.236.219)     scheduler.event_loop_normal()
(SGLangEngine pid=952, ip=10.150.236.219)   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(SGLangEngine pid=952, ip=10.150.236.219)     return func(*args, **kwargs)
(SGLangEngine pid=952, ip=10.150.236.219)            ^^^^^^^^^^^^^^^^^^^^^
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1060, in event_loop_normal
(SGLangEngine pid=952, ip=10.150.236.219)     result = self.run_batch(batch)
(SGLangEngine pid=952, ip=10.150.236.219)              ^^^^^^^^^^^^^^^^^^^^^
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2035, in run_batch
(SGLangEngine pid=952, ip=10.150.236.219)     batch_result = self.model_worker.forward_batch_generation(
(SGLangEngine pid=952, ip=10.150.236.219)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/speculative/eagle_worker.py", line 276, in forward_batch_generation
(SGLangEngine pid=952, ip=10.150.236.219)     self.verify(batch, spec_info)
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/speculative/eagle_worker.py", line 650, in verify
(SGLangEngine pid=952, ip=10.150.236.219)     batch_result = self.target_worker.forward_batch_generation(
(SGLangEngine pid=952, ip=10.150.236.219)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 368, in forward_batch_generation
(SGLangEngine pid=952, ip=10.150.236.219)     logits_output, can_run_cuda_graph = self.model_runner.forward(
(SGLangEngine pid=952, ip=10.150.236.219)                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 2065, in forward
(SGLangEngine pid=952, ip=10.150.236.219)     output = self._forward_raw(
(SGLangEngine pid=952, ip=10.150.236.219)              ^^^^^^^^^^^^^^^^^^
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 2098, in _forward_raw
(SGLangEngine pid=952, ip=10.150.236.219)     ret = self.graph_runner.replay(
(SGLangEngine pid=952, ip=10.150.236.219)           ^^^^^^^^^^^^^^^^^^^^^^^^^
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 819, in replay
(SGLangEngine pid=952, ip=10.150.236.219)     self.replay_prepare(forward_batch, pp_proxy_tensors)
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 794, in replay_prepare
(SGLangEngine pid=952, ip=10.150.236.219)     self.model_runner.attn_backend.init_forward_metadata_replay_cuda_graph(
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/layers/attention/flashinfer_backend.py", line 663, in init_forward_metadata_replay_cuda_graph
(SGLangEngine pid=952, ip=10.150.236.219)     self.indices_updater_prefill.update(
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/layers/attention/flashinfer_backend.py", line 1175, in update_single_wrapper
(SGLangEngine pid=952, ip=10.150.236.219)     self.call_begin_forward(
(SGLangEngine pid=952, ip=10.150.236.219)   File "/sgl-workspace/sglang/python/sglang/srt/layers/attention/flashinfer_backend.py", line 1371, in call_begin_forward
(SGLangEngine pid=952, ip=10.150.236.219)     wrapper_paged.begin_forward(
(SGLangEngine pid=952, ip=10.150.236.219)   File "/usr/local/lib/python3.12/dist-packages/flashinfer/prefill.py", line 1717, in plan
(SGLangEngine pid=952, ip=10.150.236.219)     qo_indptr_host = qo_indptr.to("cpu")
(SGLangEngine pid=952, ip=10.150.236.219)                      ^^^^^^^^^^^^^^^^^^^
(SGLangEngine pid=952, ip=10.150.236.219) torch.AcceleratorError: CUDA error: an illegal memory access was encountered
(SGLangEngine pid=952, ip=10.150.236.219) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(SGLangEngine pid=952, ip=10.150.236.219) For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(SGLangEngine pid=952, ip=10.150.236.219) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

This is under slime training, but is probably the same issue here.

**Comment by Qing-zy** [comment]
> I also have the same error using _sglang v0.5.5-cu129-amd64_ and _flashinfer-python v0.5.0._
> 
> I encountered "cuda illegal memory access" in inference Qwen3-32B-fp8 (single gpu H100) and Eagle 2 with --speculative-num-steps=4, --speculative-eagle-topk=6, --speculative-num-draft-tokens=26. Fix [#9687](https://github.com/sgl-project/sglang/pull/9687) resolves the issue, thank you. I wanted to understand why the fix works, and noticed that in flashinfer in [this line](https://github.com/flashinfer-ai/flashinfer/blob/54101e9533bd65af6393e7f86c30c0bff9794499/flashinfer/prefill.py#L1702) mask length not always equal to mask_indptr[-1]: `custom_mask.numel() != mask_indptr[-1]`
> 
> Experimentally I figured out that "cuda illegal memory access" occurs in my case only when `custom_mask.numel() < mask_indptr[-1]`. I hypothesize that, in segment_packbits, mask_indptr sometimes attempts to access memory that is not allocated for the custom_mask. In general the condition `custom_mask.numel() != mask_indptr[-1]` seems as not expected behavior.
> 
> [@Qing-zy](https://github.com/Qing-zy), have you encountered a similar issue where the length of the custom mask does not match the last value of mask_indptr?

If the running batch size is not included in captured cuda graph bs size，it will occur。So padding custom mask is a solution
