### ISSUE TITLE
[Bug] `health_generate` false positive response

### ISSUE THREAD

**Issue by junliu-mde** [sgl-project/sglang#6624]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

```
[2025-05-26 07:48:17 DP0 TP0] Prefill batch. #new-seq: 1, #new-token: 208, #cached-token: 0, token usage: 0.86, #running-req: 50, #queue-req: 18
[2025-05-26 07:48:17 DP1 TP2] Prefill batch. #new-seq: 1, #new-token: 1024, #cached-token: 0, token usage: 0.90, #running-req: 51, #queue-req: 2
[2025-05-26 07:48:17 DP1 TP2] Prefill batch. #new-seq: 2, #new-token: 1024, #cached-token: 4, token usage: 0.91, #running-req: 51, #queue-req: 1
[2025-05-26 07:48:17 DP1 TP2] Scheduler hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2311, in run_scheduler_process
    scheduler.event_loop_overlap()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 664, in event_loop_overlap
    batch = self.get_next_batch_to_run()
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1307, in get_next_batch_to_run
    self.last_batch.filter_batch(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/schedule_batch.py", line 1554, in filter_batch
    self.seq_lens_sum = self.seq_lens.sum().item()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


[rank2]:[E526 07:48:17.606387121 ProcessGroupNCCL.cpp:1895] [PG ID 2 PG GUID 3 Rank 2] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7ffe7636c1b6 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7ffe76315a76 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7ffe767a3918 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7ffe24a1c556 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7ffe24a298c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x617 (0x7ffe24a2b557 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7ffe24a2c6ed in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7ffe76b7b5c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x94ac3 (0x7ffff7cf1ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7ffff7d83850 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 2 PG GUID 3 Rank 2] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7ffe7636c1b6 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7ffe76315a76 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7ffe767a3918 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7ffe24a1c556 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7ffe24a298c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x617 (0x7ffe24a2b557 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7ffe24a2c6ed in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7ffe76b7b5c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x94ac3 (0x7ffff7cf1ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7ffff7d83850 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1901 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7ffe7636c1b6 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe5c6fc (0x7ffe246876fc in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x145c0 (0x7ffe76b7b5c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x94ac3 (0x7ffff7cf1ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x7ffff7d83850 in /lib/x86_64-linux-gnu/libc.so.6)

Fatal Python error: Aborted

Thread 0x00007fe8b7fff640 (most recent call first):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1829 in watchdog_thread
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007fe8c3fff640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 320 in wait
  File "/usr/lib/python3.10/queue.py", line 171 in get
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 130 in forward_thread_func_
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116 in decorate_context
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 118 in forward_thread_func
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007fece3fff640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/usr/local/lib/python3.10/dist-packages/tqdm/_monitor.py", line 60 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007feceffff640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 324 in wait
  File "/usr/lib/python3.10/threading.py", line 607 in wait
  File "/usr/local/lib/python3.10/dist-packages/tqdm/_monitor.py", line 60 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007ffb888ff640 (most recent call first):
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py", line 53 in _recv_msg
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py", line 161 in _read_thread
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007ffff7c5c480 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 1567 in _shutdown
  File "/usr/lib/python3.10/multiprocessing/process.py", line 332 in _bootstrap
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129 in _main
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116 in spawn_main
  File "<string>", line 1 in <module>

Extension modules: numpy._core._multiarray_umath, numpy.linalg._umath_linalg, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, uvloop.loop, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, psutil._psutil_linux, psutil._psutil_posix, zmq.backend.cython._zmq, PIL._imaging, setproctitle._setproctitle, yaml._yaml, markupsafe._speedups, PIL._imagingft, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, sentencepiece._sentencepiece, cuda.bindings._lib.utils, cuda.bindings._bindings.cydriver, cuda.bindings.cydriver, cuda.bindings.driver, cuda.bindings._bindings.cynvrtc, cuda.bindings.cynvrtc, cuda.bindings.nvrtc, msgspec._core, cuda_utils, regex._regex, __triton_launcher (total: 46)
[2025-05-26 07:48:19] INFO:     10.142.1.14:54368 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:48:22 DP1 TP3] Scheduler hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2311, in run_scheduler_process
    scheduler.event_loop_overlap()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 664, in event_loop_overlap
    batch = self.get_next_batch_to_run()
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1335, in get_next_batch_to_run
    ret, _ = self.prepare_dp_attn_batch(ret)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1641, in prepare_dp_attn_batch
    return self.prepare_dp_attn_batch_raw(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1712, in prepare_dp_attn_batch_raw
    torch.distributed.all_gather_into_tensor(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3803, in all_gather_into_tensor
    work.wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [192.168.179.206]:32171

[2025-05-26 07:48:22 DP0 TP1] Scheduler hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2311, in run_scheduler_process
    scheduler.event_loop_overlap()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 664, in event_loop_overlap
    batch = self.get_next_batch_to_run()
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1335, in get_next_batch_to_run
    ret, _ = self.prepare_dp_attn_batch(ret)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1641, in prepare_dp_attn_batch
    return self.prepare_dp_attn_batch_raw(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1712, in prepare_dp_attn_batch_raw
    torch.distributed.all_gather_into_tensor(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3803, in all_gather_into_tensor
    work.wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [192.168.179.206]:32171

[2025-05-26 07:48:23] Child process unexpectedly failed with an exit code 9. pid=313
[2025-05-26 07:48:24] Child process unexpectedly failed with an exit code 9. pid=314
[2025-05-26 07:48:24] Child process unexpectedly failed with an exit code 9. pid=317
[2025-05-26 07:48:24] Child process unexpectedly failed with an exit code 9. pid=1316
[2025-05-26 07:48:24] Child process unexpectedly failed with an exit code 9. pid=315
[2025-05-26 07:48:24] Child process unexpectedly failed with an exit code 9. pid=7483
[2025-05-26 07:48:24] Child process unexpectedly failed with an exit code 134. pid=6623
[2025-05-26 07:48:24] Child process unexpectedly failed with an exit code 9. pid=7479
[2025-05-26 07:48:24] Child process unexpectedly failed with an exit code 131. pid=6338
[2025-05-26 07:48:25] Child process unexpectedly failed with an exit code 9. pid=6622
[2025-05-26 07:48:26] Child process unexpectedly failed with an exit code 9. pid=6624
[2025-05-26 07:48:26] Child process unexpectedly failed with an exit code 9. pid=6621
[2025-05-26 07:48:26] Child process unexpectedly failed with an exit code 9. pid=6625
[2025-05-26 07:48:27] Child process unexpectedly failed with an exit code 9. pid=6626
[2025-05-26 07:48:27] Child process unexpectedly failed with an exit code 9. pid=6628
[2025-05-26 07:48:27] Child process unexpectedly failed with an exit code 9. pid=6627
[2025-05-26 07:48:29] INFO:     10.142.1.14:55374 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:48:39] INFO:     10.142.1.14:56322 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:48:49] INFO:     10.142.1.14:38566 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:48:59] INFO:     10.142.1.14:54592 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:49:09] INFO:     10.142.1.14:43330 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:49:19] INFO:     10.142.1.14:60770 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:49:29] INFO:     10.142.1.14:39692 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:49:39] INFO:     10.142.1.14:56346 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:49:49] INFO:     10.142.1.14:53290 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:49:59] INFO:     10.142.1.14:53628 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:50:09] INFO:     10.142.1.14:42974 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:50:19] INFO:     10.142.1.14:47396 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:50:29] INFO:     10.142.1.14:53248 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:50:39] INFO:     10.142.1.14:33384 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:50:49] INFO:     10.142.1.14:54738 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:50:59] INFO:     10.142.1.14:55830 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:51:09] INFO:     10.142.1.14:46536 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:51:19] INFO:     10.142.1.14:51238 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:51:29] INFO:     10.142.1.14:57904 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:51:39] INFO:     10.142.1.14:56112 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:51:49] INFO:     10.142.1.14:54358 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:51:59] INFO:     10.142.1.14:33580 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:52:09] INFO:     10.142.1.14:50006 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:52:19] INFO:     10.142.1.14:55214 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:52:29] INFO:     10.142.1.14:42670 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:52:39] INFO:     10.142.1.14:61252 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:52:49] INFO:     10.142.1.14:60288 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:52:59] INFO:     10.142.1.14:56300 - "GET /health_generate HTTP/1.1" 200 OK
[2025-05-26 07:53:09] INFO:     10.142.1.14:38004 - "GET /health_generate HTTP/1.1" 200 OK
```

`health_generate` endpoint continue returning 200 even if the scheduler has crashed.

### Reproduction

This is my guess, possibly because my health check interval is set too short (less than 20 seconds).

```
livenessProbe:
  httpGet:
    path: /health_generate
    port: 8888
  timeoutSeconds: 20
  periodSeconds: 10
```

Continuously send requests using the client, for example: `python3 -m sglang.bench_serving --backend sglang --num-prompts 114514 --dataset-name random --random-input 100 --random-output 1 --max-concurrency 16`

Kill the scheduler after client starts sending requests, should be able to reproduce the issue, /health_generate keeps return 200 even no token was generated at that time.

Although the watchdog timeout may find the scheduler dead and exit (I noticed the main process will exit after minutes when I was trying to reproduce the scene), but sometimes it's not working (in the original scene the "GET /health_generate HTTP/1.1" 200 OK" log kept over a hour).

The suspected source of the bug：

In: 
https://github.com/sgl-project/sglang/blob/14d1075f2c895cdcd1c54e553bfdebb8f584b7ad/python/sglang/srt/entrypoints/http_server.py#L185-L193

`last_receive_tstamp` will be updated no matter this received request is successfully proceed or not:

https://github.com/sgl-project/sglang/blob/14d1075f2c895cdcd1c54e553bfdebb8f584b7ad/python/sglang/srt/managers/tokenizer_manager.py#L1117

From a product design perspective, I'm unsure whether this is the intended behavior, or if the health_generate timeout is 20 seconds, thus requiring users not to send health check requests more frequently than once every 20 seconds. If this is the expected behavior, I think it should be clearly marked in the interface documentation. If this is not expected, I guess it can be fixed by not using global `last_receive_tstamp`. 

### Environment

```
Python: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 570.133.20
PyTorch: 2.6.0+cu124
sglang: 0.4.6.post5
sgl_kernel: 0.1.4
flashinfer_python: 0.2.5+cu124torch2.6
triton: 3.2.0
transformers: 4.51.1
torchao: 0.9.0
numpy: 2.2.6
aiohttp: 3.11.18
fastapi: 0.115.12
hf_transfer: 0.1.9
huggingface_hub: 0.32.0
interegular: 0.3.3
modelscope: 1.26.0
orjson: 3.10.18
outlines: 0.1.11
packaging: 25.0
psutil: 7.0.0
pydantic: 2.11.5
python-multipart: 0.0.20
pyzmq: 26.4.0
uvicorn: 0.34.2
uvloop: 0.21.0
vllm: Module Not Found
xgrammar: 0.1.19
openai: 1.82.0
tiktoken: 0.9.0
anthropic: 0.52.0
litellm: 1.70.4
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    NIC8    NIC9    NIC10   NIC11  NIC12    NIC13   NIC14   NIC15   NIC16   NIC17   NIC18   CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS     PIX     NODE    SYS    NODE     NODE    SYS     SYS     SYS     SYS     SYS     0-55,112-167    0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    NODE    PIX     NODE    NODE    NODE    NODE    SYS     SYS     SYS     NODE    PIX     SYS    NODE     NODE    SYS     SYS     SYS     SYS     SYS     0-55,112-167    0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    NODE    NODE    PIX     NODE    NODE    NODE    SYS     SYS     SYS     NODE    NODE    SYS    PIX      NODE    SYS     SYS     SYS     SYS     SYS     0-55,112-167    0               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    NODE    NODE    NODE    NODE    NODE    PIX     SYS     SYS     SYS     NODE    NODE    SYS    NODE     PIX     SYS     SYS     SYS     SYS     SYS     0-55,112-167    0               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     SYS     SYS     SYS     SYS     PIX     NODE    NODE    SYS     SYS     NODE   SYS      SYS     NODE    PIX     NODE    NODE    NODE    56-111,168-223  1               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     SYS     SYS     SYS     SYS     NODE    PIX     NODE    SYS     SYS     NODE   SYS      SYS     NODE    NODE    PIX     NODE    NODE    56-111,168-223  1               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    PIX     SYS     SYS     NODE   SYS      SYS     NODE    NODE    NODE    PIX     NODE    56-111,168-223  1               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE    SYS     SYS     PIX    SYS      SYS     PIX     NODE    NODE    NODE    NODE    56-111,168-223  1               N/A
NIC0    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS     PIX     NODE    SYS    NODE     NODE    SYS     SYS     SYS     SYS     SYS
NIC1    NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    NODE    NODE    SYS     SYS     SYS     NODE    PIX     SYS    NODE     NODE    SYS     SYS     SYS     SYS     SYS
NIC2    NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    NODE    NODE    SYS     SYS     SYS     NODE    NODE    SYS    PIX      NODE    SYS     SYS     SYS     SYS     SYS
NIC3    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      PIX     NODE    SYS     SYS     SYS     NODE    NODE    SYS    NODE     NODE    SYS     SYS     SYS     SYS     SYS
NIC4    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX      X      NODE    SYS     SYS     SYS     NODE    NODE    SYS    NODE     NODE    SYS     SYS     SYS     SYS     SYS
NIC5    NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    NODE     X      SYS     SYS     SYS     NODE    NODE    SYS    NODE     PIX     SYS     SYS     SYS     SYS     SYS
NIC6    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS      X      NODE    NODE    SYS     SYS     NODE   SYS      SYS     NODE    PIX     NODE    NODE    NODE
NIC7    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE     X      NODE    SYS     SYS     NODE   SYS      SYS     NODE    NODE    PIX     NODE    NODE
NIC8    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE     X      SYS     SYS     NODE   SYS      SYS     NODE    NODE    NODE    PIX     NODE
NIC9    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS      X      NODE    SYS    NODE     NODE    SYS     SYS     SYS     SYS     SYS
NIC10   NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    NODE    NODE    SYS     SYS     SYS     NODE     X      SYS    NODE     NODE    SYS     SYS     SYS     SYS     SYS
NIC11   SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE    SYS     SYS      X     SYS      SYS     PIX     NODE    NODE    NODE    NODE
NIC12   NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    NODE    NODE    SYS     SYS     SYS     NODE    NODE    SYS     X       NODE    SYS     SYS     SYS     SYS     SYS
NIC13   NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    NODE    PIX     SYS     SYS     SYS     NODE    NODE    SYS    NODE      X      SYS     SYS     SYS     SYS     SYS
NIC14   SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE    SYS     SYS     PIX    SYS      SYS      X      NODE    NODE    NODE    NODE
NIC15   SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     PIX     NODE    NODE    SYS     SYS     NODE   SYS      SYS     NODE     X      NODE    NODE    NODE
NIC16   SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE    PIX     NODE    SYS     SYS     NODE   SYS      SYS     NODE    NODE     X      NODE    NODE
NIC17   SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    PIX     SYS     SYS     NODE   SYS      SYS     NODE    NODE    NODE     X      NODE
NIC18   SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE    SYS     SYS     NODE   SYS      SYS     NODE    NODE    NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5
  NIC6: mlx5_6
  NIC7: mlx5_7
  NIC8: mlx5_8
  NIC9: mlx5_9
  NIC10: mlx5_10
  NIC11: mlx5_11
  NIC12: mlx5_12
  NIC13: mlx5_13
  NIC14: mlx5_14
  NIC15: mlx5_15
  NIC16: mlx5_16
  NIC17: mlx5_17
  NIC18: mlx5_bond_0


ulimit soft: 1048576
```

**Comment by acelyc111** [comment]
@junliu-mde I happened to encounter the same issue, it's because wall time vs. monotonic time, I've fixed it by https://github.com/sgl-project/sglang/pull/8028

**Comment by junliu-mde** [comment]
> [@junliu-mde](https://github.com/junliu-mde) I happened to encounter the same issue, it's because wall time vs. monotonic time, I've fixed it by [#8028](https://github.com/sgl-project/sglang/pull/8028)

Wow, I did suspect this issue was related to time synchronization, but I didn't expect the fix to require only one change. Thank you for the fix.

**Comment by acelyc111** [comment]
> > [@junliu-mde](https://github.com/junliu-mde) I happened to encounter the same issue, it's because wall time vs. monotonic time, I've fixed it by [#8028](https://github.com/sgl-project/sglang/pull/8028)
> 
> Wow, I did suspect this issue was related to time synchronization, but I didn't expect the fix to require only one change. Thank you for the fix.

@junliu-mde this patch has been merged, plz check it, this issue can be closed if it works.

**Comment by junliu-mde** [comment]
> > > [@junliu-mde](https://github.com/junliu-mde) I happened to encounter the same issue, it's because wall time vs. monotonic time, I've fixed it by [#8028](https://github.com/sgl-project/sglang/pull/8028)
> > 
> > 
> > Wow, I did suspect this issue was related to time synchronization, but I didn't expect the fix to require only one change. Thank you for the fix.
> 
> [@junliu-mde](https://github.com/junliu-mde) this patch has been merged, plz check it, this issue can be closed if it works.

Cool, since this issue only happens in DP Attention, I don't have chance recently, but if you confirm that problem solved I can simply close this issue, thank you.
