### ISSUE TITLE
[Bug] Verl + sglang with server backend have illegal memory access

### ISSUE THREAD

**Issue by kemuxiaozi000** [sgl-project/sglang#6630]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

When run script in verl using sglang backend with http server adapter,  I met IMS problem.
version: verl (latest) +sglang(0.4.6.post4)
error:
`(WorkerDict pid=1387612) [2025-05-26 16:01:06 TP0] Cache not flushed because there are pending requests. #queue-req: 0, #running-req: 1
(WorkerDict pid=1387612) [2025-05-26 16:01:06 TP0] Scheduler hit an exception: Traceback (most recent call last):
(WorkerDict pid=1387612)   File "/opt/ac2/lib/python3.12/site-packages/sglang/srt/managers/scheduler.py", line 2269, in run_scheduler_process
(WorkerDict pid=1387612)     scheduler.event_loop_overlap()
(WorkerDict pid=1387612)   File "/opt/ac2/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(WorkerDict pid=1387612)     return func(*args, **kwargs)
(WorkerDict pid=1387612)            ^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=1387612)   File "/opt/ac2/lib/python3.12/site-packages/sglang/srt/managers/scheduler.py", line 658, in event_loop_overlap
(WorkerDict pid=1387612)     batch = self.get_next_batch_to_run()
(WorkerDict pid=1387612)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=1387612)   File "/opt/ac2/lib/python3.12/site-packages/sglang/srt/managers/scheduler.py", line 1304, in get_next_batch_to_run
(WorkerDict pid=1387612)     self.running_batch = self.update_running_batch(self.running_batch)
(WorkerDict pid=1387612)                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=1387612)   File "/opt/ac2/lib/python3.12/site-packages/sglang/srt/managers/scheduler.py", line 1502, in update_running_batch
(WorkerDict pid=1387612)     batch.prepare_for_decode()
(WorkerDict pid=1387612)   File "/opt/ac2/lib/python3.12/site-packages/sglang/srt/managers/schedule_batch.py", line 1461, in prepare_for_decode
(WorkerDict pid=1387612)     locs = self.seq_lens.clone()
(WorkerDict pid=1387612)            ^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=1387612) RuntimeError: CUDA error: an illegal memory access was encountered
(WorkerDict pid=1387612) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(WorkerDict pid=1387612) For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(WorkerDict pid=1387612) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(WorkerDict pid=1387612) 
(WorkerDict pid=1387612) 
(WorkerDict pid=1387612) [2025-05-26 16:01:06] Received sigquit from a child process. It usually means the child failed.
(WorkerDict pid=1387612) [2025-05-26 16:01:06 TP1] Cache not flushed because there are pending requests. #queue-req: 0, #running-req: 1
(WorkerDict pid=1387614) [2025-05-26 16:01:03 TP0] Prefill batch. #new-seq: 1, #new-token: 6, #cached-token: 0, token usage: 0.00, #running-req: 0, #queue-req: 0 [repeated 6x across cluster]
(WorkerDict pid=1387614) [2025-05-26 16:01:03] INFO:     127.0.0.1:34500 - "GET /get_model_info HTTP/1.1" 200 OK [repeated 3x across cluster]
(TaskRunner pid=1376949) Using LocalLogger is deprecated. The constructor API will change 
(TaskRunner pid=1376949) Checkpoint tracker file does not exist: %s /workspace/checkpoints/verl_example_gsm8k/qwen2-7b_function_rm_bsz8k_p4k_r4k_seq_packing/latest_checkpointed_iteration.txt
(TaskRunner pid=1376949) Training from scratch
Training Progress:   0%|          | 0/45 [00:00<?, ?it/s]
Training Progress:   0%|          | 0/45 [00:05<?, ?it/s]
(WorkerDict pid=1387614) [2025-05-26 16:01:07] The server is fired up and ready to roll! [repeated 2x across cluster]
(WorkerDict pid=1387614) /opt/ac2/lib/python3.12/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html . [repeated 7x across cluster]
(WorkerDict pid=1387614)   warnings.warn( [repeated 7x across cluster]
(WorkerDict pid=1387614) [2025-05-26 16:01:07 TP1] Cache flushed successfully! [repeated 4x across cluster]
Error executing job with overrides: ['algorithm.adv_estimator=gae', "data.train_files=['/w/data/gsm8k/train.parquet', '/w/data/math/train.parquet']", "data.val_files=['/w/data/gsm8k/test.parquet', '/w/data/math/test.parquet']", 'data.train_batch_size=4096', 'data.max_prompt_length=4096', 'data.max_response_length=4096', 'data.filter_overlong_prompts=True', 'data.truncation=error', 'actor_rollout_ref.model.path=/w/models/Qwen/Qwen2-7B-Instruct', 'actor_rollout_ref.actor.optim.lr=1e-6', 'actor_rollout_ref.model.use_remove_padding=True', 'actor_rollout_ref.model.enable_gradient_checkpointing=True', 'actor_rollout_ref.actor.ppo_mini_batch_size=512', 'actor_rollout_ref.actor.use_dynamic_bsz=True', 'actor_rollout_ref.actor.ppo_max_token_len_per_gpu=24000', 'actor_rollout_ref.actor.fsdp_config.param_offload=False', 'actor_rollout_ref.actor.fsdp_config.optimizer_offload=False', 'actor_rollout_ref.actor.use_kl_loss=False', 'actor_rollout_ref.rollout.tensor_model_parallel_size=2', 'actor_rollout_ref.rollout.name=sglang', '+actor_rollout_ref.rollout.backend=server', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.5', 'actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=24000', 'critic.optim.lr=1e-5', 'critic.model.use_remove_padding=True', 'critic.model.path=/w/models/Qwen/Qwen2-7B-Instruct', 'critic.model.enable_gradient_checkpointing=True', 'critic.ppo_max_token_len_per_gpu=98304', 'critic.model.fsdp_config.param_offload=False', 'critic.model.fsdp_config.optimizer_offload=False', 'algorithm.use_kl_in_reward=False', 'trainer.critic_warmup=0', 'trainer.logger=[console]', 'trainer.project_name=verl_example_gsm8k', 'trainer.experiment_name=qwen2-7b_function_rm_bsz8k_p4k_r4k_seq_packing', 'trainer.n_gpus_per_node=8', 'trainer.val_before_train=False', 'trainer.nnodes=1', 'trainer.save_freq=20', 'trainer.test_freq=5', 'trainer.total_epochs=15']
Traceback (most recent call last):
  File "/opt/ac2/lib/python3.12/site-packages/verl/trainer/main_ppo.py", line 64, in main
    run_ppo(config)
  File "/opt/ac2/lib/python3.12/site-packages/verl/trainer/main_ppo.py", line 76, in run_ppo
    ray.get(runner.run.remote(config))
  File "/opt/ac2/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/ac2/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ac2/lib/python3.12/site-packages/ray/_private/worker.py", line 2771, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ac2/lib/python3.12/site-packages/ray/_private/worker.py", line 919, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ConnectionError): ray::TaskRunner.run() (pid=1376949, ip=172.16.30.223, actor_id=73f88609c305233f596786d001000000, repr=<main_ppo.TaskRunner object at 0x7f709c358890>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ac2/lib/python3.12/site-packages/verl/trainer/main_ppo.py", line 183, in run
    trainer.fit()
  File "/opt/ac2/lib/python3.12/site-packages/verl/trainer/ppo/ray_trainer.py", line 910, in fit
    gen_batch_output = self.actor_rollout_wg.generate_sequences(gen_batch)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ac2/lib/python3.12/site-packages/verl/single_controller/ray/base.py", line 49, in func
    output = ray.get(output)
             ^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ray.exceptions.RayTaskError(ConnectionError): ray::WorkerDict.actor_rollout_generate_sequences() (pid=1387612, ip=172.16.30.223, actor_id=fda5334e9d8cb9dc49e0b5ed01000000, repr=<verl.single_controller.ray.base.WorkerDict object at 0x7f847812dc40>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ac2/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/ac2/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
`

### Reproduction

model: Qwen2.5-0.5B-Instruct

`set -x
gsm8k_train_path=/w/data/gsm8k/train.parquet
gsm8k_test_path=/w/data/gsm8k/test.parquet
math_train_path=/w/data/math/train.parquet
math_test_path=/w/data/math/test.parquet

train_files="['$gsm8k_train_path', '$math_train_path']"
test_files="['$gsm8k_test_path', '$math_test_path']"
#export CUDA_VISIBLE_DEVICES=0,1
python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=gae \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=4096 \
    data.max_prompt_length=4096 \
    data.max_response_length=4096 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    actor_rollout_ref.model.path=/w/models/Qwen/Qwen2.5-0.5B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=512 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=24000 \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=sglang \
    +actor_rollout_ref.rollout.backend=server \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=24000 \
    critic.optim.lr=1e-5 \
    critic.model.use_remove_padding=True \
    critic.model.path=/w/models/Qwen/Qwen2.5-0.5B-Instruct \
    critic.model.enable_gradient_checkpointing=True \
    critic.ppo_max_token_len_per_gpu=98304 \
    critic.model.fsdp_config.param_offload=False \
    critic.model.fsdp_config.optimizer_offload=False \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger=['console'] \
    trainer.project_name='verl_example_gsm8k' \
    trainer.experiment_name='qwen2-7b_function_rm_bsz8k_p4k_r4k_seq_packing' \
    trainer.n_gpus_per_node=8 \`

### Environment

Python: 3.12.7+gc (main, Jan 10 2025, 17:28:43) [GCC 13.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H20
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.8, V12.8.61
CUDA Driver Version: 535.183.06
PyTorch: 2.6.0+cu124
sglang: 0.4.6.post4
sgl_kernel: 0.1.2.post1
flashinfer_python: 0.2.5
triton: 3.1.0
transformers: 4.51.1
torchao: 0.11.0
numpy: 1.26.4
aiohttp: 3.11.18
fastapi: 0.115.12
hf_transfer: 0.1.9
huggingface_hub: 0.30.2
interegular: 0.3.3
modelscope: 1.26.0
orjson: 3.10.18
outlines: 0.1.11
packaging: 25.0
psutil: 7.0.0
pydantic: 2.11.3
python-multipart: 0.0.20
pyzmq: 26.4.0
uvicorn: 0.34.2
uvloop: 0.21.0
vllm: 0.8.5+cu128
xgrammar: 0.1.19
openai: 1.75.0
tiktoken: 0.9.0
anthropic: 0.51.0
litellm: 1.70.2
decord: 0.6.0
NVIDIA Topology: 
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	NIC1	NIC2	NIC3	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV18	NV18	NV18	NV18	NV18	NV18	NV18	NODE	NODE	SYS	SYS	0-47,96-143	0		N/A
GPU1	NV18	 X 	NV18	NV18	NV18	NV18	NV18	NV18	PIX	NODE	SYS	SYS	0-47,96-143	0		N/A
GPU2	NV18	NV18	 X 	NV18	NV18	NV18	NV18	NV18	NODE	NODE	SYS	SYS	0-47,96-143	0		N/A
GPU3	NV18	NV18	NV18	 X 	NV18	NV18	NV18	NV18	NODE	PIX	SYS	SYS	0-47,96-143	0		N/A
GPU4	NV18	NV18	NV18	NV18	 X 	NV18	NV18	NV18	SYS	SYS	PIX	NODE	48-95,144-191	1		N/A
GPU5	NV18	NV18	NV18	NV18	NV18	 X 	NV18	NV18	SYS	SYS	NODE	NODE	48-95,144-191	1		N/A
GPU6	NV18	NV18	NV18	NV18	NV18	NV18	 X 	NV18	SYS	SYS	NODE	PIX	48-95,144-191	1		N/A
GPU7	NV18	NV18	NV18	NV18	NV18	NV18	NV18	 X 	SYS	SYS	NODE	NODE	48-95,144-191	1		N/A
NIC0	NODE	PIX	NODE	NODE	SYS	SYS	SYS	SYS	 X 	NODE	SYS	SYS				
NIC1	NODE	NODE	NODE	PIX	SYS	SYS	SYS	SYS	NODE	 X 	SYS	SYS				
NIC2	SYS	SYS	SYS	SYS	PIX	NODE	NODE	NODE	SYS	SYS	 X 	NODE				
NIC3	SYS	SYS	SYS	SYS	NODE	NODE	PIX	NODE	SYS	SYS	NODE	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0
  NIC1: mlx5_bond_1
  NIC2: mlx5_bond_2
  NIC3: mlx5_bond_3

ulimit soft: 1048576

**Comment by qiancheng0sf** [comment]
Having the same issue with sglang 0.4.6.post5 and latest verl

**Comment by yuleiqin** [comment]
Any update here?

**Comment by sfc-gh-zhyao** [comment]
Having the same issue

**Comment by linhaojia13** [comment]
Having the same issue

**Comment by Dynamite321** [comment]
Having the same issue.

**Comment by linxxx3** [comment]
encountered the same issue. 
i would like to provide more info. if runs with CUDA_LAUNCH_BLOCKING=1 , i got more precise stacks like this:
```
...
File ".../sglang/srt/managers/schedule_batch.py", line 1510, in prepare_for_decode
self.req_to_token_pool.write(
File ".../sglang/srt/mem_cache/memory_pool.py", line 78, in write
self.req_to_token[indices] = values
~~~~~~~~~~~~~~~~~^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
```
hope this could help.
@zhaochenyang20 Could you please take a look when you have a moment?

**Comment by linxxx3** [comment]
> encountered the same issue. i would like to provide more info. if runs with CUDA_LAUNCH_BLOCKING=1 , i got more precise stacks like this:
> 
> ```
> ...
> File ".../sglang/srt/managers/schedule_batch.py", line 1510, in prepare_for_decode
> self.req_to_token_pool.write(
> File ".../sglang/srt/mem_cache/memory_pool.py", line 78, in write
> self.req_to_token[indices] = values
> ~~~~~~~~~~~~~~~~~^^^^^^^^^
> RuntimeError: CUDA error: an illegal memory access was encountered
> ```
> 
> hope this could help. [@zhaochenyang20](https://github.com/zhaochenyang20) Could you please take a look when you have a moment?

my problem solved. my code has a bug which cause the rollout worker crash, silently. it appear to be a crash in sglang, but actually one of the rollout worker already died.

**Comment by WindowsXp-Beta** [comment]
@linxxx3 how did you find the rollout worker crashed silently?

**Comment by linxxx3** [comment]
> [@linxxx3](https://github.com/linxxx3) how did you find the rollout worker crashed silently?

I use the async multi-turn rollout mode. some logics are executed in the async event loop. after I add a try-catch block over these logics, I got the real crash point. meanwhile the rollout workers won't crash.
