### ISSUE TITLE
[Bug] When deploying DeepseekV3(DP+EP) in a multi-machine setup (H800), the Decode instance gets stuck; however, the GPU resource utilization reaches 100%.

### ISSUE THREAD

**Issue by nannaer** [sgl-project/sglang#6763]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

![Image](https://github.com/user-attachments/assets/1eea347c-81aa-446a-b2dd-1aefdb61c31c)

When using the following commands to start the Decode instances on two machines during the multi-machine deployment of DP+EP, I found that the Decode instances get stuck. Meanwhile, via nvidia-smi, it is observed that no model weights are loaded, but the GPU utilization reaches 100%, as shown in the figure above.

I tried to locate the error by checking the logs, which might provide you with some help: It seems that, when launching the multi-machine setup, the `init_distributed_environment` function in `model_runner.py` runs normally, but it gets stuck at the `initialize_model_parallel` function in `model_runner.py`.

### Reproduction

Node 1

SGLANG_TORCH_PROFILER_DIR=./profile_res_decode python3 -m sglang.launch_server --model-path deepseek-ai/DeepSeek-R1 --load-format dummy --trust-remote-code --disaggregation-mode decode --dist-init-addr 10.130.8.144:45000 --nnodes 2 --node-rank 1 --tp-size 16 --dp-size 16 --enable-dp-attention --enable-deepep-moe --ep-size 16 --disable-radix-cache --attention-backend fa3 --mem-frac 0.7 --deepep-mode low_latency --host 0.0.0.0 --moe-dense-tp-size 1 --enable-dp-lm-head --cuda-graph-max-bs 128 --watchdog-timeout 1000000 --decode-log-interval 1

Node 2

SGLANG_TORCH_PROFILER_DIR=./profile_res_decode python3 -m sglang.launch_server --model-path deepseek-ai/DeepSeek-R1 --load-format dummy --trust-remote-code --disaggregation-mode decode --dist-init-addr 10.130.8.144:45000 --nnodes 2 --node-rank 0 --tp-size 16 --dp-size 16 --enable-dp-attention --enable-deepep-moe --ep-size 16 --disable-radix-cache --attention-backend fa3 --mem-frac 0.7 --deepep-mode low_latency --host 0.0.0.0 --moe-dense-tp-size 1 --enable-dp-lm-head --cuda-graph-max-bs 128 --watchdog-timeout 1000000 --decode-log-interval 1

### Environment

Python: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA L20Y
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 550.127.08
PyTorch: 2.6.0+cu124
sglang: 0.4.6.post5
sgl_kernel: 0.1.4
flashinfer_python: 0.2.5+cu124torch2.6
triton: 3.2.0
transformers: 4.52.3
torchao: 0.9.0
numpy: 2.2.5
aiohttp: 3.11.18
fastapi: 0.115.12
hf_transfer: 0.1.9
huggingface_hub: 0.30.2
interegular: 0.3.3
modelscope: 1.25.0
orjson: 3.10.18
outlines: 0.1.11
packaging: 25.0
psutil: 7.0.0
pydantic: 2.11.4
python-multipart: 0.0.20
pyzmq: 26.4.0
uvicorn: 0.34.2
uvloop: 0.21.0
vllm: Module Not Found
xgrammar: 0.1.19
openai: 1.76.2
tiktoken: 0.9.0
anthropic: 0.50.0
litellm: 1.67.5
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7       CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV8     NV8     NV8     NV8     NV8     NV8     NV8     PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS0,2,4,6,8,10    0               N/A
GPU1    NV8      X      NV8     NV8     NV8     NV8     NV8     NV8     NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS0,2,4,6,8,10    0               N/A
GPU2    NV8     NV8      X      NV8     NV8     NV8     NV8     NV8     NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS0,2,4,6,8,10    0               N/A
GPU3    NV8     NV8     NV8      X      NV8     NV8     NV8     NV8     NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS0,2,4,6,8,10    0               N/A
GPU4    NV8     NV8     NV8     NV8      X      NV8     NV8     NV8     SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE       1,3,5,7,9,11    1               N/A
GPU5    NV8     NV8     NV8     NV8     NV8      X      NV8     NV8     SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE       1,3,5,7,9,11    1               N/A
GPU6    NV8     NV8     NV8     NV8     NV8     NV8      X      NV8     SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE       1,3,5,7,9,11    1               N/A
GPU7    NV8     NV8     NV8     NV8     NV8     NV8     NV8      X      SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX1,3,5,7,9,11    1               N/A
NIC0    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    SYS     SYS     SYS     SYS
NIC1    NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    SYS     SYS     SYS     SYS
NIC2    NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    SYS     SYS     SYS     SYS
NIC3    NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      SYS     SYS     SYS     SYS
NIC4    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE
NIC5    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE
NIC6    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE
NIC7    SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0
  NIC1: mlx5_bond_1
  NIC2: mlx5_bond_2
  NIC3: mlx5_bond_3
  NIC4: mlx5_bond_4
  NIC5: mlx5_bond_5
  NIC6: mlx5_bond_6
  NIC7: mlx5_bond_7

ulimit soft: 1048576

**Comment by nannaer** [comment]
Would you be willing to offer me some guidance? I've been troubled by this issue for a long time when deploying DeepSeek V3. Thanks! In this Issue, similar bugs are also mentioned. https://github.com/sgl-project/sglang/issues/6465 @zhyncs @ShangmingCai

**Comment by ShangmingCai** [comment]
Can you try the latest main branch? There are a lot of bugfix lately.

**Comment by nannaer** [comment]
> 您可以尝试最新的 main 分支吗？最近有很多错误修复。

Okay, thank you. I'll give it a try. The branch where multi-machine Decode fails to start was pulled from the main branch three days ago.

**Comment by nannaer** [comment]
> Can you try the latest main branch? There are a lot of bugfix lately.

_**When we just downloaded the latest main branch of SGLang and launched multi-machine Decode, it still hung, but there were some additional error messages. The error information is as follows, which seems to be an issue with GLOO:**_





terminate called after throwing an instance of 'terminate called after throwing an instance of 'terminate called after throwing an instance of 'gloo::EnforceNotMetgloo::EnforceNotMetgloo::EnforceNotMet'
'
'
  what():    what():  [enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 128 vs 8  what():  [enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 128 vs 8
[enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 128 vs 8
terminate called after throwing an instance of '
gloo::EnforceNotMet'
Fatal Python error: Aborted

Fatal Python error: Aborted

Thread 0xFatal Python error:   what():  00007f1b0c1ff640AbortedThread 0x[enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 128 vs 8 (most recent call first):



00007f1292eff640Thread 0x (most recent call first):
  File 00007f6e30dff640 (most recent call first):
"  File Fatal Python error: /usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.pyAborted  File ""/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py

", line "Thread 0x/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py53, line "00007f09013ff640 in 53, line  (most recent call first):
terminate called after throwing an instance of '_recv_msg in 53  File 
gloo::EnforceNotMet_recv_msg in "  File '

_recv_msg/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py"
  File terminate called after throwing an instance of 'terminate called after throwing an instance of '"/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py  File "  what():  gloo::EnforceNotMetgloo::EnforceNotMet, line ""/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py[enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 128 vs 8'
'
53, line /usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py"
 in 161_recv_msg", line   what():    what():   in 
, line 161[enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 128 vs 8Fatal Python error: [enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 128 vs 8_read_thread161  File  in 
Aborted

terminate called after throwing an instance of ' in "_read_thread

  File Fatal Python error: gloo::EnforceNotMet_read_threadFatal Python error: /usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py
Thread 0x"Aborted'

Aborted"  File 00007fd0d85ff640/usr/lib/python3.10/threading.py

  File 

, line "  what():   (most recent call first):
"Thread 0x"00007f4e468ff640161/usr/lib/python3.10/threading.pyThread 0x[enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 128 vs 8, line 
/usr/lib/python3.10/threading.py (most recent call first):
 in "_read_thread  File 00007f5ca73ff640953"  File , line "Fatal Python error: 
 (most recent call first):
 in , line "953/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.pyAborted  File run953  File /usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py in "

"
Thread 0x in ""run, line /usr/lib/python3.10/threading.py  File run/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py00007fbbc49ff640, line 
53""
" (most recent call first):
53 in   File , line /usr/lib/python3.10/threading.py  File , line  in _recv_msg"953""53_recv_msg  File 
/usr/lib/python3.10/threading.py in , line /usr/lib/python3.10/threading.py in 
  File ""run1016"_recv_msg"  File /usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py
, line  in 
, line /usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py""  File 1016_bootstrap_inner1016
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py" in , line  in   File ", line "/usr/lib/python3.10/threading.py_bootstrap_inner53_bootstrap_inner"/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py161, line "
 in 
/usr/lib/python3.10/threading.py" in 161, line   File "_recv_msg, line   File _read_thread in 1016", line 
161"
_read_thread in /usr/lib/python3.10/threading.py973 in /usr/lib/python3.10/threading.py  File   File 
_bootstrap_inner" in _read_thread"""
  File , line _bootstrap
, line /usr/lib/python3.10/threading.py/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py  File "973
  File 973"""/usr/lib/python3.10/threading.py, line  in 
" in , line /usr/lib/python3.10/threading.py"161_bootstrapThread 0x/usr/lib/python3.10/threading.py_bootstrap953", line  in 
00007f1ea8bd6480"
 in 
, line 953_read_thread
 (most recent call first):
, line runThread 0x973 in 
Thread 0x  File 953
00007f71cd00e480 in   File run  File 00007f162f164480 in " (most recent call first):
_bootstrap"
" (most recent call first):
run/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py  File 
/usr/lib/python3.10/threading.py  File /usr/lib/python3.10/threading.py  File 
""
"""  File ", line /usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.pyThread 0x, line /usr/lib/python3.10/threading.py, line "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py2730"00007f0c9d6854801016"953/usr/lib/python3.10/threading.py" in , line  (most recent call first):
 in   File  in , line ", line broadcast2730_bootstrap_inner"run10162730
, line  in 
/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py
 in  in   File   File 1016broadcast  File "_bootstrap_innerbroadcast"" in 
", line 

/usr/lib/python3.10/threading.py/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py_bootstrap_inner  File /usr/lib/python3.10/threading.py2730  File   File ""
"" in "", line , line   File /usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py, line broadcast/usr/lib/python3.10/threading.py/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py811016""973
"" in  in /usr/lib/python3.10/threading.py, line  in 81  File , line , line wrapper_bootstrap_inner"_bootstrap in "97381

, line 
wrapper/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py in  in   File 973

"  File _bootstrapwrapper" in Thread 0x00007f51e2b36480 (most recent call first):
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2730 in broadcast
  File "  File , line "

/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py_bootstrap/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py"81/usr/lib/python3.10/threading.py
  File "
"/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py in "Thread 0x", line 
, line "wrapper, line 00007fd474846480/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py3479Thread 0x81, line 
973 (most recent call first):
" in 00007f6043672480 in 3479  File  in   File , line broadcast_object_list (most recent call first):
wrapper in "_bootstrap3479"
  File 
broadcast_object_list/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py
 in /usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py  File   File "
"
broadcast_object_list"""/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py  File , line Thread 0x
, line /usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py""347900007fbf60c82480  File 2730"", line /usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py in  (most recent call first):
" in , line , line 2730"broadcast_object_list  File /usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.pybroadcast813479 in , line 
""
 in  in broadcast81  File /usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py, line   File wrapperbroadcast_object_list
 in ""81"

  File wrapper/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py, line  in /usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py  File   File ""
"2730wrapper""/workspace/sglang/python/sglang/srt/distributed/parallel_state.py/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py  File , line  in 
, line /usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py"""81broadcast  File 81", line , line /workspace/sglang/python/sglang/srt/distributed/parallel_state.py in 
" in , line 135781"wrapper  File /workspace/sglang/python/sglang/srt/distributed/parallel_state.pywrapper81 in  in 
, line ""
 in in_the_same_node_aswrapper  File 1357/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py, line   File wrapper

" in "1357"
  File   File   File "/workspace/sglang/python/sglang/srt/distributed/parallel_state.pyin_the_same_node_as, line  in /usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py""/workspace/sglang/python/sglang/srt/distributed/parallel_state.py"
81in_the_same_node_as"/workspace/sglang/python/sglang/srt/distributed/device_communicators/custom_all_reduce.py/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line   File  in 
"", line , line 1357"wrapper  File , line , line 34791357 in /workspace/sglang/python/sglang/srt/distributed/device_communicators/custom_all_reduce.py
"1843479 in  in in_the_same_node_as"  File /workspace/sglang/python/sglang/srt/distributed/device_communicators/custom_all_reduce.py in  in broadcast_object_listin_the_same_node_as
, line ""__init__broadcast_object_list

  File 184/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py, line 

  File   File " in "184  File   File ""/workspace/sglang/python/sglang/srt/distributed/device_communicators/custom_all_reduce.py__init__ in ""/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py, line /workspace/sglang/python/sglang/srt/distributed/device_communicators/custom_all_reduce.py"
, line __init__/workspace/sglang/python/sglang/srt/distributed/parallel_state.py/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py"3479"  File 184
"  File ", line  in , line " in , line ", line 81broadcast_object_list184/workspace/sglang/python/sglang/srt/distributed/parallel_state.py__init__291/workspace/sglang/python/sglang/srt/distributed/parallel_state.py81 in 
 in "
 in " in wrapper  File __init__, line   File __init__, line wrapper
"
291"
291
  File /usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py  File  in /workspace/sglang/python/sglang/srt/distributed/parallel_state.py  File  in   File """__init__""__init__"/workspace/sglang/python/sglang/srt/distributed/parallel_state.py, line /workspace/sglang/python/sglang/srt/distributed/parallel_state.py
, line /workspace/sglang/python/sglang/srt/distributed/parallel_state.py
/workspace/sglang/python/sglang/srt/distributed/parallel_state.py"81"  File 291"  File " in , line , line " in , line ", line wrapper1357291/workspace/sglang/python/sglang/srt/distributed/parallel_state.py__init__1000/workspace/sglang/python/sglang/srt/distributed/parallel_state.py1357
 in  in "
 in " in   File in_the_same_node_as__init__, line   File init_model_parallel_group, line in_the_same_node_as

"1000"
1000
  File   File /workspace/sglang/python/sglang/srt/distributed/parallel_state.py in /workspace/sglang/python/sglang/srt/distributed/parallel_state.py in   File   File """init_model_parallel_group", line init_model_parallel_group""/workspace/sglang/python/sglang/srt/distributed/device_communicators/custom_all_reduce.py/workspace/sglang/python/sglang/srt/distributed/parallel_state.py
, line 1357
/workspace/sglang/python/sglang/srt/distributed/device_communicators/custom_all_reduce.py/workspace/sglang/python/sglang/srt/distributed/parallel_state.py""  File , line 1000 in   File "", line "1000 in in_the_same_node_as", line , line 184/workspace/sglang/python/sglang/srt/distributed/parallel_state.py in init_model_parallel_group
/workspace/sglang/python/sglang/srt/distributed/parallel_state.py1841177 in "__init__init_model_parallel_group
  File " in , line  in , line 

  File "__init__1177initialize_model_parallel1177  File   File "/workspace/sglang/python/sglang/srt/distributed/device_communicators/custom_all_reduce.py
 in 
 in ""/workspace/sglang/python/sglang/srt/distributed/parallel_state.py"  File initialize_model_parallel  File initialize_model_parallel"/workspace/sglang/python/sglang/srt/distributed/parallel_state.py/workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line "

/workspace/sglang/python/sglang/srt/model_executor/model_runner.py"", line 184/workspace/sglang/python/sglang/srt/distributed/parallel_state.py  File   File ", line , line 1177 in """, line 2911177 in __init__, line /workspace/sglang/python/sglang/srt/model_executor/model_runner.py/workspace/sglang/python/sglang/srt/model_executor/model_runner.py472 in  in initialize_model_parallel
291  File "" in __init__
initialize_model_parallel in ", line , line init_torch_distributed
  File 
__init__"/workspace/sglang/python/sglang/srt/distributed/parallel_state.py472472
  File   File 
/workspace/sglang/python/sglang/srt/model_executor/model_runner.py" in  in   File "  File "", line init_torch_distributedinit_torch_distributed"/workspace/sglang/python/sglang/srt/distributed/parallel_state.py"/workspace/sglang/python/sglang/srt/model_executor/model_runner.py, line 291

/workspace/sglang/python/sglang/srt/model_executor/model_runner.py"/workspace/sglang/python/sglang/srt/distributed/parallel_state.py"472 in   File   File ", line ", line  in __init__"", line 1000, line 472init_torch_distributed
/workspace/sglang/python/sglang/srt/model_executor/model_runner.py/workspace/sglang/python/sglang/srt/model_executor/model_runner.py228 in 1000 in 
  File "" in init_model_parallel_group in init_torch_distributed  File ", line , line __init__
init_model_parallel_group
"/workspace/sglang/python/sglang/srt/distributed/parallel_state.py228"228
 in   File 
/workspace/sglang/python/sglang/srt/model_executor/model_runner.py  File  in , line __init__  File "  File ""__init__1000
"  File /workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line /workspace/sglang/python/sglang/srt/model_executor/model_runner.py
 in /workspace/sglang/python/sglang/srt/managers/tp_worker.py""/workspace/sglang/python/sglang/srt/distributed/parallel_state.py228"  File init_model_parallel_group"/workspace/sglang/python/sglang/srt/managers/tp_worker.py, line " in , line "
", line 1177, line __init__228/workspace/sglang/python/sglang/srt/managers/tp_worker.py  File , line 78 in 1177
 in ""78 in initialize_model_parallel in   File __init__, line /workspace/sglang/python/sglang/srt/distributed/parallel_state.py in __init__
initialize_model_parallel"

78"__init__
  File /workspace/sglang/python/sglang/srt/managers/tp_worker.py  File   File  in , line 
  File """"__init__1177  File "/workspace/sglang/python/sglang/srt/model_executor/model_runner.py/workspace/sglang/python/sglang/srt/model_executor/model_runner.py, line /workspace/sglang/python/sglang/srt/managers/tp_worker.py
 in "/workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py""78, line "472  File initialize_model_parallel/workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line  in  in , line "
", line 472__init__init_torch_distributed78/workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py  File , line 64 in 

 in "64" in init_torch_distributed  File   File __init__, line  in /workspace/sglang/python/sglang/srt/model_executor/model_runner.py__init__
"  File 
"64__init__"
/workspace/sglang/python/sglang/srt/model_executor/model_runner.py"/workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py  File  in 
, line   File ", line 228/workspace/sglang/python/sglang/srt/model_executor/model_runner.py"__init__"  File 472" in ", line 
/workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py" in /workspace/sglang/python/sglang/srt/managers/scheduler.py__init__", line 64"  File /workspace/sglang/python/sglang/srt/managers/scheduler.pyinit_torch_distributed
, line 228 in  in , line ""
  File 280__init____init__64/workspace/sglang/python/sglang/srt/managers/scheduler.py, line   File " in 

 in "280"/workspace/sglang/python/sglang/srt/managers/tp_worker.py__init__  File   File __init__, line  in /workspace/sglang/python/sglang/srt/model_executor/model_runner.py"
""
280  File __init__", line /workspace/sglang/python/sglang/srt/managers/scheduler.py  File /workspace/sglang/python/sglang/srt/managers/tp_worker.py in 
", line 78"""__init__  File /workspace/sglang/python/sglang/srt/managers/scheduler.py228 in , line /workspace/sglang/python/sglang/srt/managers/scheduler.py, line 
"" in __init__280"78/workspace/sglang/python/sglang/srt/managers/scheduler.py  File , line __init__
 in , line  in ""280
__init__  File 2345__init__, line /workspace/sglang/python/sglang/srt/managers/scheduler.py in 
  File " in 
2345"__init__, line "  File /workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.pyrun_scheduler_process  File  in 
2345/workspace/sglang/python/sglang/srt/managers/tp_worker.py""
run_scheduler_process in   File ""/workspace/sglang/python/sglang/srt/managers/scheduler.py, line   File 
"run_scheduler_process/workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py, line "64"/workspace/sglang/python/sglang/srt/managers/scheduler.py  File 
"78 in , line /usr/lib/python3.10/multiprocessing/process.py""  File  in , line __init__2345"/usr/lib/python3.10/multiprocessing/process.py, line "__init__64
 in , line "2345/usr/lib/python3.10/multiprocessing/process.py
 in   File run_scheduler_process108, line  in "__init__
"  File  in 108, line run_scheduler_process
/workspace/sglang/python/sglang/srt/managers/scheduler.py  File run in 108
""  File 
"run in   File , line /usr/lib/python3.10/multiprocessing/process.py"  File /workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py
run"280"/workspace/sglang/python/sglang/srt/managers/scheduler.py"/usr/lib/python3.10/multiprocessing/process.py"  File 
/usr/lib/python3.10/multiprocessing/process.py in , line """  File , line "__init__108, line , line /usr/lib/python3.10/multiprocessing/process.py"64
, line  in   File 280314"/usr/lib/python3.10/multiprocessing/process.py in 108run" in  in , line "__init__ in 
/workspace/sglang/python/sglang/srt/managers/scheduler.py__init___bootstrap314, line 
run  File "

 in 314  File 
", line _bootstrap  File  in   File "  File /usr/lib/python3.10/multiprocessing/process.py2345
"_bootstrap"/workspace/sglang/python/sglang/srt/managers/scheduler.py"" in   File /usr/lib/python3.10/multiprocessing/spawn.py
/workspace/sglang/python/sglang/srt/managers/scheduler.py"/usr/lib/python3.10/multiprocessing/process.py, line run_scheduler_process"""  File , line "314
/usr/lib/python3.10/multiprocessing/spawn.py, line "280, line , line  in   File "129/usr/lib/python3.10/multiprocessing/spawn.py in 2345314_bootstrap", line  in "__init__ in  in 
/usr/lib/python3.10/multiprocessing/process.py129_main, line 
run_scheduler_process_bootstrap  File " in 
129
  File 
", line _main  File  in "/usr/lib/python3.10/multiprocessing/spawn.py  File 108  File 
"_main/workspace/sglang/python/sglang/srt/managers/scheduler.py"" in "/usr/lib/python3.10/multiprocessing/spawn.py  File 
", line /usr/lib/python3.10/multiprocessing/spawn.pyrun/usr/lib/python3.10/multiprocessing/process.py""  File 129", line 
", line /usr/lib/python3.10/multiprocessing/spawn.py" in , line 2345  File , line 116"/usr/lib/python3.10/multiprocessing/spawn.py_main129 in "108 in , line "
 in run_scheduler_process/usr/lib/python3.10/multiprocessing/process.py in spawn_main116, line   File _main
"run
 in 116"
  File , line 
  File spawn_main in /usr/lib/python3.10/multiprocessing/spawn.py  File "314"  File 
spawn_main""/usr/lib/python3.10/multiprocessing/process.py in <string>"  File 
, line /usr/lib/python3.10/multiprocessing/spawn.py"_bootstrap"/usr/lib/python3.10/multiprocessing/process.py"116  File ", line 
, line "<string> in ", line 1081 in   File , line "spawn_main<string>116 in run"314, line 
" in <module>
/usr/lib/python3.10/multiprocessing/spawn.py in 1  File , line spawn_main
  File "_bootstrap in "1
", line 
<module><string> in   File /usr/lib/python3.10/multiprocessing/process.py129
  File "<module>"" in ", line 
<string>, line _main/usr/lib/python3.10/multiprocessing/spawn.py1"314
" in , line  in   File , line <module>1_bootstrap"129
 in 
/usr/lib/python3.10/multiprocessing/spawn.py in <module>"  File _main
, line "
116/usr/lib/python3.10/multiprocessing/spawn.py  File  in ""spawn_main
Extension modules: , line /usr/lib/python3.10/multiprocessing/spawn.py
numpy._core._multiarray_umath129"  File  in , line "_main116<string>
Extension modules: 
 in "numpy._core._multiarray_umathspawn_main  File , , line 
"numpy.linalg._umath_linalg1/usr/lib/python3.10/multiprocessing/spawn.py  File 
Extension modules:  in ""numpy._core._multiarray_umath<module>, line <string>, 
116"numpy.linalg._umath_linalg in , line 
Extension modules: 
Extension modules: spawn_main1numpy._core._multiarray_umathnumpy._core._multiarray_umath
,  in   File "<string>", line 1numpy.linalg._umath_linalg<module> in 
<module>
, , numpy.linalg._umath_linalgnumpy.linalg._umath_linalg, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md
Extension modules: numpy._core._multiarray_umath, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, numpy.linalg._umath_linalg, charset_normalizer.md, charset_normalizer.md
Extension modules: , , numpy._core._multiarray_umathcharset_normalizer.mdrequests.packages.charset_normalizer.md, requests.packages.charset_normalizer.md, , requests.packages.chardet.mdrequests.packages.chardet.md
Extension modules: numpy._core._multiarray_umath, requests.packages.charset_normalizer.md, requests.packages.chardet.md, numpy.linalg._umath_linalg, numpy.linalg._umath_linalg, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, charset_normalizer.md, multidict._multidict, requests.packages.charset_normalizer.md, , yarl._quoting_crequests.packages.chardet.md, propcache._helpers_c, aiohttp._http_writer, aiohttp._http_parser, , multidict._multidictaiohttp._websocket.mask, aiohttp._websocket.reader_c, yarl._quoting_c, multidict._multidict, , multidict._multidictpropcache._helpers_c, yarl._quoting_c, , multidict._multidict, , yarl._quoting_caiohttp._http_writer, uvloop.looppropcache._helpers_c, , aiohttp._http_parserpropcache._helpers_c, yarl._quoting_c, , aiohttp._websocket.maskaiohttp._http_writer, propcache._helpers_c, , aiohttp._websocket.reader_c, aiohttp._http_writeraiohttp._http_parser, aiohttp._http_parser, aiohttp._websocket.mask, aiohttp._http_writer, aiohttp._websocket.mask, aiohttp._websocket.reader_c, , aiohttp._http_parseraiohttp._websocket.reader_c, multidict._multidict, aiohttp._websocket.mask, , aiohttp._websocket.reader_ctorch._C, , yarl._quoting_c, torch._C._dynamo.autograd_compileruvloop.loop, torch._C._dynamo.eval_frame, propcache._helpers_c, torch._C._dynamo.guards, , torch._C._dynamo.utilsuvloop.loop, torch._C._fft, uvloop.loop, , torch._C._linalgaiohttp._http_writer, , uvloop.looptorch._C._nested, aiohttp._http_parser, torch._C._nn, aiohttp._websocket.mask, torch._C._sparse, , torch._C._specialaiohttp._websocket.reader_c, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C, torch._C._dynamo.guards, torch._C._dynamo.utils, , torch._C._dynamo.autograd_compiler, torch._C, , torch._C._fftuvloop.loop, , , multidict._multidicttorch._C._dynamo.eval_frame, torch._Ctorch._C._dynamo.autograd_compilertorch._C._linalg, , , torch._C._dynamo.guards, torch._C._dynamo.eval_frametorch._C._nestedtorch._C._dynamo.autograd_compiler, , , , torch._C._dynamo.utils, torch._C._nntorch._C._dynamo.guardsyarl._quoting_ctorch._C._dynamo.eval_frame, , , torch._C._ffttorch._C._sparse, torch._C._dynamo.utilstorch._C._dynamo.guards, , , , , propcache._helpers_ctorch._C._linalgtorch._C._specialtorch._C._ffttorch._C._dynamo.utils, , , torch._C, torch._C._nestedtorch._C._linalgtorch._C._fft, , , torch._C._dynamo.autograd_compiler, , aiohttp._http_writertorch._C._nestedtorch._C._nntorch._C._linalg, , , , torch._C._dynamo.eval_frame, torch._C._nnaiohttp._http_parsertorch._C._sparsetorch._C._nested, , , , , , multidict._multidicttorch._C._dynamo.guardstorch._C._nntorch._C._sparseaiohttp._websocket.masktorch._C._special, , , torch._C._dynamo.utilstorch._C._sparsetorch._C._special, , , , aiohttp._websocket.reader_ctorch._C._ffttorch._C._specialyarl._quoting_c, torch._C._linalg, torch._C._nested, propcache._helpers_c, torch._C._nn, torch._C._sparse, torch._C._special, aiohttp._http_writer, aiohttp._http_parser, uvloop.loop, aiohttp._websocket.mask, aiohttp._websocket.reader_c, uvloop.loop, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, psutil._psutil_linux, torch._C._sparse, , torch._C._specialpsutil._psutil_posix, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, zmq.backend.cython._zmq, PIL._imaging, setproctitle._setproctitle, yaml._yaml, regex._regex, markupsafe._speedups, psutil._psutil_linux, psutil._psutil_posix, PIL._imagingft, psutil._psutil_linux, psutil._psutil_linux, psutil._psutil_posix, , psutil._psutil_posixpsutil._psutil_linux, psutil._psutil_posix, numpy.random._common, numpy.random.bit_generator, , zmq.backend.cython._zmqnumpy.random._bounded_integers, psutil._psutil_linux, numpy.random._mt19937, psutil._psutil_posix, numpy.random.mtrand, , numpy.random._philoxPIL._imaging, numpy.random._pcg64, , setproctitle._setproctitlenumpy.random._sfc64, numpy.random._generator, yaml._yaml, zmq.backend.cython._zmq, zmq.backend.cython._zmq, sentencepiece._sentencepiece, zmq.backend.cython._zmq, , PIL._imagingcuda.bindings._lib.utils, PIL._imaging, , cuda.bindings._bindings.cydriversetproctitle._setproctitle, , , , PIL._imagingsetproctitle._setproctitlezmq.backend.cython._zmqcuda.bindings.cydriver, , yaml._yamlregex._regex, cuda.bindings.driver, setproctitle._setproctitle, cuda.bindings._bindings.cynvrtc, regex._regex, , yaml._yaml, markupsafe._speedups, cuda.bindings.cynvrtc, PIL._imagingmarkupsafe._speedups, , cuda.bindings.nvrtcregex._regex, , setproctitle._setproctitle, yaml._yamlmarkupsafe._speedups, , yaml._yamlPIL._imagingft, regex._regex, PIL._imagingft, , markupsafe._speedupsPIL._imagingft, psutil._psutil_linux, PIL._imagingft, , psutil._psutil_posixregex._regex, numpy.random._common, , markupsafe._speedupsnumpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._common, numpy.random._mt19937, numpy.random.bit_generator, numpy.random.mtrand, , msgspec._corenumpy.random._bounded_integers, numpy.random._philox, numpy.random._mt19937, , numpy.random._pcg64, numpy.random._commonnumpy.random.mtrand, numpy.random._sfc64, , numpy.random.bit_generatornumpy.random._philox, numpy.random._generator, , numpy.random._bounded_integersnumpy.random._pcg64, , numpy.random._mt19937numpy.random._sfc64, , PIL._imagingft (total: , , psutil._psutil_linux51numpy.random.mtrandnumpy.random._generator, )sentencepiece._sentencepiece, , 
, numpy.random._philoxpsutil._psutil_posixzmq.backend.cython._zmq, , cuda.bindings._lib.utilsnumpy.random._pcg64, , , sentencepiece._sentencepiececuda.bindings._bindings.cydrivernumpy.random._sfc64, , numpy.random._generatorcuda.bindings.cydriver, , cuda.bindings._lib.utils, PIL._imagingcuda.bindings.driver, cuda.bindings._bindings.cydriver, cuda.bindings._bindings.cynvrtc, , cuda.bindings.cydriver, cuda.bindings.cynvrtc, setproctitle._setproctitle, , sentencepiece._sentencepiececuda.bindings.drivercuda.bindings.nvrtc, cuda.bindings._bindings.cynvrtc, , cuda.bindings._lib.utilscuda.bindings.cynvrtc, , cuda.bindings._bindings.cydrivercuda.bindings.nvrtc, yaml._yaml, cuda.bindings.cydriver, cuda.bindings.driver, zmq.backend.cython._zmq, cuda.bindings._bindings.cynvrtc, cuda.bindings.cynvrtc, cuda.bindings.nvrtc, PIL._imaging, setproctitle._setproctitle, regex._regex, markupsafe._speedups, yaml._yaml, msgspec._core, msgspec._core, PIL._imagingft (total: 51)
,  (total: msgspec._core51)
, regex._regex, numpy.random._common, numpy.random.bit_generator, markupsafe._speedups, numpy.random._bounded_integers, numpy.random._mt19937 (total: , 51numpy.random.mtrand)
, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, , PIL._imagingftnumpy.random._generator, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, sentencepiece._sentencepiece, cuda.bindings._lib.utils, cuda.bindings._bindings.cydriver, cuda.bindings.cydriver, cuda.bindings.driver, cuda.bindings._bindings.cynvrtc, cuda.bindings.cynvrtc, cuda.bindings.nvrtc, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, , numpy.random._philoxsentencepiece._sentencepiece, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, cuda.bindings._lib.utils, cuda.bindings._bindings.cydriver, cuda.bindings.cydriver, cuda.bindings.driver, cuda.bindings._bindings.cynvrtc, cuda.bindings.cynvrtc, cuda.bindings.nvrtc, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, , msgspec._corenumpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator (total: 51)
, sentencepiece._sentencepiece, msgspec._core, cuda.bindings._lib.utils, cuda.bindings._bindings.cydriver, cuda.bindings.cydriver (total: , 51cuda.bindings.driver)
, cuda.bindings._bindings.cynvrtc, cuda.bindings.cynvrtc, cuda.bindings.nvrtc, sentencepiece._sentencepiece, cuda.bindings._lib.utils, cuda.bindings._bindings.cydriver, cuda.bindings.cydriver, cuda.bindings.driver, cuda.bindings._bindings.cynvrtc, cuda.bindings.cynvrtc, cuda.bindings.nvrtc, msgspec._core, msgspec._core (total: 51)
 (total: 51)
[2025-05-31 04:04:28] DataParallelController hit an exception: Traceback (most recent call last):
  File "/workspace/sglang/python/sglang/srt/managers/data_parallel_controller.py", line 313, in run_data_parallel_controller_process
    controller = DataParallelController(server_args, port_args)
  File "/workspace/sglang/python/sglang/srt/managers/data_parallel_controller.py", line 91, in __init__
    dp_port_args = self.launch_dp_attention_schedulers(server_args, port_args)
  File "/workspace/sglang/python/sglang/srt/managers/data_parallel_controller.py", line 169, in launch_dp_attention_schedulers
    self.launch_tensor_parallel_group(server_args, port_args, 0, None)
  File "/workspace/sglang/python/sglang/srt/managers/data_parallel_controller.py", line 254, in launch_tensor_parallel_group
    scheduler_info.append(scheduler_pipe_readers[i].recv())
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by nannaer** [comment]
> Can you try the latest main branch? There are a lot of bugfix lately.

I have written a simple test script to test GLOO and PyTorch, and I am certain that this issue is not caused by version incompatibility between GLOO and PyTorch.

**Comment by ShangmingCai** [comment]
@ch-wan It seems something weird happens in the module of the DP controller, any idea about this?

**Comment by ShangmingCai** [comment]
> > 您可以尝试最新的 main 分支吗？最近有很多错误修复。
> 
> Okay, thank you. I'll give it a try. The branch where multi-machine Decode fails to start was pulled from the main branch three days ago.

@nannaer Please make sure the Prefill and Decode machines are using the same version of SGLang codebase. Maybe try removing and reinstalling them or using a new venv?

**Comment by nannaer** [comment]
> > > 您可以尝试最新的 main 分支吗？最近有很多错误修复。
> > 
> > 
> > Okay, thank you. I'll give it a try. The branch where multi-machine Decode fails to start was pulled from the main branch three days ago.
> 
> [@nannaer](https://github.com/nannaer) Please make sure the Prefill and Decode machines are using the same version of SGLang codebase. Maybe try removing and reinstalling them or using a new venv?

![Image](https://github.com/user-attachments/assets/96b2c95a-ca9c-4856-b5d6-42d614c13493)

As shown in the figure, the GPU resource utilization on both machines is fully loaded, but it gets stuck at a certain step before loading the weights.

I confirm that the Decode instance is using the latest codebase, and I haven't started the Prefill instance. From the startup command provided in the issue https://github.com/sgl-project/sglang/issues/6017, I assume that starting the Decode instance and the Prefill instance should be independent. Currently, the multi-machine Decode instances fail to start, getting stuck before loading the model weights. I believe this is an issue independent of whether the Prefill instance is started or not.

**Comment by nannaer** [comment]
> > > 您可以尝试最新的 main 分支吗？最近有很多错误修复。
> > 
> > 
> > Okay, thank you. I'll give it a try. The branch where multi-machine Decode fails to start was pulled from the main branch three days ago.
> 
> [@nannaer](https://github.com/nannaer) Please make sure the Prefill and Decode machines are using the same version of SGLang codebase. Maybe try removing and reinstalling them or using a new venv?

I have resolved the GLOO error, but launching Decode on two machines still freezes. I used py-spy to check where the process is stuck, and the results are as follows:

sglang::scheduler_DP8_TP8 到  sglang::scheduler_DP15_TP15

![Image](https://github.com/user-attachments/assets/b36b4963-05c3-428b-9a57-cef346f06d6c)

**Comment by nannaer** [comment]
> > > > 您可以尝试最新的 main 分支吗？最近有很多错误修复。
> > > 
> > > 
> > > Okay, thank you. I'll give it a try. The branch where multi-machine Decode fails to start was pulled from the main branch three days ago.
> > 
> > 
> > [@nannaer](https://github.com/nannaer) Please make sure the Prefill and Decode machines are using the same version of SGLang codebase. Maybe try removing and reinstalling them or using a new venv?
> 
I have resolved the GLOO error, but launching Decode on two machines still hang. I used py-spy to check where the process is stuck, and the results are as follows:
> 
> Sub Node: from sglang::scheduler_DP8_TP8 to sglang::scheduler_DP15_TP15
> 
> ![Image](https://github.com/user-attachments/assets/b36b4963-05c3-428b-9a57-cef346f06d6c)

According to the output of py-spy, it appears to be stuck at initializing PyNcclCommunicator in the following diagram.
> ![Image](https://github.com/user-attachments/assets/4137f47e-288b-4e94-8423-6a49cf712138)
> ![Image](https://github.com/user-attachments/assets/ecc8c695-ded0-40cd-953b-da5e0295e9d7)

**Comment by acelyc111** [comment]
I got the same issuse in v0.4.7 version, feedbacked in [Slack](https://sgl-fru7574.slack.com/archives/C07EFURPNN9/p1750056402789099).
cc @ShangmingCai

**Comment by acelyc111** [comment]
After I set `--disable-overlap-schedule`, it seems this issue gone.

**Comment by acelyc111** [comment]
The stack looks like:
```
Thread 704 (active): "MainThread"
    synchronize (torch/cuda/streams.py:227)
    resolve_last_batch_result (tp_worker_overlap_thread.py:193)
    process_batch_result (scheduler.py:1631)
    event_loop_overlap_disagg_decode (decode.py:621)
    decorate_context (torch/utils/_contextlib.py:116)
    run_scheduler_process (scheduler.py:2515)
    run (multiprocessing/process.py:108)
    _bootstrap (multiprocessing/process.py:314)
    _main (multiprocessing/spawn.py:135)
    spawn_main (multiprocessing/spawn.py:122)
    <module> (<string>:1)
```

It seems related to this change https://github.com/sgl-project/sglang/pull/5788, I'm not sure, could you please help to take a look? @hnyls2002

**Comment by acelyc111** [comment]
> I got the same issuse in v0.4.7 version, feedbacked in [Slack](https://sgl-fru7574.slack.com/archives/C07EFURPNN9/p1750056402789099). cc [@ShangmingCai](https://github.com/ShangmingCai)

It seems not a same issue according to the stack, I've created an new issue https://github.com/sgl-project/sglang/issues/7254

**Comment by Rain-xyy** [comment]
I encounter the same problem, have you solved it?

**Comment by zhaotyer** [comment]
https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#pci-access-control-services-acs
try this
