### ISSUE TITLE
[Bug] RTX 5090: RMSNorm failed with error code no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by celsowm** [sgl-project/sglang#7249]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

user@WKS-LEVI-02:~/sglang$ python3 -m sglang.launch_server \
>  --model-path  RedHatAI/Mistral-Small-24B-Instruct-2501-FP8-dynamic \
> --quantization w8a8_fp8 \
>   --port 8081 \
> --context-length 25000
[2025-06-16 16:07:27] server_args=ServerArgs(model_path='RedHatAI/Mistral-Small-24B-Instruct-2501-FP8-dynamic', tokenizer_path='RedHatAI/Mistral-Small-24B-Instruct-2501-FP8-dynamic', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', trust_remote_code=False, dtype='auto', kv_cache_dtype='auto', quantization='w8a8_fp8', quantization_param_path=None, context_length=25000, device='cuda', served_model_name='RedHatAI/Mistral-Small-24B-Instruct-2501-FP8-dynamic', chat_template=None, completion_template=None, is_embedding=False, enable_multimodal=None, revision=None, impl='auto', host='127.0.0.1', port=8081, mem_fraction_static=0.88, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='fcfs', schedule_conservativeness=1.0, cpu_offload_gb=0, page_size=1, tp_size=1, pp_size=1, max_micro_batch_size=None, stream_interval=1, stream_output=False, random_seed=690219957, constrained_json_whitespace_pattern=None, watchdog_timeout=300, dist_timeout=None, download_dir=None, base_gpu_id=0, gpu_id_step=1, log_level='info', log_level_http=None, log_requests=False, log_requests_level=0, show_time_cost=False, enable_metrics=False, bucket_time_to_first_token=None, bucket_e2e_request_latency=None, bucket_inter_token_latency=None, collect_tokens_histogram=False, decode_log_interval=40, enable_request_time_stats_logging=False, kv_events_config=None, api_key=None, file_storage_path='sglang_storage', enable_cache_report=False, reasoning_parser=None, dp_size=1, load_balance_method='round_robin', ep_size=1, dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', preferred_sampling_params=None, lora_paths=None, max_loras_per_batch=8, lora_backend='triton', attention_backend=None, sampling_backend='flashinfer', grammar_backend='xgrammar', speculative_algorithm=None, speculative_draft_model_path=None, speculative_num_steps=None, speculative_eagle_topk=None, speculative_num_draft_tokens=None, speculative_accept_threshold_single=1.0, speculative_accept_threshold_acc=1.0, speculative_token_map=None, enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, disable_radix_cache=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, enable_nccl_nvls=False, enable_tokenizer_batch_encode=False, disable_outlines_disk_cache=False, disable_custom_all_reduce=False, enable_mscclpp=False, disable_overlap_schedule=False, enable_mixed_chunk=False, enable_dp_attention=False, enable_dp_lm_head=False, enable_two_batch_overlap=False, enable_ep_moe=False, enable_deepep_moe=False, deepep_mode='auto', ep_num_redundant_experts=0, ep_dispatch_algorithm='static', init_expert_location='trivial', enable_eplb=False, eplb_algorithm='auto', eplb_rebalance_num_iterations=1000, eplb_rebalance_layers_per_chunk=None, expert_distribution_recorder_mode=None, expert_distribution_recorder_buffer_size=1000, enable_expert_distribution_metrics=False, deepep_config=None, enable_torch_compile=False, torch_compile_max_bs=32, cuda_graph_max_bs=None, cuda_graph_bs=None, torchao_config='', enable_nan_detection=False, enable_p2p_check=False, triton_attention_reduce_in_fp32=False, triton_attention_num_kv_splits=8, num_continuous_decode_steps=1, delete_ckpt_after_loading=False, enable_memory_saver=False, allow_auto_truncate=False, enable_custom_logit_processor=False, tool_call_parser=None, enable_hierarchical_cache=False, hicache_ratio=2.0, hicache_size=0, hicache_write_policy='write_through_selective', flashinfer_mla_disable_ragged=False, warmups=None, moe_dense_tp_size=None, disable_shared_experts_fusion=False, disable_chunked_prefix_cache=False, disable_fast_image_processor=False, mm_attention_backend=None, debug_tensor_dump_output_folder=None, debug_tensor_dump_input_file=None, debug_tensor_dump_inject=False, disaggregation_mode='null', disaggregation_bootstrap_port=8998, disaggregation_transfer_backend='mooncake', disaggregation_ib_device=None, pdlb_url=None)
[2025-06-16 16:07:28] Infer the chat template name from the model path and obtain the result: mistral.
[2025-06-16 16:07:31] Attention backend not set. Use flashinfer backend by default.
[2025-06-16 16:07:31] Init torch distributed begin.
[W616 16:07:31.158919108 ProcessGroupNCCL.cpp:972] Warning: TORCH_NCCL_AVOID_RECORD_STREAMS is the default now, this environment variable is thus deprecated. (function operator())
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[2025-06-16 16:07:31] Init torch distributed ends. mem usage=0.00 GB
[2025-06-16 16:07:31] Load weight begin. avail mem=30.13 GB
[2025-06-16 16:07:31] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/6 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  17% Completed | 1/6 [00:00<00:02,  1.90it/s]
Loading safetensors checkpoint shards:  33% Completed | 2/6 [00:01<00:02,  1.86it/s]
Loading safetensors checkpoint shards:  50% Completed | 3/6 [00:01<00:01,  1.85it/s]
Loading safetensors checkpoint shards:  67% Completed | 4/6 [00:02<00:01,  1.98it/s]
Loading safetensors checkpoint shards:  83% Completed | 5/6 [00:02<00:00,  1.92it/s]
Loading safetensors checkpoint shards: 100% Completed | 6/6 [00:02<00:00,  2.46it/s]
Loading safetensors checkpoint shards: 100% Completed | 6/6 [00:02<00:00,  2.14it/s]

[2025-06-16 16:07:35] Load weight end. type=MistralForCausalLM, dtype=torch.bfloat16, avail mem=6.90 GB, mem usage=23.23 GB.
[2025-06-16 16:07:35] KV Cache is allocated. #tokens: 21456, K size: 1.64 GB, V size: 1.64 GB
[2025-06-16 16:07:35] Memory pool end. avail mem=3.36 GB
[2025-06-16 16:07:35] Capture cuda graph begin. This can take up to several minutes. avail mem=2.85 GB
[2025-06-16 16:07:35] Capture cuda graph bs [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160]
Capturing batches (avail_mem=2.84 GB):   0%|             | 0/23 [00:00<?, ?it/s]
[2025-06-16 16:07:35] Scheduler hit an exception: Traceback (most recent call last):
  File "/home/user/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 305, in __init__
    self.capture()
  File "/home/user/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 374, in capture
    ) = self.capture_one_batch_size(bs, forward)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 502, in capture_one_batch_size
    run_once()
  File "/home/user/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 490, in run_once
    logits_output_or_pp_proxy_tensors = forward(
                                        ^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/models/llama.py", line 457, in forward
    hidden_states = self.model(
                    ^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/models/llama.py", line 334, in forward
    hidden_states, residual = layer(
                              ^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/models/llama.py", line 255, in forward
    hidden_states = self.input_layernorm(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/custom_op.py", line 53, in forward
    return self._forward_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/layers/layernorm.py", line 66, in forward_cuda
    out = rmsnorm(x, self.weight.data, self.variance_epsilon)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/sgl_kernel/elementwise.py", line 44, in rmsnorm
    torch.ops.sgl_kernel.rmsnorm.default(out, input, weight, eps, enable_pdl)
  File "/home/user/.local/lib/python3.12/site-packages/torch/_ops.py", line 818, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: RMSNorm failed with error code no kernel image is available for execution on the device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/sglang/python/sglang/srt/managers/scheduler.py", line 2490, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, pp_rank, dp_rank)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/managers/scheduler.py", line 282, in __init__
    self.tp_worker = TpWorkerClass(
                     ^^^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 64, in __init__
    self.worker = TpModelWorker(
                  ^^^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/managers/tp_worker.py", line 78, in __init__
    self.model_runner = ModelRunner(
                        ^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/model_executor/model_runner.py", line 212, in __init__
    self.initialize(min_per_gpu_memory)
  File "/home/user/sglang/python/sglang/srt/model_executor/model_runner.py", line 287, in initialize
    self.init_cuda_graphs()
  File "/home/user/sglang/python/sglang/srt/model_executor/model_runner.py", line 1138, in init_cuda_graphs
    self.cuda_graph_runner = CudaGraphRunner(self)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 307, in __init__
    raise Exception(
Exception: Capture cuda graph failed: RMSNorm failed with error code no kernel image is available for execution on the device
Possible solutions:
1. set --mem-fraction-static to a smaller value (e.g., 0.8 or 0.7)
2. set --cuda-graph-max-bs to a smaller value (e.g., 16)
3. disable torch compile by not using --enable-torch-compile
4. disable CUDA graph by --disable-cuda-graph. (Not recommended. Huge performance loss)
Open an issue on GitHub https://github.com/sgl-project/sglang/issues/new/choose

### Reproduction

python3 -m sglang.launch_server \
  --model-path RedHatAI/Mistral-Small-24B-Instruct-2501-FP8-dynamic \
  --quantization w8a8_fp8 \
  --port 8081 \
  --context-length 25000

### Environment

🖥️ Environment

Model: RedHatAI/Mistral-Small-24B-Instruct-2501-FP8-dynamic

Quantization: w8a8_fp8

GPU: NVIDIA RTX 5090

CUDA: 12.8

PyTorch: 2.8.0.dev20250616+cu128

Python: 3.12.3

OS: Ubuntu 22.04

**Comment by fzyzcjy** [comment]
Replied in https://github.com/sgl-project/sglang/issues/7227#issuecomment-2978577643

**Comment by makjaveli** [comment]
This is happening in version 0.4.7 and there was no related code change or fix provided. Why is this closed? It also has little to do with #7227 as comented above.

The stated error is the default behaviour when exectuting sglang on a Pro 6000 Blackwell or RTX 5090. Sglang 0.4.7 is not working on Pro 6000 Blackwell at all.

**Comment by fzyzcjy** [comment]
For blackwell need to get sgl-kernel wheel from that place

**Comment by makjaveli** [comment]
ok, thank you! I can confirm that PRO 6000 Blackwell/RTX 5090 can run Llama3 with fp16 weights when installing the sg-kernerl 0.1.9 through:

pip3 install https://github.com/sgl-project/whl/releases/download/v0.1.9/sgl_kernel-0.1.9+cu128-cp39-abi3-manylinux2014_x86_64.whl

With sglang 0.4.7 tagged branch the SGL_ENABLE_JIT_DEEPGEMM=0 has to be set, with 0.4.7post1 (current main) the default seems to be with disabled DeepGemm.

Support for Blackwell is still quite shaky and release note for 0.4.7 is a bit false advertisement:

"Full Blackwell support for DeepSeek V3/R1, Llama 4, and Qwen 3. Further optimizations are underway."

Llama4 does not work on a 6000 Blackwell, as there seems to be issues with the block_sizes and shared memory limit. Will try to patch. 

But for me this issue also can be closed now. Thank you for your help.

**Comment by YUNQIUGUO** [comment]
hey I am encountering a same error still even with installing the latest sglang (0.4.9 - released 4 days ago). 

does the pip installed 0.4.9 wheel sgl-kernel contain symbols compatible with sm_100a or not?

Wondering if the issue has been fixed and thanks in advance!

*The model I am running is llama4 maverick fp8

**Comment by Qinghao-Hu** [comment]
> hey I am encountering a same error still even with installing the latest sglang (0.4.9 - released 4 days ago).
> 
> does the pip installed 0.4.9 wheel sgl-kernel contain symbols compatible with sm_100a or not?
> 
> Wondering if the issue has been fixed and thanks in advance!
> 
> *The model I am running is llama4 maverick fp8

same issue for Qwen3 models

**Comment by jinleic** [comment]
The issue persists with this command:

python3 -m sglang.launch_server --model OpenGVLab/InternVL3-8B

currently there is no problem running the hf version:

python3 -m sglang.launch_server --model OpenGVLab/InternVL3-8B-hf

wondering if there is huge performance drop with the hf version

**Comment by jinleic** [comment]
BTW, has the docker lmsysorg/sglang:blackwell been tested on 5090 ?

**Comment by alvinshao0313** [comment]
The same issue, how can it be resolved? @makjaveli

**Comment by wwj-2017-1117** [comment]
The same issue

**Comment by pmixer** [comment]
I tried to run deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B on my personal desktop w/ 5070, encountered the same issue.

According to https://github.com/sgl-project/sglang/issues/9542#issuecomment-3218531293, manually downloading and installing sgl-kernel whl from https://github.com/sgl-project/whl/blob/484e8e47311e8cb58d210dcb8dcc8ae7c8d268d1/cu128/sgl-kernel/index.html#L57, works for my case.

Considering the whl file w/ sm120 kernel binaries being a bit larger than 400MB while https://pypi.org/project/sgl-kernel/#sgl_kernel-0.3.8-cp310-abi3-manylinux2014_x86_64.whl being only a bit larger than 300MB, feels like the sm120 binaries haven't been included in the default pip whl(yet?)

**Comment by andrewgross** [comment]
Flagging that this solved my issue as well. Even using `uv` and specifying the torch backend, I had to follow custom installation instructions.

Steps:

1. have Cuda 12.9 Installed (I was on driver 575.57.08 as well)
2. `uv venv --python 3.10` (3.10 is important for getting the matching wheel)
3. `uv pip install "sglang[all]>=0.5.2rc2"` (EDIT: I replicated this with 0.5.1.post3 successfully, and using that tag was important when trying to run the tuning script below)
4. `uv pip install https://github.com/sgl-project/whl/releases/download/v0.3.8/sgl_kernel-0.3.8+cu129-cp310-abi3-manylinux2014_x86_64.whl` - Note the cu129 and cp310 affixes to ensure I got the right version. If you are Cuda 12.8, you need cu128.

Now models like Qwen3 are running on Blackwell. Still having issues with GLM-4.5 Air models. Note, this is due to SGLang have issues with some FP8 Kernels at Cutlass. 

To deal with this I had to do the following:

1. Switch to the Triton Moe FP8 kernel via `USE_TRITON_W8A8_FP8_KERNEL=1 <sglang server commands>`. 
2. Calibrate Triton to my gfx card. 
3. Check out `sglang==0.5.1.post3`, install it and its deps, along with `ray`
4. Run `cd sglang/benchmark/kernels/fused_moe_triton && python tuning_fused_moe_triton.py --model zai-org/GLM-4.5-Air-FP8 --tp-size 2 --dtype fp8_w8a8 --tune` to generate the config file. See this [post](https://www.jamesflare.com/tuning-fused-moe-triton/).  <-- I am here
5. Move the file to the appropriate config location for SGLang and rebuild from source.

The upside was that I was able to go from ~70 tok/s for GLM-4.5-Air-FP8 (bs=1) on vLLM to ~160 tok/s on SGLang when using MTP speculative execution (no draft model), before it blew up due to Triton memory issues.

EDIT: After running the tuning script and building SGLang with those config files in place, I was able to get 200 tok/s stable for GLM-4.5-Air. I also have PR #10243 open to add the configs for Blackwell Workstation cards.

**Comment by matheus-1618** [comment]
same issue here, using behing Nvidia Dynamo
