### ISSUE TITLE
[Bug] TBO hang when capture cuda graph in disaggregation mode

### ISSUE THREAD

**Issue by lbh2001** [sgl-project/sglang#7602]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug
I have two nodes, each with 8 * H800. I applied this pr https://github.com/sgl-project/sglang/pull/7616 to avoid the same bug to https://github.com/sgl-project/sglang/issues/7511 .
But I found it would always hang when capture bs=32. I printed some logs and found that every time, the process stucks at the `all_gather` operation in `attn_tp_all_gather` of a fixed layer. I marked where did it hang:
```python
# parallel_state.py
def all_gather(
    self,
    input_: torch.Tensor,
    dim: int = -1,
    output_tensor_list: Optional[List[torch.Tensor]] = None,
) -> torch.Tensor:
    world_size = self.world_size
    # Bypass the function if we are using only 1 GPU.
    if world_size == 1:
        if output_tensor_list is not None:
            logger.warning(
                "Performing in-place all-gather with a group size of 1. "
                "This may be unnecessary; consider bypassing it for better efficiency."
            )
            output_tensor_list[0].copy_(input_)
            return None
        else:
            return input_

    if output_tensor_list is not None:
        # TODO(ch-wan): support other backends
        # hang here
        return torch.distributed.all_gather(
            output_tensor_list, input_, group=self.device_group
        )
    #...
```
And the capture_bs was set to `[2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128]`, if I changed it to some smaller value, for example `[2, 4, 8, 16, 24, 32, 40, 48, 56, 64]`, the problem would be solved.

### Reproduction

model: DeepSeek-V3

script:
```bash
#...
dp_size=4
tp_size=16
nnodes=2

python3 -m sglang.launch_server --model-path /ssd1/models/huggingface.co/deepseek-ai/DeepSeek-V3 --disaggregation-ib-device ${device_name} --disaggregation-mode decode --host ${local_ip} --port ${port} --trust-remote-code --dist-init-addr ${decode_master_ip}:6676 --nnodes ${nnodes} --node-rank ${node_rank} --tp-size ${tp_size} --dp-size ${dp_size} --enable-dp-attention  --enable-deepep-moe --deepep-mode normal --mem-fraction-static 0.85 --schedule-policy lpm --enable-two-batch-overlap
```

### Environment
My sglang version is v0.4.8
Here is my environment:
```bash
Python: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H800
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 550.127.08
PyTorch: 2.5.1+cu124
sglang: 0.4.8
sgl_kernel: 0.1.9
flashinfer_python: 0.2.5+cu124torch2.5
triton: 3.1.0
transformers: 4.48.3
torchao: 0.9.0
numpy: 1.26.4
aiohttp: 3.11.13
fastapi: 0.115.11
hf_transfer: 0.1.9
huggingface_hub: 0.29.2
interegular: 0.3.3
modelscope: 1.23.2
orjson: 3.10.15
outlines: 0.0.46
packaging: 24.2
psutil: 7.0.0
pydantic: 2.10.6
python-multipart: 0.0.20
pyzmq: 26.2.1
uvicorn: 0.34.0
uvloop: 0.21.0
vllm: 0.6.4.post1
xgrammar: 0.1.14
openai: 1.65.4
tiktoken: 0.9.0
anthropic: 0.49.0
litellm: 1.62.4
decord: 0.6.0
NVIDIA Topology:
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	NIC1	NIC2	NIC3	NIC4	NIC5	NIC6	NIC7	NIC8	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV18	NV18	NV18	NV18	NV18	NV18	NV18	PIX	NODE	NODE	NODE	SYS	SYS	SYS	SYS	NODE	0-47,96-143	0		N/A
GPU1	NV18	 X 	NV18	NV18	NV18	NV18	NV18	NV18	NODE	PIX	NODE	NODE	SYS	SYS	SYS	SYS	NODE	0-47,96-143	0		N/A
GPU2	NV18	NV18	 X 	NV18	NV18	NV18	NV18	NV18	NODE	NODE	PIX	NODE	SYS	SYS	SYS	SYS	NODE	0-47,96-143	0		N/A
GPU3	NV18	NV18	NV18	 X 	NV18	NV18	NV18	NV18	NODE	NODE	NODE	PIX	SYS	SYS	SYS	SYS	NODE	0-47,96-143	0		N/A
GPU4	NV18	NV18	NV18	NV18	 X 	NV18	NV18	NV18	SYS	SYS	SYS	SYS	PIX	NODE	NODE	NODE	SYS	48-95,144-191	1		N/A
GPU5	NV18	NV18	NV18	NV18	NV18	 X 	NV18	NV18	SYS	SYS	SYS	SYS	NODE	PIX	NODE	NODE	SYS	48-95,144-191	1		N/A
GPU6	NV18	NV18	NV18	NV18	NV18	NV18	 X 	NV18	SYS	SYS	SYS	SYS	NODE	NODE	PIX	NODE	SYS	48-95,144-191	1		N/A
GPU7	NV18	NV18	NV18	NV18	NV18	NV18	NV18	 X 	SYS	SYS	SYS	SYS	NODE	NODE	NODE	PIX	SYS	48-95,144-191	1		N/A
NIC0	PIX	NODE	NODE	NODE	SYS	SYS	SYS	SYS	 X 	NODE	NODE	NODE	SYS	SYS	SYS	SYS	NODE
NIC1	NODE	PIX	NODE	NODE	SYS	SYS	SYS	SYS	NODE	 X 	NODE	NODE	SYS	SYS	SYS	SYS	NODE
NIC2	NODE	NODE	PIX	NODE	SYS	SYS	SYS	SYS	NODE	NODE	 X 	NODE	SYS	SYS	SYS	SYS	NODE
NIC3	NODE	NODE	NODE	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	 X 	SYS	SYS	SYS	SYS	NODE
NIC4	SYS	SYS	SYS	SYS	PIX	NODE	NODE	NODE	SYS	SYS	SYS	SYS	 X 	NODE	NODE	NODE	SYS
NIC5	SYS	SYS	SYS	SYS	NODE	PIX	NODE	NODE	SYS	SYS	SYS	SYS	NODE	 X 	NODE	NODE	SYS
NIC6	SYS	SYS	SYS	SYS	NODE	NODE	PIX	NODE	SYS	SYS	SYS	SYS	NODE	NODE	 X 	NODE	SYS
NIC7	SYS	SYS	SYS	SYS	NODE	NODE	NODE	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	 X 	SYS
NIC8	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	 X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_2
  NIC1: mlx5_3
  NIC2: mlx5_4
  NIC3: mlx5_5
  NIC4: mlx5_6
  NIC5: mlx5_7
  NIC6: mlx5_8
  NIC7: mlx5_9
  NIC8: mlx5_bond_0


ulimit soft: 1048576
```

**Comment by lbh2001** [comment]
Oh it have been fixed by https://github.com/sgl-project/sglang/pull/7531

**Comment by lbh2001** [comment]
I have tried https://github.com/sgl-project/sglang/pull/7531 but it would only work on Decode node which was enabled cuda graph. Currently, the prefill node almost always fails, and only occasionally succeeds. It was already like this before applying this pr.

**Comment by lbh2001** [comment]
@fzyzcjy @zhyncs @ch-wan Hello, could you please help take a look at this issue?

**Comment by lbh2001** [comment]
> [@fzyzcjy](https://github.com/fzyzcjy) [@zhyncs](https://github.com/zhyncs) [@ch-wan](https://github.com/ch-wan) Hello, could you please help take a look at this issue?

Oh I have solved this problem, I found my `nvidia-nccl-cu12` version was 2.21.5, and there was a deadlock bug in this version https://github.com/NVIDIA/nccl/issues/1251. I tried to upgrade it to 2.22.3 and everything was ok..
