### ISSUE TITLE
[Bug] Serve Qwen3-GPTQ with OOM issue

### ISSUE THREAD

**Issue by hahmad2008** [sgl-project/sglang#8362]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

I can't serve this model `Qwen/Qwen3-235B-A22B-GPTQ-Int4` on 2A100 GPUS (each GPU has 80G memory). and the same model can be served using VLLM on the same 2A100 GPUs machine!! why I can't serve it using SGLANG although I tried to use disable cuda graph and also with different gpu fraction.

- command
```
python -m sglang.launch_server --model  Qwen/Qwen3-235B-A22B-GPTQ-Int4 \
                                                         --tp 2 --mem-fraction 0.85  --host 0.0.0.0 --port 8000  \
                                                        --context-len 32768 --chunked-prefill-size 32768 \
                                                         --disable-cuda-graph --disable-cuda-graph-padding 

```

- Error

```
 File "/root/miniconda3/envs/sglang-env/lib/python3.10/site-packages/vllm/_custom_ops.py", line 783, in gptq_marlin_moe_repack
    output = torch.empty((num_experts, size_k // 16, size_n * (num_bits // 2)),
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 192.00 MiB. GPU 0 has a total capacity of 79.14 GiB of which 145.00 MiB is free. Including non-PyTorch memory, this process has 78.99 GiB memory in use. Of the allocated memory 77.67 GiB is allocated by PyTorch, and 163.09 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  

```

- Worked with VLLM on 2A100
```
 VLLM_USE_V1=0  vllm serve \
    Qwen/Qwen3-235B-A22B-GPTQ-Int4 \
    --max-model-len 32768 \
    --distributed-executor-backend mp \
    --gpu-memory-utilization 0.9 \
    --tensor-parallel-size 2 

```

Any help?

### Environment

```
conda create   -n sglang-env python=3.10
python -m pip install sgl-kernel --force-reinstall --no-deps
python -m pip install torch==2.6.0
python -m pip install flashinfer-python==0.2.5 -i https://flashinfer.ai/whl/cu124/torch2.6/
python -m pip  install   "sglang[all]==0.4.6.post5"
python -m  pip install vllm==0.8.4
```

**Comment by aaronyeeio** [comment]
same issue with Qwen3-GPTQ

**Comment by hahmad2008** [comment]
@aaronyeeio are you able to solve it?

**Comment by yzhh029** [comment]
Same issue here, with 4 RTX 4090 48GB vram, running Qwen3 got OOM issue

`docker run -d --gpus all \
  --shm-size 32g \
  -p 30000:30000 \
  --env "SGLANG_USE_MODELSCOPE=true" \
  --ipc=host \
  lmsysorg/sglang:latest \
  python3 -m sglang.launch_server \
    --model-path Qwen/Qwen3-235B-A22B-GPTQ-Int4 \
    --host 0.0.0.0 --port 30000 --tp 4 --enable-p2p-check --tool-call-parser qwen25 --reasoning-parser qwen3 --mem-fraction-static 0.85
`
Already installed vllm inside the container

`INFO 07-30 06:59:08 [__init__.py:243] Automatically detected platform cuda.
/sgl-workspace/sglang/python/sglang/srt/layers/quantization/awq.py:42: UserWarning: Using kernels directly from vllm. This might lead to performance degradation or missing functionalities as certain kernels may not be optimized. 
  warnings.warn(
[2025-07-30 06:59:11] server_args=ServerArgs(model_path='Qwen/Qwen3-235B-A22B-GPTQ-Int4', tokenizer_path='Qwen/Qwen3-235B-A22B-GPTQ-Int4', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', model_loader_extra_config='{}', trust_remote_code=False, context_length=None, is_embedding=False, enable_multimodal=None, revision=None, model_impl='auto', host='0.0.0.0', port=30000, skip_server_warmup=False, warmups=None, nccl_port=None, dtype='auto', quantization=None, quantization_param_path=None, kv_cache_dtype='auto', mem_fraction_static=0.85, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='fcfs', schedule_conservativeness=1.0, cpu_offload_gb=0, page_size=1, hybrid_kvcache_ratio=None, swa_full_tokens_ratio=0.8, disable_hybrid_swa_memory=False, device='cuda', tp_size=4, pp_size=1, max_micro_batch_size=None, stream_interval=1, stream_output=False, random_seed=59390279, constrained_json_whitespace_pattern=None, watchdog_timeout=300, dist_timeout=None, download_dir=None, base_gpu_id=0, gpu_id_step=1, sleep_on_idle=False, log_level='info', log_level_http=None, log_requests=False, log_requests_level=0, crash_dump_folder=None, show_time_cost=False, enable_metrics=False, enable_metrics_for_all_schedulers=False, bucket_time_to_first_token=None, bucket_inter_token_latency=None, bucket_e2e_request_latency=None, collect_tokens_histogram=False, decode_log_interval=40, enable_request_time_stats_logging=False, kv_events_config=None, api_key=None, served_model_name='Qwen/Qwen3-235B-A22B-GPTQ-Int4', chat_template=None, completion_template=None, file_storage_path='sglang_storage', enable_cache_report=False, reasoning_parser='qwen3', tool_call_parser='qwen25', dp_size=1, load_balance_method='round_robin', dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', preferred_sampling_params=None, enable_lora=None, max_lora_rank=None, lora_target_modules=None, lora_paths=None, max_loras_per_batch=8, lora_backend='triton', attention_backend=None, sampling_backend='flashinfer', grammar_backend='xgrammar', mm_attention_backend=None, speculative_algorithm=None, speculative_draft_model_path=None, speculative_num_steps=None, speculative_eagle_topk=None, speculative_num_draft_tokens=None, speculative_accept_threshold_single=1.0, speculative_accept_threshold_acc=1.0, speculative_token_map=None, ep_size=1, enable_ep_moe=False, enable_deepep_moe=False, enable_flashinfer_moe=False, enable_flashinfer_allreduce_fusion=False, deepep_mode='auto', ep_num_redundant_experts=0, ep_dispatch_algorithm='static', init_expert_location='trivial', enable_eplb=False, eplb_algorithm='auto', eplb_rebalance_num_iterations=1000, eplb_rebalance_layers_per_chunk=None, expert_distribution_recorder_mode=None, expert_distribution_recorder_buffer_size=1000, enable_expert_distribution_metrics=False, deepep_config=None, moe_dense_tp_size=None, enable_hierarchical_cache=False, hicache_ratio=2.0, hicache_size=0, hicache_write_policy='write_through_selective', hicache_io_backend='', hicache_storage_backend=None, enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, disable_radix_cache=False, cuda_graph_max_bs=None, cuda_graph_bs=None, disable_cuda_graph=False, disable_cuda_graph_padding=False, enable_profile_cuda_graph=False, enable_nccl_nvls=False, enable_tokenizer_batch_encode=False, disable_outlines_disk_cache=False, disable_custom_all_reduce=False, enable_mscclpp=False, disable_overlap_schedule=False, enable_mixed_chunk=False, enable_dp_attention=False, enable_dp_lm_head=False, enable_two_batch_overlap=False, enable_torch_compile=False, torch_compile_max_bs=32, torchao_config='', enable_nan_detection=False, enable_p2p_check=True, triton_attention_reduce_in_fp32=False, triton_attention_num_kv_splits=8, num_continuous_decode_steps=1, delete_ckpt_after_loading=False, enable_memory_saver=False, allow_auto_truncate=False, enable_custom_logit_processor=False, flashinfer_mla_disable_ragged=False, disable_shared_experts_fusion=False, disable_chunked_prefix_cache=False, disable_fast_image_processor=False, enable_return_hidden_states=False, enable_triton_kernel_moe=False, debug_tensor_dump_output_folder=None, debug_tensor_dump_input_file=None, debug_tensor_dump_inject=False, debug_tensor_dump_prefill_only=False, disaggregation_mode='null', disaggregation_transfer_backend='mooncake', disaggregation_bootstrap_port=8998, disaggregation_decode_tp=None, disaggregation_decode_dp=None, disaggregation_prefill_pp=1, disaggregation_ib_device=None, num_reserved_decode_tokens=512, pdlb_url=None, custom_weight_loader=[], weight_loader_disable_mmap=False, enable_pdmux=False, sm_group_num=3)
Downloading Model from https://www.modelscope.cn to directory: /root/.cache/modelscope/hub/models/Qwen/Qwen3-235B-A22B-GPTQ-Int4
Downloading Model from https://www.modelscope.cn to directory: /root/.cache/modelscope/hub/models/Qwen/Qwen3-235B-A22B-GPTQ-Int4
[2025-07-30 06:59:13] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
INFO 07-30 06:59:18 [__init__.py:243] Automatically detected platform cuda.
INFO 07-30 06:59:18 [__init__.py:243] Automatically detected platform cuda.
INFO 07-30 06:59:19 [__init__.py:243] Automatically detected platform cuda.
INFO 07-30 06:59:19 [__init__.py:243] Automatically detected platform cuda.
INFO 07-30 06:59:19 [__init__.py:243] Automatically detected platform cuda.
/sgl-workspace/sglang/python/sglang/srt/layers/quantization/awq.py:42: UserWarning: Using kernels directly from vllm. This might lead to performance degradation or missing functionalities as certain kernels may not be optimized. 
  warnings.warn(
[2025-07-30 06:59:21 TP0] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
[2025-07-30 06:59:22 TP0] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
[2025-07-30 06:59:22 TP0] Attention backend not explicitly specified. Use flashinfer backend by default.
[2025-07-30 06:59:22 TP0] Init torch distributed begin.
/sgl-workspace/sglang/python/sglang/srt/layers/quantization/awq.py:42: UserWarning: Using kernels directly from vllm. This might lead to performance degradation or missing functionalities as certain kernels may not be optimized. 
  warnings.warn(
/sgl-workspace/sglang/python/sglang/srt/layers/quantization/awq.py:42: UserWarning: Using kernels directly from vllm. This might lead to performance degradation or missing functionalities as certain kernels may not be optimized. 
  warnings.warn(
/sgl-workspace/sglang/python/sglang/srt/layers/quantization/awq.py:42: UserWarning: Using kernels directly from vllm. This might lead to performance degradation or missing functionalities as certain kernels may not be optimized. 
  warnings.warn(
/sgl-workspace/sglang/python/sglang/srt/layers/quantization/awq.py:42: UserWarning: Using kernels directly from vllm. This might lead to performance degradation or missing functionalities as certain kernels may not be optimized. 
  warnings.warn(
[2025-07-30 06:59:22 TP2] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
[2025-07-30 06:59:22 TP3] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
[2025-07-30 06:59:22 TP1] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
[2025-07-30 06:59:22 TP2] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
[2025-07-30 06:59:23 TP3] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
[2025-07-30 06:59:23 TP1] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
[2025-07-30 06:59:23 TP0] sglang is using nccl==2.26.2
[2025-07-30 06:59:23 TP1] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[2025-07-30 06:59:23 TP3] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[2025-07-30 06:59:23 TP0] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[2025-07-30 06:59:23 TP2] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[2025-07-30 06:59:23 TP0] Init torch distributed ends. mem usage=0.16 GB
[2025-07-30 06:59:25 TP0] Load weight begin. avail mem=46.86 GB
Loading safetensors checkpoint shards:   0% Completed | 0/32 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   3% Completed | 1/32 [00:00<00:29,  1.04it/s]
Loading safetensors checkpoint shards:   6% Completed | 2/32 [00:02<00:34,  1.15s/it]
Loading safetensors checkpoint shards:   9% Completed | 3/32 [00:03<00:34,  1.20s/it]
Loading safetensors checkpoint shards:  12% Completed | 4/32 [00:04<00:31,  1.13s/it]
Loading safetensors checkpoint shards:  16% Completed | 5/32 [00:05<00:31,  1.17s/it]
Loading safetensors checkpoint shards:  19% Completed | 6/32 [00:07<00:31,  1.21s/it]
Loading safetensors checkpoint shards:  22% Completed | 7/32 [00:08<00:30,  1.23s/it]
Loading safetensors checkpoint shards:  25% Completed | 8/32 [00:09<00:27,  1.14s/it]
Loading safetensors checkpoint shards:  28% Completed | 9/32 [00:10<00:23,  1.03s/it]
Loading safetensors checkpoint shards:  31% Completed | 10/32 [00:11<00:23,  1.09s/it]
Loading safetensors checkpoint shards:  34% Completed | 11/32 [00:12<00:23,  1.14s/it]
Loading safetensors checkpoint shards:  38% Completed | 12/32 [00:13<00:23,  1.17s/it]
Loading safetensors checkpoint shards:  41% Completed | 13/32 [00:15<00:22,  1.20s/it]
Loading safetensors checkpoint shards:  44% Completed | 14/32 [00:16<00:21,  1.20s/it]
Loading safetensors checkpoint shards:  47% Completed | 15/32 [00:17<00:20,  1.20s/it]
Loading safetensors checkpoint shards:  50% Completed | 16/32 [00:18<00:19,  1.19s/it]
Loading safetensors checkpoint shards:  53% Completed | 17/32 [00:19<00:18,  1.22s/it]
Loading safetensors checkpoint shards:  56% Completed | 18/32 [00:21<00:17,  1.23s/it]
Loading safetensors checkpoint shards:  59% Completed | 19/32 [00:22<00:16,  1.25s/it]
Loading safetensors checkpoint shards:  62% Completed | 20/32 [00:23<00:15,  1.26s/it]
Loading safetensors checkpoint shards:  66% Completed | 21/32 [00:24<00:13,  1.22s/it]
Loading safetensors checkpoint shards:  69% Completed | 22/32 [00:26<00:13,  1.32s/it]
Loading safetensors checkpoint shards:  72% Completed | 23/32 [00:27<00:11,  1.28s/it]
Loading safetensors checkpoint shards:  75% Completed | 24/32 [00:28<00:10,  1.27s/it]
Loading safetensors checkpoint shards:  78% Completed | 25/32 [00:30<00:08,  1.27s/it]
Loading safetensors checkpoint shards:  81% Completed | 26/32 [00:31<00:07,  1.27s/it]
Loading safetensors checkpoint shards:  84% Completed | 27/32 [00:32<00:06,  1.27s/it]
Loading safetensors checkpoint shards:  88% Completed | 28/32 [00:33<00:05,  1.27s/it]
Loading safetensors checkpoint shards:  91% Completed | 29/32 [00:35<00:03,  1.28s/it]
Loading safetensors checkpoint shards:  94% Completed | 30/32 [00:37<00:03,  1.57s/it]
Loading safetensors checkpoint shards:  97% Completed | 31/32 [00:38<00:01,  1.47s/it]
Loading safetensors checkpoint shards: 100% Completed | 32/32 [00:39<00:00,  1.15s/it]
Loading safetensors checkpoint shards: 100% Completed | 32/32 [00:39<00:00,  1.22s/it]

[2025-07-30 07:00:06 TP2] Scheduler hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2935, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, pp_rank, dp_rank)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 344, in __init__
    self.tp_worker = TpWorkerClass(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 66, in __init__
    self.worker = TpModelWorker(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 81, in __init__
    self.model_runner = ModelRunner(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 233, in __init__
    self.initialize(min_per_gpu_memory)
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 276, in initialize
    self.load_model()
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 618, in load_model
    self.model = get_model(
  File "/sgl-workspace/sglang/python/sglang/srt/model_loader/__init__.py", line 22, in get_model
    return loader.load_model(
  File "/sgl-workspace/sglang/python/sglang/srt/model_loader/loader.py", line 437, in load_model
    self.load_weights_and_postprocess(
  File "/sgl-workspace/sglang/python/sglang/srt/model_loader/loader.py", line 456, in load_weights_and_postprocess
    quant_method.process_weights_after_loading(module)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/quantization/gptq.py", line 1030, in process_weights_after_loading
    marlin_w2_qweight = gptq_marlin_moe_repack(
  File "/sgl-workspace/sglang/python/sglang/srt/layers/quantization/gptq.py", line 82, in gptq_marlin_moe_repack
    output = torch.empty(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 2 has a total capacity of 47.38 GiB of which 62.19 MiB is free. Process 81643 has 47.31 GiB memory in use. Of the allocated memory 46.67 GiB is allocated by PyTorch, and 148.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
`

**Comment by lmjhh** [comment]
The memory usage doubles after executing process_weights_after_loading in awq.py.

**Comment by lmjhh** [comment]
I fixed this bug， https://github.com/sgl-project/sglang/pull/8748

**Comment by aaronyeeio** [comment]
It seems it's a problem introduced by newer version of vllm (https://github.com/vllm-project/vllm/issues/21864).

Here comes a temporary solution. Downgrade the vllm version according to the environment listed here: https://qwen.readthedocs.io/en/latest/getting_started/speed_benchmark.html

**Comment by aaronyeeio** [comment]
Just found out it's probably fixed by #7568
