### ISSUE TITLE
[Bug]  Scheduler hit an exception

### ISSUE THREAD

**Issue by salt00n9** [sgl-project/sglang#8974]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

i was able to run GLM 4.5 into a rented vastai machine with 4xh200 using this command :

```
vastai create instance <insatance-id> --image lmsysorg/sglang:latest --env '-p 8000:8000' --disk 600 --args python3 -m sglang.launch_server \
  --model-path zai-org/GLM-4.5-FP8 \
  --tp-size 4 \
  --tool-call-parser glm45  \
  --reasoning-parser glm45  \
  --speculative-algorithm EAGLE \
  --speculative-num-steps 3  \
  --speculative-eagle-topk 1  \
  --speculative-num-draft-tokens 4 \
  --mem-fraction-static 0.7 \
  --disable-shared-experts-fusion \
  --served-model-name glm-4.5-fp8 \
  --host 0.0.0.0 \
  --port 8000
```

i tried to mimic the same into our setup which has no internet connection, using nvidia runai (docker containers):
using this command:

```
python3 -m sglang.launch_server \
  --model-path /data/GLM-4.5 \
  --tp-size 4 \
  --tool-call-parser glm45  \
  --reasoning-parser glm45  \
  --speculative-algorithm EAGLE \
  --speculative-num-steps 3  \
  --speculative-eagle-topk 1  \
  --speculative-num-draft-tokens 4 \
  --mem-fraction-static 0.7 \
  --disable-shared-experts-fusion \
  --served-model-name glm-4.5 \
  --host 0.0.0.0 \
  --port 8000
```

**LOGS:**

==========
== CUDA ==
==========
CUDA Version 12.6.1
Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
Overlap scheduler is disabled because of using eagle speculative decoding.
[2025-08-08 09:08:57] server_args=ServerArgs(model_path='/data/GLM-4.5', tokenizer_path='/data/GLM-4.5', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', model_loader_extra_config='{}', trust_remote_code=False, context_length=None, is_embedding=False, enable_multimodal=None, revision=None, model_impl='auto', host='0.0.0.0', port=8000, skip_server_warmup=False, warmups=None, nccl_port=None, dtype='auto', quantization=None, quantization_param_path=None, kv_cache_dtype='auto', mem_fraction_static=0.7, max_running_requests=48, max_queued_requests=9223372036854775807, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='fcfs', schedule_conservativeness=1.0, cpu_offload_gb=0, page_size=1, hybrid_kvcache_ratio=None, swa_full_tokens_ratio=0.8, disable_hybrid_swa_memory=False, device='cuda', tp_size=4, pp_size=1, max_micro_batch_size=None, stream_interval=1, stream_output=False, random_seed=209038388, constrained_json_whitespace_pattern=None, watchdog_timeout=300, dist_timeout=None, download_dir=None, base_gpu_id=0, gpu_id_step=1, sleep_on_idle=False, log_level='info', log_level_http=None, log_requests=False, log_requests_level=0, crash_dump_folder=None, show_time_cost=False, enable_metrics=False, enable_metrics_for_all_schedulers=False, bucket_time_to_first_token=None, bucket_inter_token_latency=None, bucket_e2e_request_latency=None, collect_tokens_histogram=False, decode_log_interval=40, enable_request_time_stats_logging=False, kv_events_config=None, api_key=None, served_model_name='sultanai', chat_template=None, completion_template=None, file_storage_path='sglang_storage', enable_cache_report=False, reasoning_parser='glm45', tool_call_parser='glm45', dp_size=1, load_balance_method='round_robin', dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', preferred_sampling_params=None, enable_lora=None, max_lora_rank=None, lora_target_modules=None, lora_paths=None, max_loaded_loras=None, max_loras_per_batch=8, lora_backend='triton', attention_backend=None, decode_attention_backend=None, prefill_attention_backend=None, sampling_backend='flashinfer', grammar_backend='xgrammar', mm_attention_backend=None, speculative_algorithm='EAGLE', speculative_draft_model_path='/data/GLM-4.5', speculative_num_steps=3, speculative_eagle_topk=1, speculative_num_draft_tokens=4, speculative_accept_threshold_single=1.0, speculative_accept_threshold_acc=1.0, speculative_token_map=None, ep_size=1, moe_a2a_backend=None, enable_flashinfer_cutlass_moe=False, enable_flashinfer_trtllm_moe=False, enable_flashinfer_allreduce_fusion=False, deepep_mode='auto', ep_num_redundant_experts=0, ep_dispatch_algorithm='static', init_expert_location='trivial', enable_eplb=False, eplb_algorithm='auto', eplb_rebalance_num_iterations=1000, eplb_rebalance_layers_per_chunk=None, expert_distribution_recorder_mode=None, expert_distribution_recorder_buffer_size=1000, enable_expert_distribution_metrics=False, deepep_config=None, moe_dense_tp_size=None, enable_hierarchical_cache=False, hicache_ratio=2.0, hicache_size=0, hicache_write_policy='write_through_selective', hicache_io_backend='kernel', hicache_mem_layout='layer_first', hicache_storage_backend=None, enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, disable_radix_cache=False, cuda_graph_max_bs=None, cuda_graph_bs=None, disable_cuda_graph=False, disable_cuda_graph_padding=False, enable_profile_cuda_graph=False, enable_cudagraph_gc=False, enable_nccl_nvls=False, enable_symm_mem=False, enable_tokenizer_batch_encode=False, disable_outlines_disk_cache=False, disable_custom_all_reduce=False, enable_mscclpp=False, disable_overlap_schedule=True, enable_mixed_chunk=False, enable_dp_attention=False, enable_dp_lm_head=False, enable_two_batch_overlap=False, enable_torch_compile=False, torch_compile_max_bs=32, torchao_config='', enable_nan_detection=False, enable_p2p_check=False, triton_attention_reduce_in_fp32=False, triton_attention_num_kv_splits=8, num_continuous_decode_steps=1, delete_ckpt_after_loading=False, enable_memory_saver=False, allow_auto_truncate=False, enable_custom_logit_processor=False, flashinfer_mla_disable_ragged=False, disable_shared_experts_fusion=True, disable_chunked_prefix_cache=False, disable_fast_image_processor=False, enable_return_hidden_states=False, enable_triton_kernel_moe=False, debug_tensor_dump_output_folder=None, debug_tensor_dump_input_file=None, debug_tensor_dump_inject=False, debug_tensor_dump_prefill_only=False, disaggregation_mode='null', disaggregation_transfer_backend='mooncake', disaggregation_bootstrap_port=8998, disaggregation_decode_tp=None, disaggregation_decode_dp=None, disaggregation_prefill_pp=1, disaggregation_ib_device=None, num_reserved_decode_tokens=512, pdlb_url=None, custom_weight_loader=[], weight_loader_disable_mmap=False, enable_pdmux=False, sm_group_num=3, enable_ep_moe=False, enable_deepep_moe=False)
[2025-08-08 09:08:58] Using default HuggingFace chat template with detected content format: string
[2025-08-08 09:09:07 TP0] Attention backend not explicitly specified. Use fa3 backend by default.
[2025-08-08 09:09:07 TP0] Init torch distributed begin.
[2025-08-08 09:09:08 TP0] sglang is using nccl==2.27.6
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Bootstrap: Using eth0:172.29.141.183<0>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO cudaDriverVersion 12090
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO NCCL version 2.27.6+cuda12.9
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO NET/Plugin: Could not find: libnccl-net.so.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO NET/Socket : Using [0]eth0:172.29.141.183<0>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Initialized NET plugin Socket
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Assigned NET plugin Socket to comm
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Using network Socket
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO ncclCommInitRank comm 0x55555f90d420 rank 0 nranks 4 cudaDev 0 nvmlDev 0 busId 18000 commId 0xb6ef167071e271f7 - Init START
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO RAS client listening socket at ::1<28028>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Bootstrap timings total 0.002532 (create 0.000094, send 0.000244, recv 0.000585, ring 0.000160, delay 0.000001)
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO MNNVL busId 0x18000 fabric UUID 0.0 cliqueId 0x0 state 3 healthMask 0x0
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO NCCL_P2P_LEVEL set by environment to NVL
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Setting affinity for GPU 0 to 0-47,96-143
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO NCCL_NVLS_ENABLE set by environment to 0.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO comm 0x55555f90d420 rank 0 nRanks 4 nNodes 1 localRanks 4 localRank 0 MNNVL 0
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 00/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 01/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 02/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 03/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 04/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 05/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 06/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 07/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 08/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 09/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 10/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 11/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 12/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 13/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 14/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 15/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 16/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 17/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 18/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 19/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 20/24 : 0 1adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO cudaDriverVersion 12090
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Bootstrap: Using eth0:172.29.141.183<0>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO NCCL version 2.27.6+cuda12.9
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO NET/Plugin: Could not find: libnccl-net.so.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO NET/Socket : Using [0]eth0:172.29.141.183<0>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Initialized NET plugin Socket
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Assigned NET plugin Socket to comm
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Using network Socket
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO ncclCommInitRank comm 0x5555654f3ed0 rank 3 nranks 4 cudaDev 3 nvmlDev 3 busId 4b000 commId 0xb6ef167071e271f7 - Init START
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO RAS client listening socket at ::1<28028>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Bootstrap timings total 0.020492 (create 0.000112, send 0.000216, recv 0.019127, ring 0.000101, delay 0.000001)
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO MNNVL busId 0x4b000 fabric UUID 0.0 cliqueId 0x0 state 3 healthMask 0x0
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO NCCL_P2P_LEVEL set by environment to NVL
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Setting affinity for GPU 3 to 0-47,96-143
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO NCCL_NVLS_ENABLE set by environment to 0.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO comm 0x5555654f3ed0 rank 3 nRanks 4 nNodes 1 localRanks 4 localRank 3 MNNVL 0
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] -1/-1/-1->3->2 [2] -1/-1/-1->3->2 [3] -1/-1/-1->3->2 [4] -1/-1/-1->3->2 [5] -1/-1/-1->3->2 [6] -1/-1/-1->3->2 [7] -1/-1/-1->3->2 [8] -1/-1/-1->3->2 [9] -1/-1/-1->3->2 [10] -1/-1/-1->3->2 [11] -1/-1/-1->3->2 [12] -1/-1/-1->3->2 [13] -1/-1/-1->3->2 [14] -1/-1/-1->3->2 [15] -1/-1/-1->3->2 [16] -1/-1/-1->3->2 [17] -1/-1/-1->3->2 [18] -1/-1/-1->3->2 [19] -1/-1/-1->3->2 [20] -1/-1/-1->3->2 [21] -1/-1/-1->3->2 [22] -1/-1/-1->3->2 [23] -1/-1/-1->3->2
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO P2P Chunksize set to 524288
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO PROFILER/Plugin: Could not find: libnccl-profiler.so.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:2068 [3] NCCL INFO [Proxy Service] Device 3 CPU core 14
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:2069 [3] NCCL INFO [Proxy Service UDS] Device 3 CPU core 15
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 00/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 01/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 02/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 03/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 04/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 05/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 06/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 07/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 08/0 : 3[3] -> adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO cudaDriverVersion 12090
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Bootstrap: Using eth0:172.29.141.183<0>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO NCCL version 2.27.6+cuda12.9
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO NET/Plugin: Could not find: libnccl-net.so.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO NET/Socket : Using [0]eth0:172.29.141.183<0>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Initialized NET plugin Socket
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Assigned NET plugin Socket to comm
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Using network Socket
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO ncclCommInitRank comm 0x5555675fbf30 rank 2 nranks 4 cudaDev 2 nvmlDev 2 busId 3a000 commId 0xb6ef167071e271f7 - Init START
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO RAS client listening socket at ::1<28028>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Bootstrap timings total 0.014991 (create 0.000095, send 0.000280, recv 0.000364, ring 0.000441, delay 0.000001)
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO MNNVL busId 0x3a000 fabric UUID 0.0 cliqueId 0x0 state 3 healthMask 0x0
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO NCCL_P2P_LEVEL set by environment to NVL
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Setting affinity for GPU 2 to 0-47,96-143
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO NCCL_NVLS_ENABLE set by environment to 0.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO comm 0x5555675fbf30 rank 2 nRanks 4 nNodes 1 localRanks 4 localRank 2 MNNVL 0
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1 [2] 3/-1/-1->2->1 [3] 3/-1/-1->2->1 [4] 3/-1/-1->2->1 [5] 3/-1/-1->2->1 [6] 3/-1/-1->2->1 [7] 3/-1/-1->2->1 [8] 3/-1/-1->2->1 [9] 3/-1/-1->2->1 [10] 3/-1/-1->2->1 [11] 3/-1/-1->2->1 [12] 3/-1/-1->2->1 [13] 3/-1/-1->2->1 [14] 3/-1/-1->2->1 [15] 3/-1/-1->2->1 [16] 3/-1/-1->2->1 [17] 3/-1/-1->2->1 [18] 3/-1/-1->2->1 [19] 3/-1/-1->2->1 [20] 3/-1/-1->2->1 [21] 3/-1/-1->2->1 [22] 3/-1/-1->2->1 [23] 3/-1/-1->2->1
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO P2P Chunksize set to 524288
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO PROFILER/Plugin: Could not find: libnccl-profiler.so.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:2072 [2] NCCL INFO [Proxy Service] Device 2 CPU core 103
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:2073 [2] NCCL INFO [Proxy Service UDS] Device 2 CPU core 108
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 00/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 01/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 02/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 03/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 04/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 05/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 06/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 07/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 08/0 : 2[2] -> 3[3] via P2P/IPC
adp-uadp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO cudaDriverVersion 12090
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Bootstrap: Using eth0:172.29.141.183<0>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO NCCL version 2.27.6+cuda12.9
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO NET/Plugin: Could not find: libnccl-net.so.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO NET/Socket : Using [0]eth0:172.29.141.183<0>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Initialized NET plugin Socket
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Assigned NET plugin Socket to comm
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Using network Socket
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO ncclCommInitRank comm 0x5555675daab0 rank 1 nranks 4 cudaDev 1 nvmlDev 1 busId 29000 commId 0xb6ef167071e271f7 - Init START
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO RAS client listening socket at ::1<28028>
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Bootstrap timings total 0.002336 (create 0.000082, send 0.000205, recv 0.000522, ring 0.000452, delay 0.000001)
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO MNNVL busId 0x29000 fabric UUID 0.0 cliqueId 0x0 state 3 healthMask 0x0
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO NCCL_P2P_LEVEL set by environment to NVL
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Setting affinity for GPU 1 to 0-47,96-143
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO NCCL_NVLS_ENABLE set by environment to 0.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO comm 0x5555675daab0 rank 1 nRanks 4 nNodes 1 localRanks 4 localRank 1 MNNVL 0
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 2/-1/-1->1->0 [2] 2/-1/-1->1->0 [3] 2/-1/-1->1->0 [4] 2/-1/-1->1->0 [5] 2/-1/-1->1->0 [6] 2/-1/-1->1->0 [7] 2/-1/-1->1->0 [8] 2/-1/-1->1->0 [9] 2/-1/-1->1->0 [10] 2/-1/-1->1->0 [11] 2/-1/-1->1->0 [12] 2/-1/-1->1->0 [13] 2/-1/-1->1->0 [14] 2/-1/-1->1->0 [15] 2/-1/-1->1->0 [16] 2/-1/-1->1->0 [17] 2/-1/-1->1->0 [18] 2/-1/-1->1->0 [19] 2/-1/-1->1->0 [20] 2/-1/-1->1->0 [21] 2/-1/-1->1->0 [22] 2/-1/-1->1->0 [23] 2/-1/-1->1->0
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO P2P Chunksize set to 524288
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO PROFILER/Plugin: Could not find: libnccl-profiler.so.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:2075 [1] NCCL INFO [Proxy Service UDS] Device 1 CPU core 21
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:2070 [1] NCCL INFO [Proxy Service] Device 1 CPU core 103
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 00/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 01/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 02/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 03/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 04/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 05/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 06/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 07/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 08/0 : 1[1] -> 2[2] via P2P/IPC
adp-us 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 21/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 22/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 23/24 : 0 1 2 3
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1 [4] 1/-1/-1->0->-1 [5] 1/-1/-1->0->-1 [6] 1/-1/-1->0->-1 [7] 1/-1/-1->0->-1 [8] 1/-1/-1->0->-1 [9] 1/-1/-1->0->-1 [10] 1/-1/-1->0->-1 [11] 1/-1/-1->0->-1 [12] 1/-1/-1->0->-1 [13] 1/-1/-1->0->-1 [14] 1/-1/-1->0->-1 [15] 1/-1/-1->0->-1 [16] 1/-1/-1->0->-1 [17] 1/-1/-1->0->-1 [18] 1/-1/-1->0->-1 [19] 1/-1/-1->0->-1 [20] 1/-1/-1->0->-1 [21] 1/-1/-1->0->-1 [22] 1/-1/-1->0->-1 [23] 1/-1/-1->0->-1
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO P2P Chunksize set to 524288
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO PROFILER/Plugin: Could not find: libnccl-profiler.so.
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Check P2P Type isAllDirectP2p 1 directMode 0
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:2071 [0] NCCL INFO [Proxy Service] Device 0 CPU core 103
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:2074 [0] NCCL INFO [Proxy Service UDS] Device 0 CPU core 21
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 02/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 03/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 04/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 05/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 06/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 07/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 08/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 09/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 10/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 11/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 12/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 13/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 14/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 15/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 16/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 17/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 18/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 19/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 20/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 21/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 22/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Channel 23/0 : 0[0] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:234:234 [0] NCCL INFO Connected all rings, use rin0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 09/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 10/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 11/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 12/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 13/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 14/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 15/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 16/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 17/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 18/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 19/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 20/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 21/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 22/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 23/0 : 3[3] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Connected all rings, use ring PXN 0 GDR 1
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 00/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 01/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 02/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 03/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 04/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 05/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 06/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 07/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 08/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 09/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 10/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 11/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 12/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 13/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 14/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 15/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 16/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 17/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 18/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 19/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:237:237 [3] NCCL INFO Channel 20/0 : 3[3] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59s-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 09/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 10/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 11/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 12/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 13/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 14/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 15/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 16/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 17/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 18/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 19/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 20/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 21/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 22/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 23/0 : 2[2] -> 3[3] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Connected all rings, use ring PXN 0 GDR 1
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 00/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 01/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 02/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 03/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 04/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 05/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 06/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 07/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 08/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 09/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 10/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 11/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 12/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 13/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 14/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 15/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 16/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 17/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 18/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 19/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL INFO Channel 20/0 : 2[2] -> 1[1] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:236:236 [2] NCCL IN-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 09/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 10/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 11/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 12/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 13/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 14/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 15/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 16/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 17/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 18/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 19/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 20/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 21/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 22/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 23/0 : 1[1] -> 2[2] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Connected all rings, use ring PXN 0 GDR 1
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 00/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 01/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 02/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 03/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 04/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 05/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 06/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 07/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 08/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 09/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 10/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 11/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 12/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 13/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 14/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 15/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 16/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 17/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 18/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 19/0 : 1[1] -> 0[0] via P2P/IPC
adp-us-llm-1-00001-deployment-6f47c67945-s59dl:235:235 [1] NCCL INFO Channel 20/0 : 1[1] -> 0[0] via P2P/IPC
[2025-08-08 09:09:09 TP3] Scheduler hit an exception: Traceback (most recent call last):
File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2534, in run_scheduler_process
scheduler = Scheduler(
File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 313, in __init__
self.tp_worker = TpWorkerClass(
File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 84, in __init__
self.model_runner = ModelRunner(
File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 235, in __init__
min_per_gpu_memory = self.init_torch_distributed()
File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 559, in init_torch_distributed
initialize_model_parallel(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 1336, in initialize_model_parallel
_TP = init_model_parallel_group(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 1124, in init_model_parallel_group
return GroupCoordinator(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 280, in __init__
self.pynccl_comm = PyNcclCommunicator(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl.py", line 110, in __init__
self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 375, in ncclCommInitRank
self.NCCL_CHECK(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in NCCL_CHECK
raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
[2025-08-08 09:09:09 TP1] Scheduler hit an exception: Traceback (most recent call last):
File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2534, in run_scheduler_process
scheduler = Scheduler(
File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 313, in __init__
self.tp_worker = TpWorkerClass(
File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 84, in __init__
self.model_runner = ModelRunner(
File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 235, in __init__
min_per_gpu_memory = self.init_torch_distributed()
File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 559, in init_torch_distributed
initialize_model_parallel(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 1336, in initialize_model_parallel
_TP = init_model_parallel_group(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 1124, in init_model_parallel_group
return GroupCoordinator(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 280, in __init__
self.pynccl_comm = PyNcclCommunicator(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl.py", line 110, in __init__
self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 375, in ncclCommInitRank
self.NCCL_CHECK(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in NCCL_CHECK
raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
[2025-08-08 09:09:09] Received sigquit from a child process. It usually means the child failed.
[2025-08-08 09:09:09] Received sigquit from a child process. It usually means the child failed.
[2025-08-08 09:09:09 TP0] Scheduler hit an exception: Traceback (most recent call last):
File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2534, in run_scheduler_process
scheduler = Scheduler(
File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 313, in __init__
self.tp_worker = TpWorkerClass(
File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 84, in __init__
self.model_runner = ModelRunner(
File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 235, in __init__
min_per_gpu_memory = self.init_torch_distributed()
File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 559, in init_torch_distributed
initialize_model_parallel(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 1336, in initialize_model_parallel
_TP = init_model_parallel_group(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 1124, in init_model_parallel_group
return GroupCoordinator(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 280, in __init__
self.pynccl_comm = PyNcclCommunicator(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl.py", line 110, in __init__
self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 375, in ncclCommInitRank
self.NCCL_CHECK(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in NCCL_CHECK
raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
[2025-08-08 09:09:09 TP2] Scheduler hit an exception: Traceback (most recent call last):
File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2534, in run_scheduler_process
scheduler = Scheduler(
File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 313, in __init__
self.tp_worker = TpWorkerClass(
File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 84, in __init__
self.model_runner = ModelRunner(
File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 235, in __init__
min_per_gpu_memory = self.init_torch_distributed()
File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 559, in init_torch_distributed
initialize_model_parallel(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 1336, in initialize_model_parallel
_TP = init_model_parallel_group(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 1124, in init_model_parallel_group
return GroupCoordinator(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/parallel_state.py", line 280, in __init__
self.pynccl_comm = PyNcclCommunicator(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl.py", line 110, in __init__
self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 375, in ncclCommInitRank
self.NCCL_CHECK(
File "/sgl-workspace/sglang/python/sglang/srt/distributed/device_communicators/pynccl_wrapper.py", line 350, in NCCL_CHECK
raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
[2025-08-08 09:09:09] Received sigquit from a child process. It usually means the child failed.

### Reproduction

```
python3 -m sglang.launch_server \
  --model-path /data/GLM-4.5 \
  --tp-size 4 \
  --tool-call-parser glm45  \
  --reasoning-parser glm45  \
  --speculative-algorithm EAGLE \
  --speculative-num-steps 3  \
  --speculative-eagle-topk 1  \
  --speculative-num-draft-tokens 4 \
  --mem-fraction-static 0.7 \
  --disable-shared-experts-fusion \
  --served-model-name glm-4.5 \
  --host 0.0.0.0 \
  --port 8000
```

### Environment

==========
== CUDA ==
==========
CUDA Version 12.6.1
Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
Python: 3.10.12 (main, May 27 2025, 17:12:29) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA H200
GPU 0,1,2,3 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.6, V12.6.68
CUDA Driver Version: 575.57.08
PyTorch: 2.7.1+cu126
sglang: 0.4.10.post2
sgl_kernel: 0.2.8
flashinfer_python: 0.2.9rc2
triton: 3.3.1
transformers: 4.54.1
torchao: 0.9.0+cu126
numpy: 2.2.6
aiohttp: 3.12.15
fastapi: 0.116.1
hf_transfer: 0.1.9
huggingface_hub: 0.34.3
interegular: 0.3.3
modelscope: 1.28.1
orjson: 3.11.1
outlines: 0.1.11
packaging: 25.0
psutil: 7.0.0
pydantic: 2.11.7
python-multipart: 0.0.20
pyzmq: 27.0.1
uvicorn: 0.35.0
uvloop: 0.21.0
vllm: Module Not Found
xgrammar: 0.1.22
openai: 1.98.0
tiktoken: 0.9.0
anthropic: 0.60.0
litellm: 1.74.15.post1
decord: 0.6.0
NVIDIA Topology:
[4mGPU0 GPU1 GPU2 GPU3 NIC0 NIC1 NIC2 NIC3 NIC4 NIC5 NIC6 NIC7 NIC8 NIC9 CPU Affinity NUMA Affinity GPU NUMA ID[0m
GPU0 X NV18 NV18 NV18 PIX NODE NODE NODE SYS SYS SYS SYS SYS SYS 0-47,96-143 0 N/A
GPU1 NV18 X NV18 NV18 NODE PIX NODE NODE SYS SYS SYS SYS SYS SYS 0-47,96-143 0 N/A
GPU2 NV18 NV18 X NV18 NODE NODE PIX NODE SYS SYS SYS SYS SYS SYS 0-47,96-143 0 N/A
GPU3 NV18 NV18 NV18 X NODE NODE NODE PIX SYS SYS SYS SYS SYS SYS 0-47,96-143 0 N/A
NIC0 PIX NODE NODE NODE X NODE NODE NODE SYS SYS SYS SYS SYS SYS
NIC1 NODE PIX NODE NODE NODE X NODE NODE SYS SYS SYS SYS SYS SYS
NIC2 NODE NODE PIX NODE NODE NODE X NODE SYS SYS SYS SYS SYS SYS
NIC3 NODE NODE NODE PIX NODE NODE NODE X SYS SYS SYS SYS SYS SYS
NIC4 SYS SYS SYS SYS SYS SYS SYS SYS X NODE NODE NODE NODE NODE
NIC5 SYS SYS SYS SYS SYS SYS SYS SYS NODE X NODE NODE NODE NODE
NIC6 SYS SYS SYS SYS SYS SYS SYS SYS NODE NODE X NODE NODE NODE
NIC7 SYS SYS SYS SYS SYS SYS SYS SYS NODE NODE NODE X NODE NODE
NIC8 SYS SYS SYS SYS SYS SYS SYS SYS NODE NODE NODE NODE X PIX
NIC9 SYS SYS SYS SYS SYS SYS SYS SYS NODE NODE NODE NODE PIX X
Legend:
X = Self
SYS = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
PHB = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
PXB = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
PIX = Connection traversing at most a single PCIe bridge
NV# = Connection traversing a bonded set of # NVLinks
NIC Legend:
NIC0: ibp25s0
NIC1: ibp42s0
NIC2: ibp59s0
NIC3: ibp76s0
NIC4: ibp155s0
NIC5: ibp171s0
NIC6: ibp193s0
NIC7: ibp203s0
NIC8: rocep216s0f0
NIC9: rocep216s0f1
ulimit soft: 1048576

**Comment by salt00n9** [comment]
Hi everyone,

My apologies for the startup error I was experiencing. I was able to resolve the issue by increasing the shared memory (shm) size when launching the container. The default size was too small for the model to load properly.
