### ISSUE TITLE
[Bug] Eagle Triton attention backend illegal memory

### ISSUE THREAD

**Issue by qywu** [sgl-project/sglang#9412]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

This bug is related to https://github.com/sgl-project/sglang/pull/9344.

However, the pr did not fully fix the issue. I am still getting illegal memory access error when hosting the model. The error doesn't show up immediately until after sending about 100~150 queries. The error happens with both cuda graph and without cuda graph.

<img width="1296" height="503" alt="Image" src="https://github.com/user-attachments/assets/b0f501eb-0ab9-4f01-b085-ded3afbd8bf4" />

<img width="1288" height="448" alt="Image" src="https://github.com/user-attachments/assets/f6b2f296-6e3d-465d-a210-c592e6300d20" />

### Reproduction

*Launch command*
```bash
python -m sglang.launch_server   --model-path meta-llama/Llama-3.1-8B-Instruct   --port 8005   --tensor-parallel-size 1   --speculative-algo EAGLE3   --speculative-draft jamesliu1/sglang-EAGLE3-Llama-3.1-Instruct-8B  --speculative-num-steps 3   --speculative-eagle-topk 1   --speculative-num-draft-tokens 4   --mem-fraction 0.6 --attention-backend triton --dtype bfloat16
```

*Eval command*
```bash
OPENAI_API_KEY="" python -m gpt_oss.evals --model openai/gpt-oss-120b --eval gpqa --base-url http://localhost:8005/v1/ --reasoning-effort low --n-threads 256 --sampler "chat_completions" --temperature=0.0 --max-tokens 4096
```

### Environment

B200 cuda12.9 with newest sglang main branch

**Comment by ispobock** [comment]
@qywu Why you benchmark llama3 with gpt-oss eval? The context length of the llama3 draft model is only 2048 (https://huggingface.co/jamesliu1/sglang-EAGLE3-Llama-3.1-Instruct-8B/blob/main/config.json#L11). So some of the requests in gpqa may exceed the context length in the draft model memory pool. Could you try gpt-oss model with EAGLE?

**Comment by qywu** [comment]
Thanks. After changing the the config max_position_embeddings, the error is gone now. `qywu/sglang-EAGLE3-Llama-3.1-Instruct-8B`

**Comment by hnyls2002** [comment]
@qywu Try to reset your context length. I have turned off the default setting of overriding with a longer context length. #9388
